package com.cnLive.dao;

import com.cnLive.pojo.CmsContent;
import com.cnLive.pojo.CmsContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int countByExample(CmsContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int deleteByExample(CmsContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int insert(CmsContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int insertSelective(CmsContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    List<CmsContent> selectByExampleWithBLOBs(CmsContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    List<CmsContent> selectByExample(CmsContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    CmsContent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CmsContent record, @Param("example") CmsContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CmsContent record, @Param("example") CmsContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CmsContent record, @Param("example") CmsContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmsContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CmsContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsContent record);
}