package com.cnLive.dao;

import com.cnLive.pojo.CmsVideo;
import com.cnLive.pojo.CmsVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsVideoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	int countByExample(CmsVideoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	int deleteByExample(CmsVideoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	int insert(CmsVideo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	int insertSelective(CmsVideo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	List<CmsVideo> selectByExample(CmsVideoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	CmsVideo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") CmsVideo record,
			@Param("example") CmsVideoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CmsVideo record,
			@Param("example") CmsVideoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CmsVideo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CmsVideo record);
}