package com.cnLive.dao;

import com.cnLive.pojo.mediaAsset;
import com.cnLive.pojo.mediaAssetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface mediaAssetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	int countByExample(mediaAssetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	int deleteByExample(mediaAssetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	int insert(mediaAsset record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	int insertSelective(mediaAsset record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	List<mediaAsset> selectByExample(mediaAssetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	mediaAsset selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") mediaAsset record,
			@Param("example") mediaAssetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") mediaAsset record,
			@Param("example") mediaAssetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(mediaAsset record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	int updateByPrimaryKey(mediaAsset record);
}