package com.cnLive.pojo;

import java.util.Date;

public class CmsContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.catid
     *
     * @mbggenerated
     */
    private String catid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.pathids
     *
     * @mbggenerated
     */
    private String pathids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.modelid
     *
     * @mbggenerated
     */
    private String modelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.classify
     *
     * @mbggenerated
     */
    private String classify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.subtitle
     *
     * @mbggenerated
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.citetitle
     *
     * @mbggenerated
     */
    private String citetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.thumb
     *
     * @mbggenerated
     */
    private String thumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.editor
     *
     * @mbggenerated
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.sourceid
     *
     * @mbggenerated
     */
    private String sourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.wapurl
     *
     * @mbggenerated
     */
    private String wapurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.constants
     *
     * @mbggenerated
     */
    private String constants;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.createdby
     *
     * @mbggenerated
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.published
     *
     * @mbggenerated
     */
    private Date published;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.publishedby
     *
     * @mbggenerated
     */
    private String publishedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.unpublished
     *
     * @mbggenerated
     */
    private Long unpublished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.unpublishedby
     *
     * @mbggenerated
     */
    private Integer unpublishedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.modifiedby
     *
     * @mbggenerated
     */
    private String modifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.checked
     *
     * @mbggenerated
     */
    private Date checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.checkedby
     *
     * @mbggenerated
     */
    private String checkedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.locked
     *
     * @mbggenerated
     */
    private Date locked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.lockedby
     *
     * @mbggenerated
     */
    private String lockedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.noted
     *
     * @mbggenerated
     */
    private Date noted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.notedby
     *
     * @mbggenerated
     */
    private String notedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.note
     *
     * @mbggenerated
     */
    private Boolean note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.workflow_step
     *
     * @mbggenerated
     */
    private Boolean workflowStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.workflow_roleid
     *
     * @mbggenerated
     */
    private String workflowRoleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.iscontribute
     *
     * @mbggenerated
     */
    private String iscontribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.spaceid
     *
     * @mbggenerated
     */
    private String spaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.related
     *
     * @mbggenerated
     */
    private Byte related;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.pv
     *
     * @mbggenerated
     */
    private Integer pv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.allowcomment
     *
     * @mbggenerated
     */
    private String allowcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.docExtendJson
     *
     * @mbggenerated
     */
    private String docextendjson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.digest
     *
     * @mbggenerated
     */
    private String digest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.attribute
     *
     * @mbggenerated
     */
    private String attribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.extendCount
     *
     * @mbggenerated
     */
    private Integer extendcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.correlation
     *
     * @mbggenerated
     */
    private String correlation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.catName
     *
     * @mbggenerated
     */
    private String catname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.voteid
     *
     * @mbggenerated
     */
    private String voteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.site_id
     *
     * @mbggenerated
     */
    private String siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.grade
     *
     * @mbggenerated
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.publishedbyid
     *
     * @mbggenerated
     */
    private String publishedbyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.syn_catid
     *
     * @mbggenerated
     */
    private String synCatid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.memberid
     *
     * @mbggenerated
     */
    private String memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.two_code
     *
     * @mbggenerated
     */
    private String twoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.content_mark
     *
     * @mbggenerated
     */
    private String contentMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.isposter
     *
     * @mbggenerated
     */
    private Integer isposter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.is_headline
     *
     * @mbggenerated
     */
    private Integer isHeadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.is_top
     *
     * @mbggenerated
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.lock_content
     *
     * @mbggenerated
     */
    private String lockContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.static_url
     *
     * @mbggenerated
     */
    private String staticUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.dynamic_url
     *
     * @mbggenerated
     */
    private String dynamicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.img1
     *
     * @mbggenerated
     */
    private String img1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.img2
     *
     * @mbggenerated
     */
    private String img2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.img3
     *
     * @mbggenerated
     */
    private String img3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.img4
     *
     * @mbggenerated
     */
    private String img4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.charge_sign
     *
     * @mbggenerated
     */
    private String chargeSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.linkcontent_id
     *
     * @mbggenerated
     */
    private String linkcontentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.icms_media_id
     *
     * @mbggenerated
     */
    private String icmsMediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.live_url
     *
     * @mbggenerated
     */
    private String liveUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.subcat_id
     *
     * @mbggenerated
     */
    private String subcatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.subcat_name
     *
     * @mbggenerated
     */
    private String subcatName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_content.color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.id
     *
     * @return the value of cms_content.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.id
     *
     * @param id the value for cms_content.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.catid
     *
     * @return the value of cms_content.catid
     *
     * @mbggenerated
     */
    public String getCatid() {
        return catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.catid
     *
     * @param catid the value for cms_content.catid
     *
     * @mbggenerated
     */
    public void setCatid(String catid) {
        this.catid = catid == null ? null : catid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.pathids
     *
     * @return the value of cms_content.pathids
     *
     * @mbggenerated
     */
    public String getPathids() {
        return pathids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.pathids
     *
     * @param pathids the value for cms_content.pathids
     *
     * @mbggenerated
     */
    public void setPathids(String pathids) {
        this.pathids = pathids == null ? null : pathids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.modelid
     *
     * @return the value of cms_content.modelid
     *
     * @mbggenerated
     */
    public String getModelid() {
        return modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.modelid
     *
     * @param modelid the value for cms_content.modelid
     *
     * @mbggenerated
     */
    public void setModelid(String modelid) {
        this.modelid = modelid == null ? null : modelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.classify
     *
     * @return the value of cms_content.classify
     *
     * @mbggenerated
     */
    public String getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.classify
     *
     * @param classify the value for cms_content.classify
     *
     * @mbggenerated
     */
    public void setClassify(String classify) {
        this.classify = classify == null ? null : classify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.title
     *
     * @return the value of cms_content.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.title
     *
     * @param title the value for cms_content.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.subtitle
     *
     * @return the value of cms_content.subtitle
     *
     * @mbggenerated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.subtitle
     *
     * @param subtitle the value for cms_content.subtitle
     *
     * @mbggenerated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.citetitle
     *
     * @return the value of cms_content.citetitle
     *
     * @mbggenerated
     */
    public String getCitetitle() {
        return citetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.citetitle
     *
     * @param citetitle the value for cms_content.citetitle
     *
     * @mbggenerated
     */
    public void setCitetitle(String citetitle) {
        this.citetitle = citetitle == null ? null : citetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.thumb
     *
     * @return the value of cms_content.thumb
     *
     * @mbggenerated
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.thumb
     *
     * @param thumb the value for cms_content.thumb
     *
     * @mbggenerated
     */
    public void setThumb(String thumb) {
        this.thumb = thumb == null ? null : thumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.tags
     *
     * @return the value of cms_content.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.tags
     *
     * @param tags the value for cms_content.tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.author
     *
     * @return the value of cms_content.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.author
     *
     * @param author the value for cms_content.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.editor
     *
     * @return the value of cms_content.editor
     *
     * @mbggenerated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.editor
     *
     * @param editor the value for cms_content.editor
     *
     * @mbggenerated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.sourceid
     *
     * @return the value of cms_content.sourceid
     *
     * @mbggenerated
     */
    public String getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.sourceid
     *
     * @param sourceid the value for cms_content.sourceid
     *
     * @mbggenerated
     */
    public void setSourceid(String sourceid) {
        this.sourceid = sourceid == null ? null : sourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.url
     *
     * @return the value of cms_content.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.url
     *
     * @param url the value for cms_content.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.wapurl
     *
     * @return the value of cms_content.wapurl
     *
     * @mbggenerated
     */
    public String getWapurl() {
        return wapurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.wapurl
     *
     * @param wapurl the value for cms_content.wapurl
     *
     * @mbggenerated
     */
    public void setWapurl(String wapurl) {
        this.wapurl = wapurl == null ? null : wapurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.weight
     *
     * @return the value of cms_content.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.weight
     *
     * @param weight the value for cms_content.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.status
     *
     * @return the value of cms_content.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.status
     *
     * @param status the value for cms_content.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.constants
     *
     * @return the value of cms_content.constants
     *
     * @mbggenerated
     */
    public String getConstants() {
        return constants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.constants
     *
     * @param constants the value for cms_content.constants
     *
     * @mbggenerated
     */
    public void setConstants(String constants) {
        this.constants = constants == null ? null : constants.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.created
     *
     * @return the value of cms_content.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.created
     *
     * @param created the value for cms_content.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.createdby
     *
     * @return the value of cms_content.createdby
     *
     * @mbggenerated
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.createdby
     *
     * @param createdby the value for cms_content.createdby
     *
     * @mbggenerated
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.published
     *
     * @return the value of cms_content.published
     *
     * @mbggenerated
     */
    public Date getPublished() {
        return published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.published
     *
     * @param published the value for cms_content.published
     *
     * @mbggenerated
     */
    public void setPublished(Date published) {
        this.published = published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.publishedby
     *
     * @return the value of cms_content.publishedby
     *
     * @mbggenerated
     */
    public String getPublishedby() {
        return publishedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.publishedby
     *
     * @param publishedby the value for cms_content.publishedby
     *
     * @mbggenerated
     */
    public void setPublishedby(String publishedby) {
        this.publishedby = publishedby == null ? null : publishedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.unpublished
     *
     * @return the value of cms_content.unpublished
     *
     * @mbggenerated
     */
    public Long getUnpublished() {
        return unpublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.unpublished
     *
     * @param unpublished the value for cms_content.unpublished
     *
     * @mbggenerated
     */
    public void setUnpublished(Long unpublished) {
        this.unpublished = unpublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.unpublishedby
     *
     * @return the value of cms_content.unpublishedby
     *
     * @mbggenerated
     */
    public Integer getUnpublishedby() {
        return unpublishedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.unpublishedby
     *
     * @param unpublishedby the value for cms_content.unpublishedby
     *
     * @mbggenerated
     */
    public void setUnpublishedby(Integer unpublishedby) {
        this.unpublishedby = unpublishedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.modified
     *
     * @return the value of cms_content.modified
     *
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.modified
     *
     * @param modified the value for cms_content.modified
     *
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.modifiedby
     *
     * @return the value of cms_content.modifiedby
     *
     * @mbggenerated
     */
    public String getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.modifiedby
     *
     * @param modifiedby the value for cms_content.modifiedby
     *
     * @mbggenerated
     */
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby == null ? null : modifiedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.checked
     *
     * @return the value of cms_content.checked
     *
     * @mbggenerated
     */
    public Date getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.checked
     *
     * @param checked the value for cms_content.checked
     *
     * @mbggenerated
     */
    public void setChecked(Date checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.checkedby
     *
     * @return the value of cms_content.checkedby
     *
     * @mbggenerated
     */
    public String getCheckedby() {
        return checkedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.checkedby
     *
     * @param checkedby the value for cms_content.checkedby
     *
     * @mbggenerated
     */
    public void setCheckedby(String checkedby) {
        this.checkedby = checkedby == null ? null : checkedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.locked
     *
     * @return the value of cms_content.locked
     *
     * @mbggenerated
     */
    public Date getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.locked
     *
     * @param locked the value for cms_content.locked
     *
     * @mbggenerated
     */
    public void setLocked(Date locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.lockedby
     *
     * @return the value of cms_content.lockedby
     *
     * @mbggenerated
     */
    public String getLockedby() {
        return lockedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.lockedby
     *
     * @param lockedby the value for cms_content.lockedby
     *
     * @mbggenerated
     */
    public void setLockedby(String lockedby) {
        this.lockedby = lockedby == null ? null : lockedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.noted
     *
     * @return the value of cms_content.noted
     *
     * @mbggenerated
     */
    public Date getNoted() {
        return noted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.noted
     *
     * @param noted the value for cms_content.noted
     *
     * @mbggenerated
     */
    public void setNoted(Date noted) {
        this.noted = noted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.notedby
     *
     * @return the value of cms_content.notedby
     *
     * @mbggenerated
     */
    public String getNotedby() {
        return notedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.notedby
     *
     * @param notedby the value for cms_content.notedby
     *
     * @mbggenerated
     */
    public void setNotedby(String notedby) {
        this.notedby = notedby == null ? null : notedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.note
     *
     * @return the value of cms_content.note
     *
     * @mbggenerated
     */
    public Boolean getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.note
     *
     * @param note the value for cms_content.note
     *
     * @mbggenerated
     */
    public void setNote(Boolean note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.workflow_step
     *
     * @return the value of cms_content.workflow_step
     *
     * @mbggenerated
     */
    public Boolean getWorkflowStep() {
        return workflowStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.workflow_step
     *
     * @param workflowStep the value for cms_content.workflow_step
     *
     * @mbggenerated
     */
    public void setWorkflowStep(Boolean workflowStep) {
        this.workflowStep = workflowStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.workflow_roleid
     *
     * @return the value of cms_content.workflow_roleid
     *
     * @mbggenerated
     */
    public String getWorkflowRoleid() {
        return workflowRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.workflow_roleid
     *
     * @param workflowRoleid the value for cms_content.workflow_roleid
     *
     * @mbggenerated
     */
    public void setWorkflowRoleid(String workflowRoleid) {
        this.workflowRoleid = workflowRoleid == null ? null : workflowRoleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.iscontribute
     *
     * @return the value of cms_content.iscontribute
     *
     * @mbggenerated
     */
    public String getIscontribute() {
        return iscontribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.iscontribute
     *
     * @param iscontribute the value for cms_content.iscontribute
     *
     * @mbggenerated
     */
    public void setIscontribute(String iscontribute) {
        this.iscontribute = iscontribute == null ? null : iscontribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.spaceid
     *
     * @return the value of cms_content.spaceid
     *
     * @mbggenerated
     */
    public String getSpaceid() {
        return spaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.spaceid
     *
     * @param spaceid the value for cms_content.spaceid
     *
     * @mbggenerated
     */
    public void setSpaceid(String spaceid) {
        this.spaceid = spaceid == null ? null : spaceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.related
     *
     * @return the value of cms_content.related
     *
     * @mbggenerated
     */
    public Byte getRelated() {
        return related;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.related
     *
     * @param related the value for cms_content.related
     *
     * @mbggenerated
     */
    public void setRelated(Byte related) {
        this.related = related;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.pv
     *
     * @return the value of cms_content.pv
     *
     * @mbggenerated
     */
    public Integer getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.pv
     *
     * @param pv the value for cms_content.pv
     *
     * @mbggenerated
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.allowcomment
     *
     * @return the value of cms_content.allowcomment
     *
     * @mbggenerated
     */
    public String getAllowcomment() {
        return allowcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.allowcomment
     *
     * @param allowcomment the value for cms_content.allowcomment
     *
     * @mbggenerated
     */
    public void setAllowcomment(String allowcomment) {
        this.allowcomment = allowcomment == null ? null : allowcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.docExtendJson
     *
     * @return the value of cms_content.docExtendJson
     *
     * @mbggenerated
     */
    public String getDocextendjson() {
        return docextendjson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.docExtendJson
     *
     * @param docextendjson the value for cms_content.docExtendJson
     *
     * @mbggenerated
     */
    public void setDocextendjson(String docextendjson) {
        this.docextendjson = docextendjson == null ? null : docextendjson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.digest
     *
     * @return the value of cms_content.digest
     *
     * @mbggenerated
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.digest
     *
     * @param digest the value for cms_content.digest
     *
     * @mbggenerated
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.attribute
     *
     * @return the value of cms_content.attribute
     *
     * @mbggenerated
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.attribute
     *
     * @param attribute the value for cms_content.attribute
     *
     * @mbggenerated
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute == null ? null : attribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.extendCount
     *
     * @return the value of cms_content.extendCount
     *
     * @mbggenerated
     */
    public Integer getExtendcount() {
        return extendcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.extendCount
     *
     * @param extendcount the value for cms_content.extendCount
     *
     * @mbggenerated
     */
    public void setExtendcount(Integer extendcount) {
        this.extendcount = extendcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.correlation
     *
     * @return the value of cms_content.correlation
     *
     * @mbggenerated
     */
    public String getCorrelation() {
        return correlation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.correlation
     *
     * @param correlation the value for cms_content.correlation
     *
     * @mbggenerated
     */
    public void setCorrelation(String correlation) {
        this.correlation = correlation == null ? null : correlation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.description
     *
     * @return the value of cms_content.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.description
     *
     * @param description the value for cms_content.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.catName
     *
     * @return the value of cms_content.catName
     *
     * @mbggenerated
     */
    public String getCatname() {
        return catname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.catName
     *
     * @param catname the value for cms_content.catName
     *
     * @mbggenerated
     */
    public void setCatname(String catname) {
        this.catname = catname == null ? null : catname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.voteid
     *
     * @return the value of cms_content.voteid
     *
     * @mbggenerated
     */
    public String getVoteid() {
        return voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.voteid
     *
     * @param voteid the value for cms_content.voteid
     *
     * @mbggenerated
     */
    public void setVoteid(String voteid) {
        this.voteid = voteid == null ? null : voteid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.site_id
     *
     * @return the value of cms_content.site_id
     *
     * @mbggenerated
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.site_id
     *
     * @param siteId the value for cms_content.site_id
     *
     * @mbggenerated
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId == null ? null : siteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.grade
     *
     * @return the value of cms_content.grade
     *
     * @mbggenerated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.grade
     *
     * @param grade the value for cms_content.grade
     *
     * @mbggenerated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.publishedbyid
     *
     * @return the value of cms_content.publishedbyid
     *
     * @mbggenerated
     */
    public String getPublishedbyid() {
        return publishedbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.publishedbyid
     *
     * @param publishedbyid the value for cms_content.publishedbyid
     *
     * @mbggenerated
     */
    public void setPublishedbyid(String publishedbyid) {
        this.publishedbyid = publishedbyid == null ? null : publishedbyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.syn_catid
     *
     * @return the value of cms_content.syn_catid
     *
     * @mbggenerated
     */
    public String getSynCatid() {
        return synCatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.syn_catid
     *
     * @param synCatid the value for cms_content.syn_catid
     *
     * @mbggenerated
     */
    public void setSynCatid(String synCatid) {
        this.synCatid = synCatid == null ? null : synCatid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.memberid
     *
     * @return the value of cms_content.memberid
     *
     * @mbggenerated
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.memberid
     *
     * @param memberid the value for cms_content.memberid
     *
     * @mbggenerated
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.two_code
     *
     * @return the value of cms_content.two_code
     *
     * @mbggenerated
     */
    public String getTwoCode() {
        return twoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.two_code
     *
     * @param twoCode the value for cms_content.two_code
     *
     * @mbggenerated
     */
    public void setTwoCode(String twoCode) {
        this.twoCode = twoCode == null ? null : twoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.content_mark
     *
     * @return the value of cms_content.content_mark
     *
     * @mbggenerated
     */
    public String getContentMark() {
        return contentMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.content_mark
     *
     * @param contentMark the value for cms_content.content_mark
     *
     * @mbggenerated
     */
    public void setContentMark(String contentMark) {
        this.contentMark = contentMark == null ? null : contentMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.isposter
     *
     * @return the value of cms_content.isposter
     *
     * @mbggenerated
     */
    public Integer getIsposter() {
        return isposter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.isposter
     *
     * @param isposter the value for cms_content.isposter
     *
     * @mbggenerated
     */
    public void setIsposter(Integer isposter) {
        this.isposter = isposter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.is_headline
     *
     * @return the value of cms_content.is_headline
     *
     * @mbggenerated
     */
    public Integer getIsHeadline() {
        return isHeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.is_headline
     *
     * @param isHeadline the value for cms_content.is_headline
     *
     * @mbggenerated
     */
    public void setIsHeadline(Integer isHeadline) {
        this.isHeadline = isHeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.is_top
     *
     * @return the value of cms_content.is_top
     *
     * @mbggenerated
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.is_top
     *
     * @param isTop the value for cms_content.is_top
     *
     * @mbggenerated
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.lock_content
     *
     * @return the value of cms_content.lock_content
     *
     * @mbggenerated
     */
    public String getLockContent() {
        return lockContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.lock_content
     *
     * @param lockContent the value for cms_content.lock_content
     *
     * @mbggenerated
     */
    public void setLockContent(String lockContent) {
        this.lockContent = lockContent == null ? null : lockContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.static_url
     *
     * @return the value of cms_content.static_url
     *
     * @mbggenerated
     */
    public String getStaticUrl() {
        return staticUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.static_url
     *
     * @param staticUrl the value for cms_content.static_url
     *
     * @mbggenerated
     */
    public void setStaticUrl(String staticUrl) {
        this.staticUrl = staticUrl == null ? null : staticUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.dynamic_url
     *
     * @return the value of cms_content.dynamic_url
     *
     * @mbggenerated
     */
    public String getDynamicUrl() {
        return dynamicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.dynamic_url
     *
     * @param dynamicUrl the value for cms_content.dynamic_url
     *
     * @mbggenerated
     */
    public void setDynamicUrl(String dynamicUrl) {
        this.dynamicUrl = dynamicUrl == null ? null : dynamicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.img1
     *
     * @return the value of cms_content.img1
     *
     * @mbggenerated
     */
    public String getImg1() {
        return img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.img1
     *
     * @param img1 the value for cms_content.img1
     *
     * @mbggenerated
     */
    public void setImg1(String img1) {
        this.img1 = img1 == null ? null : img1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.img2
     *
     * @return the value of cms_content.img2
     *
     * @mbggenerated
     */
    public String getImg2() {
        return img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.img2
     *
     * @param img2 the value for cms_content.img2
     *
     * @mbggenerated
     */
    public void setImg2(String img2) {
        this.img2 = img2 == null ? null : img2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.img3
     *
     * @return the value of cms_content.img3
     *
     * @mbggenerated
     */
    public String getImg3() {
        return img3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.img3
     *
     * @param img3 the value for cms_content.img3
     *
     * @mbggenerated
     */
    public void setImg3(String img3) {
        this.img3 = img3 == null ? null : img3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.img4
     *
     * @return the value of cms_content.img4
     *
     * @mbggenerated
     */
    public String getImg4() {
        return img4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.img4
     *
     * @param img4 the value for cms_content.img4
     *
     * @mbggenerated
     */
    public void setImg4(String img4) {
        this.img4 = img4 == null ? null : img4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.charge_sign
     *
     * @return the value of cms_content.charge_sign
     *
     * @mbggenerated
     */
    public String getChargeSign() {
        return chargeSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.charge_sign
     *
     * @param chargeSign the value for cms_content.charge_sign
     *
     * @mbggenerated
     */
    public void setChargeSign(String chargeSign) {
        this.chargeSign = chargeSign == null ? null : chargeSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.linkcontent_id
     *
     * @return the value of cms_content.linkcontent_id
     *
     * @mbggenerated
     */
    public String getLinkcontentId() {
        return linkcontentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.linkcontent_id
     *
     * @param linkcontentId the value for cms_content.linkcontent_id
     *
     * @mbggenerated
     */
    public void setLinkcontentId(String linkcontentId) {
        this.linkcontentId = linkcontentId == null ? null : linkcontentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.icms_media_id
     *
     * @return the value of cms_content.icms_media_id
     *
     * @mbggenerated
     */
    public String getIcmsMediaId() {
        return icmsMediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.icms_media_id
     *
     * @param icmsMediaId the value for cms_content.icms_media_id
     *
     * @mbggenerated
     */
    public void setIcmsMediaId(String icmsMediaId) {
        this.icmsMediaId = icmsMediaId == null ? null : icmsMediaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.live_url
     *
     * @return the value of cms_content.live_url
     *
     * @mbggenerated
     */
    public String getLiveUrl() {
        return liveUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.live_url
     *
     * @param liveUrl the value for cms_content.live_url
     *
     * @mbggenerated
     */
    public void setLiveUrl(String liveUrl) {
        this.liveUrl = liveUrl == null ? null : liveUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.subcat_id
     *
     * @return the value of cms_content.subcat_id
     *
     * @mbggenerated
     */
    public String getSubcatId() {
        return subcatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.subcat_id
     *
     * @param subcatId the value for cms_content.subcat_id
     *
     * @mbggenerated
     */
    public void setSubcatId(String subcatId) {
        this.subcatId = subcatId == null ? null : subcatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.subcat_name
     *
     * @return the value of cms_content.subcat_name
     *
     * @mbggenerated
     */
    public String getSubcatName() {
        return subcatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.subcat_name
     *
     * @param subcatName the value for cms_content.subcat_name
     *
     * @mbggenerated
     */
    public void setSubcatName(String subcatName) {
        this.subcatName = subcatName == null ? null : subcatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_content.color
     *
     * @return the value of cms_content.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_content.color
     *
     * @param color the value for cms_content.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }
}