package com.cnLive.pojo;

import java.util.Date;

public class CmsVideo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.contentid
	 * @mbggenerated
	 */
	private String contentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.videoname
	 * @mbggenerated
	 */
	private String videoname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.videourl
	 * @mbggenerated
	 */
	private String videourl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.videoclassify
	 * @mbggenerated
	 */
	private String videoclassify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.time
	 * @mbggenerated
	 */
	private String time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.special
	 * @mbggenerated
	 */
	private String special;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.videoremark
	 * @mbggenerated
	 */
	private String videoremark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.site_id
	 * @mbggenerated
	 */
	private String siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.createdtime
	 * @mbggenerated
	 */
	private Date createdtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.film_type
	 * @mbggenerated
	 */
	private String filmType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.media_column
	 * @mbggenerated
	 */
	private String mediaColumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.film_level
	 * @mbggenerated
	 */
	private String filmLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.is_positive
	 * @mbggenerated
	 */
	private String isPositive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.director
	 * @mbggenerated
	 */
	private String director;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.to_star
	 * @mbggenerated
	 */
	private String toStar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.commodity_id
	 * @mbggenerated
	 */
	private String commodityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.free_time
	 * @mbggenerated
	 */
	private String freeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.related_content_types
	 * @mbggenerated
	 */
	private String relatedContentTypes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.countries_and_regions
	 * @mbggenerated
	 */
	private String countriesAndRegions;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.keyword
	 * @mbggenerated
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.content_type
	 * @mbggenerated
	 */
	private String contentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.down_url
	 * @mbggenerated
	 */
	private String downUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.copyright
	 * @mbggenerated
	 */
	private String copyright;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.picture1
	 * @mbggenerated
	 */
	private String picture1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.picture2
	 * @mbggenerated
	 */
	private String picture2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.picture3
	 * @mbggenerated
	 */
	private String picture3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.picture4
	 * @mbggenerated
	 */
	private String picture4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.today_free
	 * @mbggenerated
	 */
	private Date todayFree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.smooth_url
	 * @mbggenerated
	 */
	private String smoothUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.sd_url
	 * @mbggenerated
	 */
	private String sdUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.hd_url
	 * @mbggenerated
	 */
	private String hdUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.ultra_clear_url
	 * @mbggenerated
	 */
	private String ultraClearUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.score
	 * @mbggenerated
	 */
	private Double score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.release_year
	 * @mbggenerated
	 */
	private Integer releaseYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.release_time
	 * @mbggenerated
	 */
	private Date releaseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.program_source
	 * @mbggenerated
	 */
	private String programSource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.copyright_source
	 * @mbggenerated
	 */
	private String copyrightSource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.copyright_begindate
	 * @mbggenerated
	 */
	private Date copyrightBegindate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_video.copyright_enddate
	 * @mbggenerated
	 */
	private Date copyrightEnddate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.id
	 * @return  the value of cms_video.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.id
	 * @param id  the value for cms_video.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.contentid
	 * @return  the value of cms_video.contentid
	 * @mbggenerated
	 */
	public String getContentid() {
		return contentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.contentid
	 * @param contentid  the value for cms_video.contentid
	 * @mbggenerated
	 */
	public void setContentid(String contentid) {
		this.contentid = contentid == null ? null : contentid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.videoname
	 * @return  the value of cms_video.videoname
	 * @mbggenerated
	 */
	public String getVideoname() {
		return videoname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.videoname
	 * @param videoname  the value for cms_video.videoname
	 * @mbggenerated
	 */
	public void setVideoname(String videoname) {
		this.videoname = videoname == null ? null : videoname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.videourl
	 * @return  the value of cms_video.videourl
	 * @mbggenerated
	 */
	public String getVideourl() {
		return videourl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.videourl
	 * @param videourl  the value for cms_video.videourl
	 * @mbggenerated
	 */
	public void setVideourl(String videourl) {
		this.videourl = videourl == null ? null : videourl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.videoclassify
	 * @return  the value of cms_video.videoclassify
	 * @mbggenerated
	 */
	public String getVideoclassify() {
		return videoclassify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.videoclassify
	 * @param videoclassify  the value for cms_video.videoclassify
	 * @mbggenerated
	 */
	public void setVideoclassify(String videoclassify) {
		this.videoclassify = videoclassify == null ? null : videoclassify
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.time
	 * @return  the value of cms_video.time
	 * @mbggenerated
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.time
	 * @param time  the value for cms_video.time
	 * @mbggenerated
	 */
	public void setTime(String time) {
		this.time = time == null ? null : time.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.special
	 * @return  the value of cms_video.special
	 * @mbggenerated
	 */
	public String getSpecial() {
		return special;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.special
	 * @param special  the value for cms_video.special
	 * @mbggenerated
	 */
	public void setSpecial(String special) {
		this.special = special == null ? null : special.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.videoremark
	 * @return  the value of cms_video.videoremark
	 * @mbggenerated
	 */
	public String getVideoremark() {
		return videoremark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.videoremark
	 * @param videoremark  the value for cms_video.videoremark
	 * @mbggenerated
	 */
	public void setVideoremark(String videoremark) {
		this.videoremark = videoremark == null ? null : videoremark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.site_id
	 * @return  the value of cms_video.site_id
	 * @mbggenerated
	 */
	public String getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.site_id
	 * @param siteId  the value for cms_video.site_id
	 * @mbggenerated
	 */
	public void setSiteId(String siteId) {
		this.siteId = siteId == null ? null : siteId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.createdtime
	 * @return  the value of cms_video.createdtime
	 * @mbggenerated
	 */
	public Date getCreatedtime() {
		return createdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.createdtime
	 * @param createdtime  the value for cms_video.createdtime
	 * @mbggenerated
	 */
	public void setCreatedtime(Date createdtime) {
		this.createdtime = createdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.film_type
	 * @return  the value of cms_video.film_type
	 * @mbggenerated
	 */
	public String getFilmType() {
		return filmType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.film_type
	 * @param filmType  the value for cms_video.film_type
	 * @mbggenerated
	 */
	public void setFilmType(String filmType) {
		this.filmType = filmType == null ? null : filmType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.media_column
	 * @return  the value of cms_video.media_column
	 * @mbggenerated
	 */
	public String getMediaColumn() {
		return mediaColumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.media_column
	 * @param mediaColumn  the value for cms_video.media_column
	 * @mbggenerated
	 */
	public void setMediaColumn(String mediaColumn) {
		this.mediaColumn = mediaColumn == null ? null : mediaColumn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.film_level
	 * @return  the value of cms_video.film_level
	 * @mbggenerated
	 */
	public String getFilmLevel() {
		return filmLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.film_level
	 * @param filmLevel  the value for cms_video.film_level
	 * @mbggenerated
	 */
	public void setFilmLevel(String filmLevel) {
		this.filmLevel = filmLevel == null ? null : filmLevel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.is_positive
	 * @return  the value of cms_video.is_positive
	 * @mbggenerated
	 */
	public String getIsPositive() {
		return isPositive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.is_positive
	 * @param isPositive  the value for cms_video.is_positive
	 * @mbggenerated
	 */
	public void setIsPositive(String isPositive) {
		this.isPositive = isPositive == null ? null : isPositive.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.director
	 * @return  the value of cms_video.director
	 * @mbggenerated
	 */
	public String getDirector() {
		return director;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.director
	 * @param director  the value for cms_video.director
	 * @mbggenerated
	 */
	public void setDirector(String director) {
		this.director = director == null ? null : director.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.to_star
	 * @return  the value of cms_video.to_star
	 * @mbggenerated
	 */
	public String getToStar() {
		return toStar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.to_star
	 * @param toStar  the value for cms_video.to_star
	 * @mbggenerated
	 */
	public void setToStar(String toStar) {
		this.toStar = toStar == null ? null : toStar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.commodity_id
	 * @return  the value of cms_video.commodity_id
	 * @mbggenerated
	 */
	public String getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.commodity_id
	 * @param commodityId  the value for cms_video.commodity_id
	 * @mbggenerated
	 */
	public void setCommodityId(String commodityId) {
		this.commodityId = commodityId == null ? null : commodityId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.free_time
	 * @return  the value of cms_video.free_time
	 * @mbggenerated
	 */
	public String getFreeTime() {
		return freeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.free_time
	 * @param freeTime  the value for cms_video.free_time
	 * @mbggenerated
	 */
	public void setFreeTime(String freeTime) {
		this.freeTime = freeTime == null ? null : freeTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.related_content_types
	 * @return  the value of cms_video.related_content_types
	 * @mbggenerated
	 */
	public String getRelatedContentTypes() {
		return relatedContentTypes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.related_content_types
	 * @param relatedContentTypes  the value for cms_video.related_content_types
	 * @mbggenerated
	 */
	public void setRelatedContentTypes(String relatedContentTypes) {
		this.relatedContentTypes = relatedContentTypes == null ? null
				: relatedContentTypes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.countries_and_regions
	 * @return  the value of cms_video.countries_and_regions
	 * @mbggenerated
	 */
	public String getCountriesAndRegions() {
		return countriesAndRegions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.countries_and_regions
	 * @param countriesAndRegions  the value for cms_video.countries_and_regions
	 * @mbggenerated
	 */
	public void setCountriesAndRegions(String countriesAndRegions) {
		this.countriesAndRegions = countriesAndRegions == null ? null
				: countriesAndRegions.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.keyword
	 * @return  the value of cms_video.keyword
	 * @mbggenerated
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.keyword
	 * @param keyword  the value for cms_video.keyword
	 * @mbggenerated
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword == null ? null : keyword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.content_type
	 * @return  the value of cms_video.content_type
	 * @mbggenerated
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.content_type
	 * @param contentType  the value for cms_video.content_type
	 * @mbggenerated
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType == null ? null : contentType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.down_url
	 * @return  the value of cms_video.down_url
	 * @mbggenerated
	 */
	public String getDownUrl() {
		return downUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.down_url
	 * @param downUrl  the value for cms_video.down_url
	 * @mbggenerated
	 */
	public void setDownUrl(String downUrl) {
		this.downUrl = downUrl == null ? null : downUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.copyright
	 * @return  the value of cms_video.copyright
	 * @mbggenerated
	 */
	public String getCopyright() {
		return copyright;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.copyright
	 * @param copyright  the value for cms_video.copyright
	 * @mbggenerated
	 */
	public void setCopyright(String copyright) {
		this.copyright = copyright == null ? null : copyright.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.picture1
	 * @return  the value of cms_video.picture1
	 * @mbggenerated
	 */
	public String getPicture1() {
		return picture1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.picture1
	 * @param picture1  the value for cms_video.picture1
	 * @mbggenerated
	 */
	public void setPicture1(String picture1) {
		this.picture1 = picture1 == null ? null : picture1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.picture2
	 * @return  the value of cms_video.picture2
	 * @mbggenerated
	 */
	public String getPicture2() {
		return picture2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.picture2
	 * @param picture2  the value for cms_video.picture2
	 * @mbggenerated
	 */
	public void setPicture2(String picture2) {
		this.picture2 = picture2 == null ? null : picture2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.picture3
	 * @return  the value of cms_video.picture3
	 * @mbggenerated
	 */
	public String getPicture3() {
		return picture3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.picture3
	 * @param picture3  the value for cms_video.picture3
	 * @mbggenerated
	 */
	public void setPicture3(String picture3) {
		this.picture3 = picture3 == null ? null : picture3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.picture4
	 * @return  the value of cms_video.picture4
	 * @mbggenerated
	 */
	public String getPicture4() {
		return picture4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.picture4
	 * @param picture4  the value for cms_video.picture4
	 * @mbggenerated
	 */
	public void setPicture4(String picture4) {
		this.picture4 = picture4 == null ? null : picture4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.today_free
	 * @return  the value of cms_video.today_free
	 * @mbggenerated
	 */
	public Date getTodayFree() {
		return todayFree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.today_free
	 * @param todayFree  the value for cms_video.today_free
	 * @mbggenerated
	 */
	public void setTodayFree(Date todayFree) {
		this.todayFree = todayFree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.smooth_url
	 * @return  the value of cms_video.smooth_url
	 * @mbggenerated
	 */
	public String getSmoothUrl() {
		return smoothUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.smooth_url
	 * @param smoothUrl  the value for cms_video.smooth_url
	 * @mbggenerated
	 */
	public void setSmoothUrl(String smoothUrl) {
		this.smoothUrl = smoothUrl == null ? null : smoothUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.sd_url
	 * @return  the value of cms_video.sd_url
	 * @mbggenerated
	 */
	public String getSdUrl() {
		return sdUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.sd_url
	 * @param sdUrl  the value for cms_video.sd_url
	 * @mbggenerated
	 */
	public void setSdUrl(String sdUrl) {
		this.sdUrl = sdUrl == null ? null : sdUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.hd_url
	 * @return  the value of cms_video.hd_url
	 * @mbggenerated
	 */
	public String getHdUrl() {
		return hdUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.hd_url
	 * @param hdUrl  the value for cms_video.hd_url
	 * @mbggenerated
	 */
	public void setHdUrl(String hdUrl) {
		this.hdUrl = hdUrl == null ? null : hdUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.ultra_clear_url
	 * @return  the value of cms_video.ultra_clear_url
	 * @mbggenerated
	 */
	public String getUltraClearUrl() {
		return ultraClearUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.ultra_clear_url
	 * @param ultraClearUrl  the value for cms_video.ultra_clear_url
	 * @mbggenerated
	 */
	public void setUltraClearUrl(String ultraClearUrl) {
		this.ultraClearUrl = ultraClearUrl == null ? null : ultraClearUrl
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.score
	 * @return  the value of cms_video.score
	 * @mbggenerated
	 */
	public Double getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.score
	 * @param score  the value for cms_video.score
	 * @mbggenerated
	 */
	public void setScore(Double score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.release_year
	 * @return  the value of cms_video.release_year
	 * @mbggenerated
	 */
	public Integer getReleaseYear() {
		return releaseYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.release_year
	 * @param releaseYear  the value for cms_video.release_year
	 * @mbggenerated
	 */
	public void setReleaseYear(Integer releaseYear) {
		this.releaseYear = releaseYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.release_time
	 * @return  the value of cms_video.release_time
	 * @mbggenerated
	 */
	public Date getReleaseTime() {
		return releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.release_time
	 * @param releaseTime  the value for cms_video.release_time
	 * @mbggenerated
	 */
	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.program_source
	 * @return  the value of cms_video.program_source
	 * @mbggenerated
	 */
	public String getProgramSource() {
		return programSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.program_source
	 * @param programSource  the value for cms_video.program_source
	 * @mbggenerated
	 */
	public void setProgramSource(String programSource) {
		this.programSource = programSource == null ? null : programSource
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.copyright_source
	 * @return  the value of cms_video.copyright_source
	 * @mbggenerated
	 */
	public String getCopyrightSource() {
		return copyrightSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.copyright_source
	 * @param copyrightSource  the value for cms_video.copyright_source
	 * @mbggenerated
	 */
	public void setCopyrightSource(String copyrightSource) {
		this.copyrightSource = copyrightSource == null ? null : copyrightSource
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.copyright_begindate
	 * @return  the value of cms_video.copyright_begindate
	 * @mbggenerated
	 */
	public Date getCopyrightBegindate() {
		return copyrightBegindate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.copyright_begindate
	 * @param copyrightBegindate  the value for cms_video.copyright_begindate
	 * @mbggenerated
	 */
	public void setCopyrightBegindate(Date copyrightBegindate) {
		this.copyrightBegindate = copyrightBegindate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_video.copyright_enddate
	 * @return  the value of cms_video.copyright_enddate
	 * @mbggenerated
	 */
	public Date getCopyrightEnddate() {
		return copyrightEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_video.copyright_enddate
	 * @param copyrightEnddate  the value for cms_video.copyright_enddate
	 * @mbggenerated
	 */
	public void setCopyrightEnddate(Date copyrightEnddate) {
		this.copyrightEnddate = copyrightEnddate;
	}
}