package com.cnLive.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CmsVideoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cms_video
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cms_video
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cms_video
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public CmsVideoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cms_video
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andContentidIsNull() {
			addCriterion("contentid is null");
			return (Criteria) this;
		}

		public Criteria andContentidIsNotNull() {
			addCriterion("contentid is not null");
			return (Criteria) this;
		}

		public Criteria andContentidEqualTo(String value) {
			addCriterion("contentid =", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidNotEqualTo(String value) {
			addCriterion("contentid <>", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidGreaterThan(String value) {
			addCriterion("contentid >", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidGreaterThanOrEqualTo(String value) {
			addCriterion("contentid >=", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidLessThan(String value) {
			addCriterion("contentid <", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidLessThanOrEqualTo(String value) {
			addCriterion("contentid <=", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidLike(String value) {
			addCriterion("contentid like", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidNotLike(String value) {
			addCriterion("contentid not like", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidIn(List<String> values) {
			addCriterion("contentid in", values, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidNotIn(List<String> values) {
			addCriterion("contentid not in", values, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidBetween(String value1, String value2) {
			addCriterion("contentid between", value1, value2, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidNotBetween(String value1, String value2) {
			addCriterion("contentid not between", value1, value2, "contentid");
			return (Criteria) this;
		}

		public Criteria andVideonameIsNull() {
			addCriterion("videoname is null");
			return (Criteria) this;
		}

		public Criteria andVideonameIsNotNull() {
			addCriterion("videoname is not null");
			return (Criteria) this;
		}

		public Criteria andVideonameEqualTo(String value) {
			addCriterion("videoname =", value, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameNotEqualTo(String value) {
			addCriterion("videoname <>", value, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameGreaterThan(String value) {
			addCriterion("videoname >", value, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameGreaterThanOrEqualTo(String value) {
			addCriterion("videoname >=", value, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameLessThan(String value) {
			addCriterion("videoname <", value, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameLessThanOrEqualTo(String value) {
			addCriterion("videoname <=", value, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameLike(String value) {
			addCriterion("videoname like", value, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameNotLike(String value) {
			addCriterion("videoname not like", value, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameIn(List<String> values) {
			addCriterion("videoname in", values, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameNotIn(List<String> values) {
			addCriterion("videoname not in", values, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameBetween(String value1, String value2) {
			addCriterion("videoname between", value1, value2, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideonameNotBetween(String value1, String value2) {
			addCriterion("videoname not between", value1, value2, "videoname");
			return (Criteria) this;
		}

		public Criteria andVideourlIsNull() {
			addCriterion("videourl is null");
			return (Criteria) this;
		}

		public Criteria andVideourlIsNotNull() {
			addCriterion("videourl is not null");
			return (Criteria) this;
		}

		public Criteria andVideourlEqualTo(String value) {
			addCriterion("videourl =", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlNotEqualTo(String value) {
			addCriterion("videourl <>", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlGreaterThan(String value) {
			addCriterion("videourl >", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlGreaterThanOrEqualTo(String value) {
			addCriterion("videourl >=", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlLessThan(String value) {
			addCriterion("videourl <", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlLessThanOrEqualTo(String value) {
			addCriterion("videourl <=", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlLike(String value) {
			addCriterion("videourl like", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlNotLike(String value) {
			addCriterion("videourl not like", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlIn(List<String> values) {
			addCriterion("videourl in", values, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlNotIn(List<String> values) {
			addCriterion("videourl not in", values, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlBetween(String value1, String value2) {
			addCriterion("videourl between", value1, value2, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlNotBetween(String value1, String value2) {
			addCriterion("videourl not between", value1, value2, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyIsNull() {
			addCriterion("videoclassify is null");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyIsNotNull() {
			addCriterion("videoclassify is not null");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyEqualTo(String value) {
			addCriterion("videoclassify =", value, "videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyNotEqualTo(String value) {
			addCriterion("videoclassify <>", value, "videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyGreaterThan(String value) {
			addCriterion("videoclassify >", value, "videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyGreaterThanOrEqualTo(String value) {
			addCriterion("videoclassify >=", value, "videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyLessThan(String value) {
			addCriterion("videoclassify <", value, "videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyLessThanOrEqualTo(String value) {
			addCriterion("videoclassify <=", value, "videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyLike(String value) {
			addCriterion("videoclassify like", value, "videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyNotLike(String value) {
			addCriterion("videoclassify not like", value, "videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyIn(List<String> values) {
			addCriterion("videoclassify in", values, "videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyNotIn(List<String> values) {
			addCriterion("videoclassify not in", values, "videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyBetween(String value1, String value2) {
			addCriterion("videoclassify between", value1, value2,
					"videoclassify");
			return (Criteria) this;
		}

		public Criteria andVideoclassifyNotBetween(String value1, String value2) {
			addCriterion("videoclassify not between", value1, value2,
					"videoclassify");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(String value) {
			addCriterion("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(String value) {
			addCriterion("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(String value) {
			addCriterion("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(String value) {
			addCriterion("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(String value) {
			addCriterion("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(String value) {
			addCriterion("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLike(String value) {
			addCriterion("time like", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotLike(String value) {
			addCriterion("time not like", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<String> values) {
			addCriterion("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<String> values) {
			addCriterion("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(String value1, String value2) {
			addCriterion("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(String value1, String value2) {
			addCriterion("time not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andSpecialIsNull() {
			addCriterion("special is null");
			return (Criteria) this;
		}

		public Criteria andSpecialIsNotNull() {
			addCriterion("special is not null");
			return (Criteria) this;
		}

		public Criteria andSpecialEqualTo(String value) {
			addCriterion("special =", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialNotEqualTo(String value) {
			addCriterion("special <>", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialGreaterThan(String value) {
			addCriterion("special >", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialGreaterThanOrEqualTo(String value) {
			addCriterion("special >=", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialLessThan(String value) {
			addCriterion("special <", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialLessThanOrEqualTo(String value) {
			addCriterion("special <=", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialLike(String value) {
			addCriterion("special like", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialNotLike(String value) {
			addCriterion("special not like", value, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialIn(List<String> values) {
			addCriterion("special in", values, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialNotIn(List<String> values) {
			addCriterion("special not in", values, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialBetween(String value1, String value2) {
			addCriterion("special between", value1, value2, "special");
			return (Criteria) this;
		}

		public Criteria andSpecialNotBetween(String value1, String value2) {
			addCriterion("special not between", value1, value2, "special");
			return (Criteria) this;
		}

		public Criteria andVideoremarkIsNull() {
			addCriterion("videoremark is null");
			return (Criteria) this;
		}

		public Criteria andVideoremarkIsNotNull() {
			addCriterion("videoremark is not null");
			return (Criteria) this;
		}

		public Criteria andVideoremarkEqualTo(String value) {
			addCriterion("videoremark =", value, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkNotEqualTo(String value) {
			addCriterion("videoremark <>", value, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkGreaterThan(String value) {
			addCriterion("videoremark >", value, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkGreaterThanOrEqualTo(String value) {
			addCriterion("videoremark >=", value, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkLessThan(String value) {
			addCriterion("videoremark <", value, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkLessThanOrEqualTo(String value) {
			addCriterion("videoremark <=", value, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkLike(String value) {
			addCriterion("videoremark like", value, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkNotLike(String value) {
			addCriterion("videoremark not like", value, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkIn(List<String> values) {
			addCriterion("videoremark in", values, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkNotIn(List<String> values) {
			addCriterion("videoremark not in", values, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkBetween(String value1, String value2) {
			addCriterion("videoremark between", value1, value2, "videoremark");
			return (Criteria) this;
		}

		public Criteria andVideoremarkNotBetween(String value1, String value2) {
			addCriterion("videoremark not between", value1, value2,
					"videoremark");
			return (Criteria) this;
		}

		public Criteria andSiteIdIsNull() {
			addCriterion("site_id is null");
			return (Criteria) this;
		}

		public Criteria andSiteIdIsNotNull() {
			addCriterion("site_id is not null");
			return (Criteria) this;
		}

		public Criteria andSiteIdEqualTo(String value) {
			addCriterion("site_id =", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotEqualTo(String value) {
			addCriterion("site_id <>", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdGreaterThan(String value) {
			addCriterion("site_id >", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdGreaterThanOrEqualTo(String value) {
			addCriterion("site_id >=", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdLessThan(String value) {
			addCriterion("site_id <", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdLessThanOrEqualTo(String value) {
			addCriterion("site_id <=", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdLike(String value) {
			addCriterion("site_id like", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotLike(String value) {
			addCriterion("site_id not like", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdIn(List<String> values) {
			addCriterion("site_id in", values, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotIn(List<String> values) {
			addCriterion("site_id not in", values, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdBetween(String value1, String value2) {
			addCriterion("site_id between", value1, value2, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotBetween(String value1, String value2) {
			addCriterion("site_id not between", value1, value2, "siteId");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeIsNull() {
			addCriterion("createdtime is null");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeIsNotNull() {
			addCriterion("createdtime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeEqualTo(Date value) {
			addCriterion("createdtime =", value, "createdtime");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeNotEqualTo(Date value) {
			addCriterion("createdtime <>", value, "createdtime");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeGreaterThan(Date value) {
			addCriterion("createdtime >", value, "createdtime");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("createdtime >=", value, "createdtime");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeLessThan(Date value) {
			addCriterion("createdtime <", value, "createdtime");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeLessThanOrEqualTo(Date value) {
			addCriterion("createdtime <=", value, "createdtime");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeIn(List<Date> values) {
			addCriterion("createdtime in", values, "createdtime");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeNotIn(List<Date> values) {
			addCriterion("createdtime not in", values, "createdtime");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeBetween(Date value1, Date value2) {
			addCriterion("createdtime between", value1, value2, "createdtime");
			return (Criteria) this;
		}

		public Criteria andCreatedtimeNotBetween(Date value1, Date value2) {
			addCriterion("createdtime not between", value1, value2,
					"createdtime");
			return (Criteria) this;
		}

		public Criteria andFilmTypeIsNull() {
			addCriterion("film_type is null");
			return (Criteria) this;
		}

		public Criteria andFilmTypeIsNotNull() {
			addCriterion("film_type is not null");
			return (Criteria) this;
		}

		public Criteria andFilmTypeEqualTo(String value) {
			addCriterion("film_type =", value, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeNotEqualTo(String value) {
			addCriterion("film_type <>", value, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeGreaterThan(String value) {
			addCriterion("film_type >", value, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeGreaterThanOrEqualTo(String value) {
			addCriterion("film_type >=", value, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeLessThan(String value) {
			addCriterion("film_type <", value, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeLessThanOrEqualTo(String value) {
			addCriterion("film_type <=", value, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeLike(String value) {
			addCriterion("film_type like", value, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeNotLike(String value) {
			addCriterion("film_type not like", value, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeIn(List<String> values) {
			addCriterion("film_type in", values, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeNotIn(List<String> values) {
			addCriterion("film_type not in", values, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeBetween(String value1, String value2) {
			addCriterion("film_type between", value1, value2, "filmType");
			return (Criteria) this;
		}

		public Criteria andFilmTypeNotBetween(String value1, String value2) {
			addCriterion("film_type not between", value1, value2, "filmType");
			return (Criteria) this;
		}

		public Criteria andMediaColumnIsNull() {
			addCriterion("media_column is null");
			return (Criteria) this;
		}

		public Criteria andMediaColumnIsNotNull() {
			addCriterion("media_column is not null");
			return (Criteria) this;
		}

		public Criteria andMediaColumnEqualTo(String value) {
			addCriterion("media_column =", value, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnNotEqualTo(String value) {
			addCriterion("media_column <>", value, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnGreaterThan(String value) {
			addCriterion("media_column >", value, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnGreaterThanOrEqualTo(String value) {
			addCriterion("media_column >=", value, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnLessThan(String value) {
			addCriterion("media_column <", value, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnLessThanOrEqualTo(String value) {
			addCriterion("media_column <=", value, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnLike(String value) {
			addCriterion("media_column like", value, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnNotLike(String value) {
			addCriterion("media_column not like", value, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnIn(List<String> values) {
			addCriterion("media_column in", values, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnNotIn(List<String> values) {
			addCriterion("media_column not in", values, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnBetween(String value1, String value2) {
			addCriterion("media_column between", value1, value2, "mediaColumn");
			return (Criteria) this;
		}

		public Criteria andMediaColumnNotBetween(String value1, String value2) {
			addCriterion("media_column not between", value1, value2,
					"mediaColumn");
			return (Criteria) this;
		}

		public Criteria andFilmLevelIsNull() {
			addCriterion("film_level is null");
			return (Criteria) this;
		}

		public Criteria andFilmLevelIsNotNull() {
			addCriterion("film_level is not null");
			return (Criteria) this;
		}

		public Criteria andFilmLevelEqualTo(String value) {
			addCriterion("film_level =", value, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelNotEqualTo(String value) {
			addCriterion("film_level <>", value, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelGreaterThan(String value) {
			addCriterion("film_level >", value, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelGreaterThanOrEqualTo(String value) {
			addCriterion("film_level >=", value, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelLessThan(String value) {
			addCriterion("film_level <", value, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelLessThanOrEqualTo(String value) {
			addCriterion("film_level <=", value, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelLike(String value) {
			addCriterion("film_level like", value, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelNotLike(String value) {
			addCriterion("film_level not like", value, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelIn(List<String> values) {
			addCriterion("film_level in", values, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelNotIn(List<String> values) {
			addCriterion("film_level not in", values, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelBetween(String value1, String value2) {
			addCriterion("film_level between", value1, value2, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andFilmLevelNotBetween(String value1, String value2) {
			addCriterion("film_level not between", value1, value2, "filmLevel");
			return (Criteria) this;
		}

		public Criteria andIsPositiveIsNull() {
			addCriterion("is_positive is null");
			return (Criteria) this;
		}

		public Criteria andIsPositiveIsNotNull() {
			addCriterion("is_positive is not null");
			return (Criteria) this;
		}

		public Criteria andIsPositiveEqualTo(String value) {
			addCriterion("is_positive =", value, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveNotEqualTo(String value) {
			addCriterion("is_positive <>", value, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveGreaterThan(String value) {
			addCriterion("is_positive >", value, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveGreaterThanOrEqualTo(String value) {
			addCriterion("is_positive >=", value, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveLessThan(String value) {
			addCriterion("is_positive <", value, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveLessThanOrEqualTo(String value) {
			addCriterion("is_positive <=", value, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveLike(String value) {
			addCriterion("is_positive like", value, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveNotLike(String value) {
			addCriterion("is_positive not like", value, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveIn(List<String> values) {
			addCriterion("is_positive in", values, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveNotIn(List<String> values) {
			addCriterion("is_positive not in", values, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveBetween(String value1, String value2) {
			addCriterion("is_positive between", value1, value2, "isPositive");
			return (Criteria) this;
		}

		public Criteria andIsPositiveNotBetween(String value1, String value2) {
			addCriterion("is_positive not between", value1, value2,
					"isPositive");
			return (Criteria) this;
		}

		public Criteria andDirectorIsNull() {
			addCriterion("director is null");
			return (Criteria) this;
		}

		public Criteria andDirectorIsNotNull() {
			addCriterion("director is not null");
			return (Criteria) this;
		}

		public Criteria andDirectorEqualTo(String value) {
			addCriterion("director =", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotEqualTo(String value) {
			addCriterion("director <>", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorGreaterThan(String value) {
			addCriterion("director >", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorGreaterThanOrEqualTo(String value) {
			addCriterion("director >=", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorLessThan(String value) {
			addCriterion("director <", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorLessThanOrEqualTo(String value) {
			addCriterion("director <=", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorLike(String value) {
			addCriterion("director like", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotLike(String value) {
			addCriterion("director not like", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorIn(List<String> values) {
			addCriterion("director in", values, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotIn(List<String> values) {
			addCriterion("director not in", values, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorBetween(String value1, String value2) {
			addCriterion("director between", value1, value2, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotBetween(String value1, String value2) {
			addCriterion("director not between", value1, value2, "director");
			return (Criteria) this;
		}

		public Criteria andToStarIsNull() {
			addCriterion("to_star is null");
			return (Criteria) this;
		}

		public Criteria andToStarIsNotNull() {
			addCriterion("to_star is not null");
			return (Criteria) this;
		}

		public Criteria andToStarEqualTo(String value) {
			addCriterion("to_star =", value, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarNotEqualTo(String value) {
			addCriterion("to_star <>", value, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarGreaterThan(String value) {
			addCriterion("to_star >", value, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarGreaterThanOrEqualTo(String value) {
			addCriterion("to_star >=", value, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarLessThan(String value) {
			addCriterion("to_star <", value, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarLessThanOrEqualTo(String value) {
			addCriterion("to_star <=", value, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarLike(String value) {
			addCriterion("to_star like", value, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarNotLike(String value) {
			addCriterion("to_star not like", value, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarIn(List<String> values) {
			addCriterion("to_star in", values, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarNotIn(List<String> values) {
			addCriterion("to_star not in", values, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarBetween(String value1, String value2) {
			addCriterion("to_star between", value1, value2, "toStar");
			return (Criteria) this;
		}

		public Criteria andToStarNotBetween(String value1, String value2) {
			addCriterion("to_star not between", value1, value2, "toStar");
			return (Criteria) this;
		}

		public Criteria andCommodityIdIsNull() {
			addCriterion("commodity_id is null");
			return (Criteria) this;
		}

		public Criteria andCommodityIdIsNotNull() {
			addCriterion("commodity_id is not null");
			return (Criteria) this;
		}

		public Criteria andCommodityIdEqualTo(String value) {
			addCriterion("commodity_id =", value, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdNotEqualTo(String value) {
			addCriterion("commodity_id <>", value, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdGreaterThan(String value) {
			addCriterion("commodity_id >", value, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdGreaterThanOrEqualTo(String value) {
			addCriterion("commodity_id >=", value, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdLessThan(String value) {
			addCriterion("commodity_id <", value, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdLessThanOrEqualTo(String value) {
			addCriterion("commodity_id <=", value, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdLike(String value) {
			addCriterion("commodity_id like", value, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdNotLike(String value) {
			addCriterion("commodity_id not like", value, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdIn(List<String> values) {
			addCriterion("commodity_id in", values, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdNotIn(List<String> values) {
			addCriterion("commodity_id not in", values, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdBetween(String value1, String value2) {
			addCriterion("commodity_id between", value1, value2, "commodityId");
			return (Criteria) this;
		}

		public Criteria andCommodityIdNotBetween(String value1, String value2) {
			addCriterion("commodity_id not between", value1, value2,
					"commodityId");
			return (Criteria) this;
		}

		public Criteria andFreeTimeIsNull() {
			addCriterion("free_time is null");
			return (Criteria) this;
		}

		public Criteria andFreeTimeIsNotNull() {
			addCriterion("free_time is not null");
			return (Criteria) this;
		}

		public Criteria andFreeTimeEqualTo(String value) {
			addCriterion("free_time =", value, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeNotEqualTo(String value) {
			addCriterion("free_time <>", value, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeGreaterThan(String value) {
			addCriterion("free_time >", value, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeGreaterThanOrEqualTo(String value) {
			addCriterion("free_time >=", value, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeLessThan(String value) {
			addCriterion("free_time <", value, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeLessThanOrEqualTo(String value) {
			addCriterion("free_time <=", value, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeLike(String value) {
			addCriterion("free_time like", value, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeNotLike(String value) {
			addCriterion("free_time not like", value, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeIn(List<String> values) {
			addCriterion("free_time in", values, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeNotIn(List<String> values) {
			addCriterion("free_time not in", values, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeBetween(String value1, String value2) {
			addCriterion("free_time between", value1, value2, "freeTime");
			return (Criteria) this;
		}

		public Criteria andFreeTimeNotBetween(String value1, String value2) {
			addCriterion("free_time not between", value1, value2, "freeTime");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesIsNull() {
			addCriterion("related_content_types is null");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesIsNotNull() {
			addCriterion("related_content_types is not null");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesEqualTo(String value) {
			addCriterion("related_content_types =", value,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesNotEqualTo(String value) {
			addCriterion("related_content_types <>", value,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesGreaterThan(String value) {
			addCriterion("related_content_types >", value,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesGreaterThanOrEqualTo(String value) {
			addCriterion("related_content_types >=", value,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesLessThan(String value) {
			addCriterion("related_content_types <", value,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesLessThanOrEqualTo(String value) {
			addCriterion("related_content_types <=", value,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesLike(String value) {
			addCriterion("related_content_types like", value,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesNotLike(String value) {
			addCriterion("related_content_types not like", value,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesIn(List<String> values) {
			addCriterion("related_content_types in", values,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesNotIn(List<String> values) {
			addCriterion("related_content_types not in", values,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesBetween(String value1,
				String value2) {
			addCriterion("related_content_types between", value1, value2,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andRelatedContentTypesNotBetween(String value1,
				String value2) {
			addCriterion("related_content_types not between", value1, value2,
					"relatedContentTypes");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsIsNull() {
			addCriterion("countries_and_regions is null");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsIsNotNull() {
			addCriterion("countries_and_regions is not null");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsEqualTo(String value) {
			addCriterion("countries_and_regions =", value,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsNotEqualTo(String value) {
			addCriterion("countries_and_regions <>", value,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsGreaterThan(String value) {
			addCriterion("countries_and_regions >", value,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsGreaterThanOrEqualTo(String value) {
			addCriterion("countries_and_regions >=", value,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsLessThan(String value) {
			addCriterion("countries_and_regions <", value,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsLessThanOrEqualTo(String value) {
			addCriterion("countries_and_regions <=", value,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsLike(String value) {
			addCriterion("countries_and_regions like", value,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsNotLike(String value) {
			addCriterion("countries_and_regions not like", value,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsIn(List<String> values) {
			addCriterion("countries_and_regions in", values,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsNotIn(List<String> values) {
			addCriterion("countries_and_regions not in", values,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsBetween(String value1,
				String value2) {
			addCriterion("countries_and_regions between", value1, value2,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andCountriesAndRegionsNotBetween(String value1,
				String value2) {
			addCriterion("countries_and_regions not between", value1, value2,
					"countriesAndRegions");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNull() {
			addCriterion("keyword is null");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNotNull() {
			addCriterion("keyword is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordEqualTo(String value) {
			addCriterion("keyword =", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotEqualTo(String value) {
			addCriterion("keyword <>", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThan(String value) {
			addCriterion("keyword >", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThanOrEqualTo(String value) {
			addCriterion("keyword >=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThan(String value) {
			addCriterion("keyword <", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThanOrEqualTo(String value) {
			addCriterion("keyword <=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLike(String value) {
			addCriterion("keyword like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotLike(String value) {
			addCriterion("keyword not like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordIn(List<String> values) {
			addCriterion("keyword in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotIn(List<String> values) {
			addCriterion("keyword not in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordBetween(String value1, String value2) {
			addCriterion("keyword between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotBetween(String value1, String value2) {
			addCriterion("keyword not between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andContentTypeIsNull() {
			addCriterion("content_type is null");
			return (Criteria) this;
		}

		public Criteria andContentTypeIsNotNull() {
			addCriterion("content_type is not null");
			return (Criteria) this;
		}

		public Criteria andContentTypeEqualTo(String value) {
			addCriterion("content_type =", value, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeNotEqualTo(String value) {
			addCriterion("content_type <>", value, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeGreaterThan(String value) {
			addCriterion("content_type >", value, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeGreaterThanOrEqualTo(String value) {
			addCriterion("content_type >=", value, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeLessThan(String value) {
			addCriterion("content_type <", value, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeLessThanOrEqualTo(String value) {
			addCriterion("content_type <=", value, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeLike(String value) {
			addCriterion("content_type like", value, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeNotLike(String value) {
			addCriterion("content_type not like", value, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeIn(List<String> values) {
			addCriterion("content_type in", values, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeNotIn(List<String> values) {
			addCriterion("content_type not in", values, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeBetween(String value1, String value2) {
			addCriterion("content_type between", value1, value2, "contentType");
			return (Criteria) this;
		}

		public Criteria andContentTypeNotBetween(String value1, String value2) {
			addCriterion("content_type not between", value1, value2,
					"contentType");
			return (Criteria) this;
		}

		public Criteria andDownUrlIsNull() {
			addCriterion("down_url is null");
			return (Criteria) this;
		}

		public Criteria andDownUrlIsNotNull() {
			addCriterion("down_url is not null");
			return (Criteria) this;
		}

		public Criteria andDownUrlEqualTo(String value) {
			addCriterion("down_url =", value, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlNotEqualTo(String value) {
			addCriterion("down_url <>", value, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlGreaterThan(String value) {
			addCriterion("down_url >", value, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlGreaterThanOrEqualTo(String value) {
			addCriterion("down_url >=", value, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlLessThan(String value) {
			addCriterion("down_url <", value, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlLessThanOrEqualTo(String value) {
			addCriterion("down_url <=", value, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlLike(String value) {
			addCriterion("down_url like", value, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlNotLike(String value) {
			addCriterion("down_url not like", value, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlIn(List<String> values) {
			addCriterion("down_url in", values, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlNotIn(List<String> values) {
			addCriterion("down_url not in", values, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlBetween(String value1, String value2) {
			addCriterion("down_url between", value1, value2, "downUrl");
			return (Criteria) this;
		}

		public Criteria andDownUrlNotBetween(String value1, String value2) {
			addCriterion("down_url not between", value1, value2, "downUrl");
			return (Criteria) this;
		}

		public Criteria andCopyrightIsNull() {
			addCriterion("copyright is null");
			return (Criteria) this;
		}

		public Criteria andCopyrightIsNotNull() {
			addCriterion("copyright is not null");
			return (Criteria) this;
		}

		public Criteria andCopyrightEqualTo(String value) {
			addCriterion("copyright =", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightNotEqualTo(String value) {
			addCriterion("copyright <>", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightGreaterThan(String value) {
			addCriterion("copyright >", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightGreaterThanOrEqualTo(String value) {
			addCriterion("copyright >=", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightLessThan(String value) {
			addCriterion("copyright <", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightLessThanOrEqualTo(String value) {
			addCriterion("copyright <=", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightLike(String value) {
			addCriterion("copyright like", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightNotLike(String value) {
			addCriterion("copyright not like", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightIn(List<String> values) {
			addCriterion("copyright in", values, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightNotIn(List<String> values) {
			addCriterion("copyright not in", values, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightBetween(String value1, String value2) {
			addCriterion("copyright between", value1, value2, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightNotBetween(String value1, String value2) {
			addCriterion("copyright not between", value1, value2, "copyright");
			return (Criteria) this;
		}

		public Criteria andPicture1IsNull() {
			addCriterion("picture1 is null");
			return (Criteria) this;
		}

		public Criteria andPicture1IsNotNull() {
			addCriterion("picture1 is not null");
			return (Criteria) this;
		}

		public Criteria andPicture1EqualTo(String value) {
			addCriterion("picture1 =", value, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1NotEqualTo(String value) {
			addCriterion("picture1 <>", value, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1GreaterThan(String value) {
			addCriterion("picture1 >", value, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1GreaterThanOrEqualTo(String value) {
			addCriterion("picture1 >=", value, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1LessThan(String value) {
			addCriterion("picture1 <", value, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1LessThanOrEqualTo(String value) {
			addCriterion("picture1 <=", value, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1Like(String value) {
			addCriterion("picture1 like", value, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1NotLike(String value) {
			addCriterion("picture1 not like", value, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1In(List<String> values) {
			addCriterion("picture1 in", values, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1NotIn(List<String> values) {
			addCriterion("picture1 not in", values, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1Between(String value1, String value2) {
			addCriterion("picture1 between", value1, value2, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture1NotBetween(String value1, String value2) {
			addCriterion("picture1 not between", value1, value2, "picture1");
			return (Criteria) this;
		}

		public Criteria andPicture2IsNull() {
			addCriterion("picture2 is null");
			return (Criteria) this;
		}

		public Criteria andPicture2IsNotNull() {
			addCriterion("picture2 is not null");
			return (Criteria) this;
		}

		public Criteria andPicture2EqualTo(String value) {
			addCriterion("picture2 =", value, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2NotEqualTo(String value) {
			addCriterion("picture2 <>", value, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2GreaterThan(String value) {
			addCriterion("picture2 >", value, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2GreaterThanOrEqualTo(String value) {
			addCriterion("picture2 >=", value, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2LessThan(String value) {
			addCriterion("picture2 <", value, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2LessThanOrEqualTo(String value) {
			addCriterion("picture2 <=", value, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2Like(String value) {
			addCriterion("picture2 like", value, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2NotLike(String value) {
			addCriterion("picture2 not like", value, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2In(List<String> values) {
			addCriterion("picture2 in", values, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2NotIn(List<String> values) {
			addCriterion("picture2 not in", values, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2Between(String value1, String value2) {
			addCriterion("picture2 between", value1, value2, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture2NotBetween(String value1, String value2) {
			addCriterion("picture2 not between", value1, value2, "picture2");
			return (Criteria) this;
		}

		public Criteria andPicture3IsNull() {
			addCriterion("picture3 is null");
			return (Criteria) this;
		}

		public Criteria andPicture3IsNotNull() {
			addCriterion("picture3 is not null");
			return (Criteria) this;
		}

		public Criteria andPicture3EqualTo(String value) {
			addCriterion("picture3 =", value, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3NotEqualTo(String value) {
			addCriterion("picture3 <>", value, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3GreaterThan(String value) {
			addCriterion("picture3 >", value, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3GreaterThanOrEqualTo(String value) {
			addCriterion("picture3 >=", value, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3LessThan(String value) {
			addCriterion("picture3 <", value, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3LessThanOrEqualTo(String value) {
			addCriterion("picture3 <=", value, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3Like(String value) {
			addCriterion("picture3 like", value, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3NotLike(String value) {
			addCriterion("picture3 not like", value, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3In(List<String> values) {
			addCriterion("picture3 in", values, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3NotIn(List<String> values) {
			addCriterion("picture3 not in", values, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3Between(String value1, String value2) {
			addCriterion("picture3 between", value1, value2, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture3NotBetween(String value1, String value2) {
			addCriterion("picture3 not between", value1, value2, "picture3");
			return (Criteria) this;
		}

		public Criteria andPicture4IsNull() {
			addCriterion("picture4 is null");
			return (Criteria) this;
		}

		public Criteria andPicture4IsNotNull() {
			addCriterion("picture4 is not null");
			return (Criteria) this;
		}

		public Criteria andPicture4EqualTo(String value) {
			addCriterion("picture4 =", value, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4NotEqualTo(String value) {
			addCriterion("picture4 <>", value, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4GreaterThan(String value) {
			addCriterion("picture4 >", value, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4GreaterThanOrEqualTo(String value) {
			addCriterion("picture4 >=", value, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4LessThan(String value) {
			addCriterion("picture4 <", value, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4LessThanOrEqualTo(String value) {
			addCriterion("picture4 <=", value, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4Like(String value) {
			addCriterion("picture4 like", value, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4NotLike(String value) {
			addCriterion("picture4 not like", value, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4In(List<String> values) {
			addCriterion("picture4 in", values, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4NotIn(List<String> values) {
			addCriterion("picture4 not in", values, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4Between(String value1, String value2) {
			addCriterion("picture4 between", value1, value2, "picture4");
			return (Criteria) this;
		}

		public Criteria andPicture4NotBetween(String value1, String value2) {
			addCriterion("picture4 not between", value1, value2, "picture4");
			return (Criteria) this;
		}

		public Criteria andTodayFreeIsNull() {
			addCriterion("today_free is null");
			return (Criteria) this;
		}

		public Criteria andTodayFreeIsNotNull() {
			addCriterion("today_free is not null");
			return (Criteria) this;
		}

		public Criteria andTodayFreeEqualTo(Date value) {
			addCriterionForJDBCDate("today_free =", value, "todayFree");
			return (Criteria) this;
		}

		public Criteria andTodayFreeNotEqualTo(Date value) {
			addCriterionForJDBCDate("today_free <>", value, "todayFree");
			return (Criteria) this;
		}

		public Criteria andTodayFreeGreaterThan(Date value) {
			addCriterionForJDBCDate("today_free >", value, "todayFree");
			return (Criteria) this;
		}

		public Criteria andTodayFreeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("today_free >=", value, "todayFree");
			return (Criteria) this;
		}

		public Criteria andTodayFreeLessThan(Date value) {
			addCriterionForJDBCDate("today_free <", value, "todayFree");
			return (Criteria) this;
		}

		public Criteria andTodayFreeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("today_free <=", value, "todayFree");
			return (Criteria) this;
		}

		public Criteria andTodayFreeIn(List<Date> values) {
			addCriterionForJDBCDate("today_free in", values, "todayFree");
			return (Criteria) this;
		}

		public Criteria andTodayFreeNotIn(List<Date> values) {
			addCriterionForJDBCDate("today_free not in", values, "todayFree");
			return (Criteria) this;
		}

		public Criteria andTodayFreeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("today_free between", value1, value2,
					"todayFree");
			return (Criteria) this;
		}

		public Criteria andTodayFreeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("today_free not between", value1, value2,
					"todayFree");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlIsNull() {
			addCriterion("smooth_url is null");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlIsNotNull() {
			addCriterion("smooth_url is not null");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlEqualTo(String value) {
			addCriterion("smooth_url =", value, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlNotEqualTo(String value) {
			addCriterion("smooth_url <>", value, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlGreaterThan(String value) {
			addCriterion("smooth_url >", value, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlGreaterThanOrEqualTo(String value) {
			addCriterion("smooth_url >=", value, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlLessThan(String value) {
			addCriterion("smooth_url <", value, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlLessThanOrEqualTo(String value) {
			addCriterion("smooth_url <=", value, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlLike(String value) {
			addCriterion("smooth_url like", value, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlNotLike(String value) {
			addCriterion("smooth_url not like", value, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlIn(List<String> values) {
			addCriterion("smooth_url in", values, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlNotIn(List<String> values) {
			addCriterion("smooth_url not in", values, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlBetween(String value1, String value2) {
			addCriterion("smooth_url between", value1, value2, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSmoothUrlNotBetween(String value1, String value2) {
			addCriterion("smooth_url not between", value1, value2, "smoothUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlIsNull() {
			addCriterion("sd_url is null");
			return (Criteria) this;
		}

		public Criteria andSdUrlIsNotNull() {
			addCriterion("sd_url is not null");
			return (Criteria) this;
		}

		public Criteria andSdUrlEqualTo(String value) {
			addCriterion("sd_url =", value, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlNotEqualTo(String value) {
			addCriterion("sd_url <>", value, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlGreaterThan(String value) {
			addCriterion("sd_url >", value, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlGreaterThanOrEqualTo(String value) {
			addCriterion("sd_url >=", value, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlLessThan(String value) {
			addCriterion("sd_url <", value, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlLessThanOrEqualTo(String value) {
			addCriterion("sd_url <=", value, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlLike(String value) {
			addCriterion("sd_url like", value, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlNotLike(String value) {
			addCriterion("sd_url not like", value, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlIn(List<String> values) {
			addCriterion("sd_url in", values, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlNotIn(List<String> values) {
			addCriterion("sd_url not in", values, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlBetween(String value1, String value2) {
			addCriterion("sd_url between", value1, value2, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andSdUrlNotBetween(String value1, String value2) {
			addCriterion("sd_url not between", value1, value2, "sdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlIsNull() {
			addCriterion("hd_url is null");
			return (Criteria) this;
		}

		public Criteria andHdUrlIsNotNull() {
			addCriterion("hd_url is not null");
			return (Criteria) this;
		}

		public Criteria andHdUrlEqualTo(String value) {
			addCriterion("hd_url =", value, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlNotEqualTo(String value) {
			addCriterion("hd_url <>", value, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlGreaterThan(String value) {
			addCriterion("hd_url >", value, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlGreaterThanOrEqualTo(String value) {
			addCriterion("hd_url >=", value, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlLessThan(String value) {
			addCriterion("hd_url <", value, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlLessThanOrEqualTo(String value) {
			addCriterion("hd_url <=", value, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlLike(String value) {
			addCriterion("hd_url like", value, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlNotLike(String value) {
			addCriterion("hd_url not like", value, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlIn(List<String> values) {
			addCriterion("hd_url in", values, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlNotIn(List<String> values) {
			addCriterion("hd_url not in", values, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlBetween(String value1, String value2) {
			addCriterion("hd_url between", value1, value2, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andHdUrlNotBetween(String value1, String value2) {
			addCriterion("hd_url not between", value1, value2, "hdUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlIsNull() {
			addCriterion("ultra_clear_url is null");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlIsNotNull() {
			addCriterion("ultra_clear_url is not null");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlEqualTo(String value) {
			addCriterion("ultra_clear_url =", value, "ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlNotEqualTo(String value) {
			addCriterion("ultra_clear_url <>", value, "ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlGreaterThan(String value) {
			addCriterion("ultra_clear_url >", value, "ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlGreaterThanOrEqualTo(String value) {
			addCriterion("ultra_clear_url >=", value, "ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlLessThan(String value) {
			addCriterion("ultra_clear_url <", value, "ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlLessThanOrEqualTo(String value) {
			addCriterion("ultra_clear_url <=", value, "ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlLike(String value) {
			addCriterion("ultra_clear_url like", value, "ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlNotLike(String value) {
			addCriterion("ultra_clear_url not like", value, "ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlIn(List<String> values) {
			addCriterion("ultra_clear_url in", values, "ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlNotIn(List<String> values) {
			addCriterion("ultra_clear_url not in", values, "ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlBetween(String value1, String value2) {
			addCriterion("ultra_clear_url between", value1, value2,
					"ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andUltraClearUrlNotBetween(String value1, String value2) {
			addCriterion("ultra_clear_url not between", value1, value2,
					"ultraClearUrl");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(Double value) {
			addCriterion("score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(Double value) {
			addCriterion("score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(Double value) {
			addCriterion("score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(Double value) {
			addCriterion("score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(Double value) {
			addCriterion("score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(Double value) {
			addCriterion("score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<Double> values) {
			addCriterion("score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<Double> values) {
			addCriterion("score not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(Double value1, Double value2) {
			addCriterion("score between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(Double value1, Double value2) {
			addCriterion("score not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andReleaseYearIsNull() {
			addCriterion("release_year is null");
			return (Criteria) this;
		}

		public Criteria andReleaseYearIsNotNull() {
			addCriterion("release_year is not null");
			return (Criteria) this;
		}

		public Criteria andReleaseYearEqualTo(Integer value) {
			addCriterion("release_year =", value, "releaseYear");
			return (Criteria) this;
		}

		public Criteria andReleaseYearNotEqualTo(Integer value) {
			addCriterion("release_year <>", value, "releaseYear");
			return (Criteria) this;
		}

		public Criteria andReleaseYearGreaterThan(Integer value) {
			addCriterion("release_year >", value, "releaseYear");
			return (Criteria) this;
		}

		public Criteria andReleaseYearGreaterThanOrEqualTo(Integer value) {
			addCriterion("release_year >=", value, "releaseYear");
			return (Criteria) this;
		}

		public Criteria andReleaseYearLessThan(Integer value) {
			addCriterion("release_year <", value, "releaseYear");
			return (Criteria) this;
		}

		public Criteria andReleaseYearLessThanOrEqualTo(Integer value) {
			addCriterion("release_year <=", value, "releaseYear");
			return (Criteria) this;
		}

		public Criteria andReleaseYearIn(List<Integer> values) {
			addCriterion("release_year in", values, "releaseYear");
			return (Criteria) this;
		}

		public Criteria andReleaseYearNotIn(List<Integer> values) {
			addCriterion("release_year not in", values, "releaseYear");
			return (Criteria) this;
		}

		public Criteria andReleaseYearBetween(Integer value1, Integer value2) {
			addCriterion("release_year between", value1, value2, "releaseYear");
			return (Criteria) this;
		}

		public Criteria andReleaseYearNotBetween(Integer value1, Integer value2) {
			addCriterion("release_year not between", value1, value2,
					"releaseYear");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeIsNull() {
			addCriterion("release_time is null");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeIsNotNull() {
			addCriterion("release_time is not null");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeEqualTo(Date value) {
			addCriterion("release_time =", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeNotEqualTo(Date value) {
			addCriterion("release_time <>", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeGreaterThan(Date value) {
			addCriterion("release_time >", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("release_time >=", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeLessThan(Date value) {
			addCriterion("release_time <", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeLessThanOrEqualTo(Date value) {
			addCriterion("release_time <=", value, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeIn(List<Date> values) {
			addCriterion("release_time in", values, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeNotIn(List<Date> values) {
			addCriterion("release_time not in", values, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeBetween(Date value1, Date value2) {
			addCriterion("release_time between", value1, value2, "releaseTime");
			return (Criteria) this;
		}

		public Criteria andReleaseTimeNotBetween(Date value1, Date value2) {
			addCriterion("release_time not between", value1, value2,
					"releaseTime");
			return (Criteria) this;
		}

		public Criteria andProgramSourceIsNull() {
			addCriterion("program_source is null");
			return (Criteria) this;
		}

		public Criteria andProgramSourceIsNotNull() {
			addCriterion("program_source is not null");
			return (Criteria) this;
		}

		public Criteria andProgramSourceEqualTo(String value) {
			addCriterion("program_source =", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceNotEqualTo(String value) {
			addCriterion("program_source <>", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceGreaterThan(String value) {
			addCriterion("program_source >", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceGreaterThanOrEqualTo(String value) {
			addCriterion("program_source >=", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceLessThan(String value) {
			addCriterion("program_source <", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceLessThanOrEqualTo(String value) {
			addCriterion("program_source <=", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceLike(String value) {
			addCriterion("program_source like", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceNotLike(String value) {
			addCriterion("program_source not like", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceIn(List<String> values) {
			addCriterion("program_source in", values, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceNotIn(List<String> values) {
			addCriterion("program_source not in", values, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceBetween(String value1, String value2) {
			addCriterion("program_source between", value1, value2,
					"programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceNotBetween(String value1, String value2) {
			addCriterion("program_source not between", value1, value2,
					"programSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceIsNull() {
			addCriterion("copyright_source is null");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceIsNotNull() {
			addCriterion("copyright_source is not null");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceEqualTo(String value) {
			addCriterion("copyright_source =", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceNotEqualTo(String value) {
			addCriterion("copyright_source <>", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceGreaterThan(String value) {
			addCriterion("copyright_source >", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceGreaterThanOrEqualTo(String value) {
			addCriterion("copyright_source >=", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceLessThan(String value) {
			addCriterion("copyright_source <", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceLessThanOrEqualTo(String value) {
			addCriterion("copyright_source <=", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceLike(String value) {
			addCriterion("copyright_source like", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceNotLike(String value) {
			addCriterion("copyright_source not like", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceIn(List<String> values) {
			addCriterion("copyright_source in", values, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceNotIn(List<String> values) {
			addCriterion("copyright_source not in", values, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceBetween(String value1, String value2) {
			addCriterion("copyright_source between", value1, value2,
					"copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceNotBetween(String value1,
				String value2) {
			addCriterion("copyright_source not between", value1, value2,
					"copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateIsNull() {
			addCriterion("copyright_begindate is null");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateIsNotNull() {
			addCriterion("copyright_begindate is not null");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateEqualTo(Date value) {
			addCriterion("copyright_begindate =", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateNotEqualTo(Date value) {
			addCriterion("copyright_begindate <>", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateGreaterThan(Date value) {
			addCriterion("copyright_begindate >", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateGreaterThanOrEqualTo(Date value) {
			addCriterion("copyright_begindate >=", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateLessThan(Date value) {
			addCriterion("copyright_begindate <", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateLessThanOrEqualTo(Date value) {
			addCriterion("copyright_begindate <=", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateIn(List<Date> values) {
			addCriterion("copyright_begindate in", values, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateNotIn(List<Date> values) {
			addCriterion("copyright_begindate not in", values,
					"copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateBetween(Date value1, Date value2) {
			addCriterion("copyright_begindate between", value1, value2,
					"copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateNotBetween(Date value1, Date value2) {
			addCriterion("copyright_begindate not between", value1, value2,
					"copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateIsNull() {
			addCriterion("copyright_enddate is null");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateIsNotNull() {
			addCriterion("copyright_enddate is not null");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateEqualTo(Date value) {
			addCriterion("copyright_enddate =", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateNotEqualTo(Date value) {
			addCriterion("copyright_enddate <>", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateGreaterThan(Date value) {
			addCriterion("copyright_enddate >", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateGreaterThanOrEqualTo(Date value) {
			addCriterion("copyright_enddate >=", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateLessThan(Date value) {
			addCriterion("copyright_enddate <", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateLessThanOrEqualTo(Date value) {
			addCriterion("copyright_enddate <=", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateIn(List<Date> values) {
			addCriterion("copyright_enddate in", values, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateNotIn(List<Date> values) {
			addCriterion("copyright_enddate not in", values, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateBetween(Date value1, Date value2) {
			addCriterion("copyright_enddate between", value1, value2,
					"copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateNotBetween(Date value1, Date value2) {
			addCriterion("copyright_enddate not between", value1, value2,
					"copyrightEnddate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cms_video
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cms_video
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}