package com.cnLive.pojo;

import java.util.Date;

public class sys_contentmain {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.CONTENTID
	 * @mbggenerated
	 */
	private Integer contentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.TITLE
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.SUBTITLE
	 * @mbggenerated
	 */
	private String subtitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.STATUS
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.UUID
	 * @mbggenerated
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.MAINCATEGORY
	 * @mbggenerated
	 */
	private String maincategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.categorys
	 * @mbggenerated
	 */
	private String categorys;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.movieLevel
	 * @mbggenerated
	 */
	private Integer movielevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.movieType
	 * @mbggenerated
	 */
	private Integer movietype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.vipFlag
	 * @mbggenerated
	 */
	private Integer vipflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.Airtime
	 * @mbggenerated
	 */
	private String airtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.videoType
	 * @mbggenerated
	 */
	private String videotype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.Tags
	 * @mbggenerated
	 */
	private String tags;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.area
	 * @mbggenerated
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.Actors
	 * @mbggenerated
	 */
	private String actors;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.Director
	 * @mbggenerated
	 */
	private String director;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.EXTFIELD2
	 * @mbggenerated
	 */
	private String extfield2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.CONTENTTYPE
	 * @mbggenerated
	 */
	private String contenttype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.CREATEDATE
	 * @mbggenerated
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.CREATEUSERID
	 * @mbggenerated
	 */
	private Integer createuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.CREATEUSERNAME
	 * @mbggenerated
	 */
	private String createusername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.DELETEFLAG
	 * @mbggenerated
	 */
	private Integer deleteflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.DESCRIPTION
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.DURATION
	 * @mbggenerated
	 */
	private Integer duration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.LASTMODIFIEDDATE
	 * @mbggenerated
	 */
	private Date lastmodifieddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.PUBLISHDATE
	 * @mbggenerated
	 */
	private Date publishdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.TITLEIMAGE
	 * @mbggenerated
	 */
	private String titleimage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.WEIGHT
	 * @mbggenerated
	 */
	private Integer weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.IMGBIG
	 * @mbggenerated
	 */
	private String imgbig;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.IMGSMALL
	 * @mbggenerated
	 */
	private String imgsmall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.IMGOTHER1
	 * @mbggenerated
	 */
	private String imgother1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.IMGOTHER2
	 * @mbggenerated
	 */
	private String imgother2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.VIDEOFLASHLURL
	 * @mbggenerated
	 */
	private String videoflashlurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.VIDEOFLASHURL
	 * @mbggenerated
	 */
	private String videoflashurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.VIDEOFLASHHURL
	 * @mbggenerated
	 */
	private String videoflashhurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.VIDEOFLASHUHURL
	 * @mbggenerated
	 */
	private String videoflashuhurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.VIDEOLURL
	 * @mbggenerated
	 */
	private String videolurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.VIDEOURL
	 * @mbggenerated
	 */
	private String videourl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.VideoHUrl
	 * @mbggenerated
	 */
	private String videohurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_contentmain.VideoUHUrl
	 * @mbggenerated
	 */
	private String videouhurl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.CONTENTID
	 * @return  the value of sys_contentmain.CONTENTID
	 * @mbggenerated
	 */
	public Integer getContentid() {
		return contentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.CONTENTID
	 * @param contentid  the value for sys_contentmain.CONTENTID
	 * @mbggenerated
	 */
	public void setContentid(Integer contentid) {
		this.contentid = contentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.TITLE
	 * @return  the value of sys_contentmain.TITLE
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.TITLE
	 * @param title  the value for sys_contentmain.TITLE
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.SUBTITLE
	 * @return  the value of sys_contentmain.SUBTITLE
	 * @mbggenerated
	 */
	public String getSubtitle() {
		return subtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.SUBTITLE
	 * @param subtitle  the value for sys_contentmain.SUBTITLE
	 * @mbggenerated
	 */
	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle == null ? null : subtitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.STATUS
	 * @return  the value of sys_contentmain.STATUS
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.STATUS
	 * @param status  the value for sys_contentmain.STATUS
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.UUID
	 * @return  the value of sys_contentmain.UUID
	 * @mbggenerated
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.UUID
	 * @param uuid  the value for sys_contentmain.UUID
	 * @mbggenerated
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid == null ? null : uuid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.MAINCATEGORY
	 * @return  the value of sys_contentmain.MAINCATEGORY
	 * @mbggenerated
	 */
	public String getMaincategory() {
		return maincategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.MAINCATEGORY
	 * @param maincategory  the value for sys_contentmain.MAINCATEGORY
	 * @mbggenerated
	 */
	public void setMaincategory(String maincategory) {
		this.maincategory = maincategory == null ? null : maincategory.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.categorys
	 * @return  the value of sys_contentmain.categorys
	 * @mbggenerated
	 */
	public String getCategorys() {
		return categorys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.categorys
	 * @param categorys  the value for sys_contentmain.categorys
	 * @mbggenerated
	 */
	public void setCategorys(String categorys) {
		this.categorys = categorys == null ? null : categorys.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.movieLevel
	 * @return  the value of sys_contentmain.movieLevel
	 * @mbggenerated
	 */
	public Integer getMovielevel() {
		return movielevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.movieLevel
	 * @param movielevel  the value for sys_contentmain.movieLevel
	 * @mbggenerated
	 */
	public void setMovielevel(Integer movielevel) {
		this.movielevel = movielevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.movieType
	 * @return  the value of sys_contentmain.movieType
	 * @mbggenerated
	 */
	public Integer getMovietype() {
		return movietype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.movieType
	 * @param movietype  the value for sys_contentmain.movieType
	 * @mbggenerated
	 */
	public void setMovietype(Integer movietype) {
		this.movietype = movietype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.vipFlag
	 * @return  the value of sys_contentmain.vipFlag
	 * @mbggenerated
	 */
	public Integer getVipflag() {
		return vipflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.vipFlag
	 * @param vipflag  the value for sys_contentmain.vipFlag
	 * @mbggenerated
	 */
	public void setVipflag(Integer vipflag) {
		this.vipflag = vipflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.Airtime
	 * @return  the value of sys_contentmain.Airtime
	 * @mbggenerated
	 */
	public String getAirtime() {
		return airtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.Airtime
	 * @param airtime  the value for sys_contentmain.Airtime
	 * @mbggenerated
	 */
	public void setAirtime(String airtime) {
		this.airtime = airtime == null ? null : airtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.videoType
	 * @return  the value of sys_contentmain.videoType
	 * @mbggenerated
	 */
	public String getVideotype() {
		return videotype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.videoType
	 * @param videotype  the value for sys_contentmain.videoType
	 * @mbggenerated
	 */
	public void setVideotype(String videotype) {
		this.videotype = videotype == null ? null : videotype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.Tags
	 * @return  the value of sys_contentmain.Tags
	 * @mbggenerated
	 */
	public String getTags() {
		return tags;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.Tags
	 * @param tags  the value for sys_contentmain.Tags
	 * @mbggenerated
	 */
	public void setTags(String tags) {
		this.tags = tags == null ? null : tags.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.area
	 * @return  the value of sys_contentmain.area
	 * @mbggenerated
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.area
	 * @param area  the value for sys_contentmain.area
	 * @mbggenerated
	 */
	public void setArea(String area) {
		this.area = area == null ? null : area.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.Actors
	 * @return  the value of sys_contentmain.Actors
	 * @mbggenerated
	 */
	public String getActors() {
		return actors;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.Actors
	 * @param actors  the value for sys_contentmain.Actors
	 * @mbggenerated
	 */
	public void setActors(String actors) {
		this.actors = actors == null ? null : actors.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.Director
	 * @return  the value of sys_contentmain.Director
	 * @mbggenerated
	 */
	public String getDirector() {
		return director;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.Director
	 * @param director  the value for sys_contentmain.Director
	 * @mbggenerated
	 */
	public void setDirector(String director) {
		this.director = director == null ? null : director.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.EXTFIELD2
	 * @return  the value of sys_contentmain.EXTFIELD2
	 * @mbggenerated
	 */
	public String getExtfield2() {
		return extfield2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.EXTFIELD2
	 * @param extfield2  the value for sys_contentmain.EXTFIELD2
	 * @mbggenerated
	 */
	public void setExtfield2(String extfield2) {
		this.extfield2 = extfield2 == null ? null : extfield2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.CONTENTTYPE
	 * @return  the value of sys_contentmain.CONTENTTYPE
	 * @mbggenerated
	 */
	public String getContenttype() {
		return contenttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.CONTENTTYPE
	 * @param contenttype  the value for sys_contentmain.CONTENTTYPE
	 * @mbggenerated
	 */
	public void setContenttype(String contenttype) {
		this.contenttype = contenttype == null ? null : contenttype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.CREATEDATE
	 * @return  the value of sys_contentmain.CREATEDATE
	 * @mbggenerated
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.CREATEDATE
	 * @param createdate  the value for sys_contentmain.CREATEDATE
	 * @mbggenerated
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.CREATEUSERID
	 * @return  the value of sys_contentmain.CREATEUSERID
	 * @mbggenerated
	 */
	public Integer getCreateuserid() {
		return createuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.CREATEUSERID
	 * @param createuserid  the value for sys_contentmain.CREATEUSERID
	 * @mbggenerated
	 */
	public void setCreateuserid(Integer createuserid) {
		this.createuserid = createuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.CREATEUSERNAME
	 * @return  the value of sys_contentmain.CREATEUSERNAME
	 * @mbggenerated
	 */
	public String getCreateusername() {
		return createusername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.CREATEUSERNAME
	 * @param createusername  the value for sys_contentmain.CREATEUSERNAME
	 * @mbggenerated
	 */
	public void setCreateusername(String createusername) {
		this.createusername = createusername == null ? null : createusername
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.DELETEFLAG
	 * @return  the value of sys_contentmain.DELETEFLAG
	 * @mbggenerated
	 */
	public Integer getDeleteflag() {
		return deleteflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.DELETEFLAG
	 * @param deleteflag  the value for sys_contentmain.DELETEFLAG
	 * @mbggenerated
	 */
	public void setDeleteflag(Integer deleteflag) {
		this.deleteflag = deleteflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.DESCRIPTION
	 * @return  the value of sys_contentmain.DESCRIPTION
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.DESCRIPTION
	 * @param description  the value for sys_contentmain.DESCRIPTION
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.DURATION
	 * @return  the value of sys_contentmain.DURATION
	 * @mbggenerated
	 */
	public Integer getDuration() {
		return duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.DURATION
	 * @param duration  the value for sys_contentmain.DURATION
	 * @mbggenerated
	 */
	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.LASTMODIFIEDDATE
	 * @return  the value of sys_contentmain.LASTMODIFIEDDATE
	 * @mbggenerated
	 */
	public Date getLastmodifieddate() {
		return lastmodifieddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.LASTMODIFIEDDATE
	 * @param lastmodifieddate  the value for sys_contentmain.LASTMODIFIEDDATE
	 * @mbggenerated
	 */
	public void setLastmodifieddate(Date lastmodifieddate) {
		this.lastmodifieddate = lastmodifieddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.PUBLISHDATE
	 * @return  the value of sys_contentmain.PUBLISHDATE
	 * @mbggenerated
	 */
	public Date getPublishdate() {
		return publishdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.PUBLISHDATE
	 * @param publishdate  the value for sys_contentmain.PUBLISHDATE
	 * @mbggenerated
	 */
	public void setPublishdate(Date publishdate) {
		this.publishdate = publishdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.TITLEIMAGE
	 * @return  the value of sys_contentmain.TITLEIMAGE
	 * @mbggenerated
	 */
	public String getTitleimage() {
		return titleimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.TITLEIMAGE
	 * @param titleimage  the value for sys_contentmain.TITLEIMAGE
	 * @mbggenerated
	 */
	public void setTitleimage(String titleimage) {
		this.titleimage = titleimage == null ? null : titleimage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.WEIGHT
	 * @return  the value of sys_contentmain.WEIGHT
	 * @mbggenerated
	 */
	public Integer getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.WEIGHT
	 * @param weight  the value for sys_contentmain.WEIGHT
	 * @mbggenerated
	 */
	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.IMGBIG
	 * @return  the value of sys_contentmain.IMGBIG
	 * @mbggenerated
	 */
	public String getImgbig() {
		return imgbig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.IMGBIG
	 * @param imgbig  the value for sys_contentmain.IMGBIG
	 * @mbggenerated
	 */
	public void setImgbig(String imgbig) {
		this.imgbig = imgbig == null ? null : imgbig.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.IMGSMALL
	 * @return  the value of sys_contentmain.IMGSMALL
	 * @mbggenerated
	 */
	public String getImgsmall() {
		return imgsmall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.IMGSMALL
	 * @param imgsmall  the value for sys_contentmain.IMGSMALL
	 * @mbggenerated
	 */
	public void setImgsmall(String imgsmall) {
		this.imgsmall = imgsmall == null ? null : imgsmall.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.IMGOTHER1
	 * @return  the value of sys_contentmain.IMGOTHER1
	 * @mbggenerated
	 */
	public String getImgother1() {
		return imgother1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.IMGOTHER1
	 * @param imgother1  the value for sys_contentmain.IMGOTHER1
	 * @mbggenerated
	 */
	public void setImgother1(String imgother1) {
		this.imgother1 = imgother1 == null ? null : imgother1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.IMGOTHER2
	 * @return  the value of sys_contentmain.IMGOTHER2
	 * @mbggenerated
	 */
	public String getImgother2() {
		return imgother2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.IMGOTHER2
	 * @param imgother2  the value for sys_contentmain.IMGOTHER2
	 * @mbggenerated
	 */
	public void setImgother2(String imgother2) {
		this.imgother2 = imgother2 == null ? null : imgother2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.VIDEOFLASHLURL
	 * @return  the value of sys_contentmain.VIDEOFLASHLURL
	 * @mbggenerated
	 */
	public String getVideoflashlurl() {
		return videoflashlurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.VIDEOFLASHLURL
	 * @param videoflashlurl  the value for sys_contentmain.VIDEOFLASHLURL
	 * @mbggenerated
	 */
	public void setVideoflashlurl(String videoflashlurl) {
		this.videoflashlurl = videoflashlurl == null ? null : videoflashlurl
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.VIDEOFLASHURL
	 * @return  the value of sys_contentmain.VIDEOFLASHURL
	 * @mbggenerated
	 */
	public String getVideoflashurl() {
		return videoflashurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.VIDEOFLASHURL
	 * @param videoflashurl  the value for sys_contentmain.VIDEOFLASHURL
	 * @mbggenerated
	 */
	public void setVideoflashurl(String videoflashurl) {
		this.videoflashurl = videoflashurl == null ? null : videoflashurl
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.VIDEOFLASHHURL
	 * @return  the value of sys_contentmain.VIDEOFLASHHURL
	 * @mbggenerated
	 */
	public String getVideoflashhurl() {
		return videoflashhurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.VIDEOFLASHHURL
	 * @param videoflashhurl  the value for sys_contentmain.VIDEOFLASHHURL
	 * @mbggenerated
	 */
	public void setVideoflashhurl(String videoflashhurl) {
		this.videoflashhurl = videoflashhurl == null ? null : videoflashhurl
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.VIDEOFLASHUHURL
	 * @return  the value of sys_contentmain.VIDEOFLASHUHURL
	 * @mbggenerated
	 */
	public String getVideoflashuhurl() {
		return videoflashuhurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.VIDEOFLASHUHURL
	 * @param videoflashuhurl  the value for sys_contentmain.VIDEOFLASHUHURL
	 * @mbggenerated
	 */
	public void setVideoflashuhurl(String videoflashuhurl) {
		this.videoflashuhurl = videoflashuhurl == null ? null : videoflashuhurl
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.VIDEOLURL
	 * @return  the value of sys_contentmain.VIDEOLURL
	 * @mbggenerated
	 */
	public String getVideolurl() {
		return videolurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.VIDEOLURL
	 * @param videolurl  the value for sys_contentmain.VIDEOLURL
	 * @mbggenerated
	 */
	public void setVideolurl(String videolurl) {
		this.videolurl = videolurl == null ? null : videolurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.VIDEOURL
	 * @return  the value of sys_contentmain.VIDEOURL
	 * @mbggenerated
	 */
	public String getVideourl() {
		return videourl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.VIDEOURL
	 * @param videourl  the value for sys_contentmain.VIDEOURL
	 * @mbggenerated
	 */
	public void setVideourl(String videourl) {
		this.videourl = videourl == null ? null : videourl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.VideoHUrl
	 * @return  the value of sys_contentmain.VideoHUrl
	 * @mbggenerated
	 */
	public String getVideohurl() {
		return videohurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.VideoHUrl
	 * @param videohurl  the value for sys_contentmain.VideoHUrl
	 * @mbggenerated
	 */
	public void setVideohurl(String videohurl) {
		this.videohurl = videohurl == null ? null : videohurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_contentmain.VideoUHUrl
	 * @return  the value of sys_contentmain.VideoUHUrl
	 * @mbggenerated
	 */
	public String getVideouhurl() {
		return videouhurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_contentmain.VideoUHUrl
	 * @param videouhurl  the value for sys_contentmain.VideoUHUrl
	 * @mbggenerated
	 */
	public void setVideouhurl(String videouhurl) {
		this.videouhurl = videouhurl == null ? null : videouhurl.trim();
	}
}