package com.cnLive.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class sys_contentmainExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public sys_contentmainExample() {
		oredCriteria = new ArrayList<Criteria>();
		page = new Page();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andContentidIsNull() {
			addCriterion("CONTENTID is null");
			return (Criteria) this;
		}

		public Criteria andContentidIsNotNull() {
			addCriterion("CONTENTID is not null");
			return (Criteria) this;
		}

		public Criteria andContentidEqualTo(Integer value) {
			addCriterion("CONTENTID =", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidNotEqualTo(Integer value) {
			addCriterion("CONTENTID <>", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidGreaterThan(Integer value) {
			addCriterion("CONTENTID >", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidGreaterThanOrEqualTo(Integer value) {
			addCriterion("CONTENTID >=", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidLessThan(Integer value) {
			addCriterion("CONTENTID <", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidLessThanOrEqualTo(Integer value) {
			addCriterion("CONTENTID <=", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidIn(List<Integer> values) {
			addCriterion("CONTENTID in", values, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidNotIn(List<Integer> values) {
			addCriterion("CONTENTID not in", values, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidBetween(Integer value1, Integer value2) {
			addCriterion("CONTENTID between", value1, value2, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidNotBetween(Integer value1, Integer value2) {
			addCriterion("CONTENTID not between", value1, value2, "contentid");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("TITLE is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("TITLE =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("TITLE <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("TITLE >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("TITLE >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("TITLE <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("TITLE <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("TITLE like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("TITLE not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("TITLE in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("TITLE not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("TITLE between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("TITLE not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andSubtitleIsNull() {
			addCriterion("SUBTITLE is null");
			return (Criteria) this;
		}

		public Criteria andSubtitleIsNotNull() {
			addCriterion("SUBTITLE is not null");
			return (Criteria) this;
		}

		public Criteria andSubtitleEqualTo(String value) {
			addCriterion("SUBTITLE =", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleNotEqualTo(String value) {
			addCriterion("SUBTITLE <>", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleGreaterThan(String value) {
			addCriterion("SUBTITLE >", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleGreaterThanOrEqualTo(String value) {
			addCriterion("SUBTITLE >=", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleLessThan(String value) {
			addCriterion("SUBTITLE <", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleLessThanOrEqualTo(String value) {
			addCriterion("SUBTITLE <=", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleLike(String value) {
			addCriterion("SUBTITLE like", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleNotLike(String value) {
			addCriterion("SUBTITLE not like", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleIn(List<String> values) {
			addCriterion("SUBTITLE in", values, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleNotIn(List<String> values) {
			addCriterion("SUBTITLE not in", values, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleBetween(String value1, String value2) {
			addCriterion("SUBTITLE between", value1, value2, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleNotBetween(String value1, String value2) {
			addCriterion("SUBTITLE not between", value1, value2, "subtitle");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andUuidIsNull() {
			addCriterion("UUID is null");
			return (Criteria) this;
		}

		public Criteria andUuidIsNotNull() {
			addCriterion("UUID is not null");
			return (Criteria) this;
		}

		public Criteria andUuidEqualTo(String value) {
			addCriterion("UUID =", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotEqualTo(String value) {
			addCriterion("UUID <>", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidGreaterThan(String value) {
			addCriterion("UUID >", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidGreaterThanOrEqualTo(String value) {
			addCriterion("UUID >=", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLessThan(String value) {
			addCriterion("UUID <", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLessThanOrEqualTo(String value) {
			addCriterion("UUID <=", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLike(String value) {
			addCriterion("UUID like", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotLike(String value) {
			addCriterion("UUID not like", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidIn(List<String> values) {
			addCriterion("UUID in", values, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotIn(List<String> values) {
			addCriterion("UUID not in", values, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidBetween(String value1, String value2) {
			addCriterion("UUID between", value1, value2, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotBetween(String value1, String value2) {
			addCriterion("UUID not between", value1, value2, "uuid");
			return (Criteria) this;
		}

		public Criteria andMaincategoryIsNull() {
			addCriterion("MAINCATEGORY is null");
			return (Criteria) this;
		}

		public Criteria andMaincategoryIsNotNull() {
			addCriterion("MAINCATEGORY is not null");
			return (Criteria) this;
		}

		public Criteria andMaincategoryEqualTo(String value) {
			addCriterion("MAINCATEGORY =", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryNotEqualTo(String value) {
			addCriterion("MAINCATEGORY <>", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryGreaterThan(String value) {
			addCriterion("MAINCATEGORY >", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryGreaterThanOrEqualTo(String value) {
			addCriterion("MAINCATEGORY >=", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryLessThan(String value) {
			addCriterion("MAINCATEGORY <", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryLessThanOrEqualTo(String value) {
			addCriterion("MAINCATEGORY <=", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryLike(String value) {
			addCriterion("MAINCATEGORY like", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryNotLike(String value) {
			addCriterion("MAINCATEGORY not like", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryIn(List<String> values) {
			addCriterion("MAINCATEGORY in", values, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryNotIn(List<String> values) {
			addCriterion("MAINCATEGORY not in", values, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryBetween(String value1, String value2) {
			addCriterion("MAINCATEGORY between", value1, value2, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryNotBetween(String value1, String value2) {
			addCriterion("MAINCATEGORY not between", value1, value2,
					"maincategory");
			return (Criteria) this;
		}

		public Criteria andCategorysIsNull() {
			addCriterion("categorys is null");
			return (Criteria) this;
		}

		public Criteria andCategorysIsNotNull() {
			addCriterion("categorys is not null");
			return (Criteria) this;
		}

		public Criteria andCategorysEqualTo(String value) {
			addCriterion("categorys =", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysNotEqualTo(String value) {
			addCriterion("categorys <>", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysGreaterThan(String value) {
			addCriterion("categorys >", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysGreaterThanOrEqualTo(String value) {
			addCriterion("categorys >=", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysLessThan(String value) {
			addCriterion("categorys <", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysLessThanOrEqualTo(String value) {
			addCriterion("categorys <=", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysLike(String value) {
			addCriterion("categorys like", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysNotLike(String value) {
			addCriterion("categorys not like", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysIn(List<String> values) {
			addCriterion("categorys in", values, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysNotIn(List<String> values) {
			addCriterion("categorys not in", values, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysBetween(String value1, String value2) {
			addCriterion("categorys between", value1, value2, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysNotBetween(String value1, String value2) {
			addCriterion("categorys not between", value1, value2, "categorys");
			return (Criteria) this;
		}

		public Criteria andMovielevelIsNull() {
			addCriterion("movieLevel is null");
			return (Criteria) this;
		}

		public Criteria andMovielevelIsNotNull() {
			addCriterion("movieLevel is not null");
			return (Criteria) this;
		}

		public Criteria andMovielevelEqualTo(Integer value) {
			addCriterion("movieLevel =", value, "movielevel");
			return (Criteria) this;
		}

		public Criteria andMovielevelNotEqualTo(Integer value) {
			addCriterion("movieLevel <>", value, "movielevel");
			return (Criteria) this;
		}

		public Criteria andMovielevelGreaterThan(Integer value) {
			addCriterion("movieLevel >", value, "movielevel");
			return (Criteria) this;
		}

		public Criteria andMovielevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("movieLevel >=", value, "movielevel");
			return (Criteria) this;
		}

		public Criteria andMovielevelLessThan(Integer value) {
			addCriterion("movieLevel <", value, "movielevel");
			return (Criteria) this;
		}

		public Criteria andMovielevelLessThanOrEqualTo(Integer value) {
			addCriterion("movieLevel <=", value, "movielevel");
			return (Criteria) this;
		}

		public Criteria andMovielevelIn(List<Integer> values) {
			addCriterion("movieLevel in", values, "movielevel");
			return (Criteria) this;
		}

		public Criteria andMovielevelNotIn(List<Integer> values) {
			addCriterion("movieLevel not in", values, "movielevel");
			return (Criteria) this;
		}

		public Criteria andMovielevelBetween(Integer value1, Integer value2) {
			addCriterion("movieLevel between", value1, value2, "movielevel");
			return (Criteria) this;
		}

		public Criteria andMovielevelNotBetween(Integer value1, Integer value2) {
			addCriterion("movieLevel not between", value1, value2, "movielevel");
			return (Criteria) this;
		}

		public Criteria andMovietypeIsNull() {
			addCriterion("movieType is null");
			return (Criteria) this;
		}

		public Criteria andMovietypeIsNotNull() {
			addCriterion("movieType is not null");
			return (Criteria) this;
		}

		public Criteria andMovietypeEqualTo(Integer value) {
			addCriterion("movieType =", value, "movietype");
			return (Criteria) this;
		}

		public Criteria andMovietypeNotEqualTo(Integer value) {
			addCriterion("movieType <>", value, "movietype");
			return (Criteria) this;
		}

		public Criteria andMovietypeGreaterThan(Integer value) {
			addCriterion("movieType >", value, "movietype");
			return (Criteria) this;
		}

		public Criteria andMovietypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("movieType >=", value, "movietype");
			return (Criteria) this;
		}

		public Criteria andMovietypeLessThan(Integer value) {
			addCriterion("movieType <", value, "movietype");
			return (Criteria) this;
		}

		public Criteria andMovietypeLessThanOrEqualTo(Integer value) {
			addCriterion("movieType <=", value, "movietype");
			return (Criteria) this;
		}

		public Criteria andMovietypeIn(List<Integer> values) {
			addCriterion("movieType in", values, "movietype");
			return (Criteria) this;
		}

		public Criteria andMovietypeNotIn(List<Integer> values) {
			addCriterion("movieType not in", values, "movietype");
			return (Criteria) this;
		}

		public Criteria andMovietypeBetween(Integer value1, Integer value2) {
			addCriterion("movieType between", value1, value2, "movietype");
			return (Criteria) this;
		}

		public Criteria andMovietypeNotBetween(Integer value1, Integer value2) {
			addCriterion("movieType not between", value1, value2, "movietype");
			return (Criteria) this;
		}

		public Criteria andVipflagIsNull() {
			addCriterion("vipFlag is null");
			return (Criteria) this;
		}

		public Criteria andVipflagIsNotNull() {
			addCriterion("vipFlag is not null");
			return (Criteria) this;
		}

		public Criteria andVipflagEqualTo(Integer value) {
			addCriterion("vipFlag =", value, "vipflag");
			return (Criteria) this;
		}

		public Criteria andVipflagNotEqualTo(Integer value) {
			addCriterion("vipFlag <>", value, "vipflag");
			return (Criteria) this;
		}

		public Criteria andVipflagGreaterThan(Integer value) {
			addCriterion("vipFlag >", value, "vipflag");
			return (Criteria) this;
		}

		public Criteria andVipflagGreaterThanOrEqualTo(Integer value) {
			addCriterion("vipFlag >=", value, "vipflag");
			return (Criteria) this;
		}

		public Criteria andVipflagLessThan(Integer value) {
			addCriterion("vipFlag <", value, "vipflag");
			return (Criteria) this;
		}

		public Criteria andVipflagLessThanOrEqualTo(Integer value) {
			addCriterion("vipFlag <=", value, "vipflag");
			return (Criteria) this;
		}

		public Criteria andVipflagIn(List<Integer> values) {
			addCriterion("vipFlag in", values, "vipflag");
			return (Criteria) this;
		}

		public Criteria andVipflagNotIn(List<Integer> values) {
			addCriterion("vipFlag not in", values, "vipflag");
			return (Criteria) this;
		}

		public Criteria andVipflagBetween(Integer value1, Integer value2) {
			addCriterion("vipFlag between", value1, value2, "vipflag");
			return (Criteria) this;
		}

		public Criteria andVipflagNotBetween(Integer value1, Integer value2) {
			addCriterion("vipFlag not between", value1, value2, "vipflag");
			return (Criteria) this;
		}

		public Criteria andAirtimeIsNull() {
			addCriterion("Airtime is null");
			return (Criteria) this;
		}

		public Criteria andAirtimeIsNotNull() {
			addCriterion("Airtime is not null");
			return (Criteria) this;
		}

		public Criteria andAirtimeEqualTo(String value) {
			addCriterion("Airtime =", value, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeNotEqualTo(String value) {
			addCriterion("Airtime <>", value, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeGreaterThan(String value) {
			addCriterion("Airtime >", value, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeGreaterThanOrEqualTo(String value) {
			addCriterion("Airtime >=", value, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeLessThan(String value) {
			addCriterion("Airtime <", value, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeLessThanOrEqualTo(String value) {
			addCriterion("Airtime <=", value, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeLike(String value) {
			addCriterion("Airtime like", value, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeNotLike(String value) {
			addCriterion("Airtime not like", value, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeIn(List<String> values) {
			addCriterion("Airtime in", values, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeNotIn(List<String> values) {
			addCriterion("Airtime not in", values, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeBetween(String value1, String value2) {
			addCriterion("Airtime between", value1, value2, "airtime");
			return (Criteria) this;
		}

		public Criteria andAirtimeNotBetween(String value1, String value2) {
			addCriterion("Airtime not between", value1, value2, "airtime");
			return (Criteria) this;
		}

		public Criteria andVideotypeIsNull() {
			addCriterion("videoType is null");
			return (Criteria) this;
		}

		public Criteria andVideotypeIsNotNull() {
			addCriterion("videoType is not null");
			return (Criteria) this;
		}

		public Criteria andVideotypeEqualTo(String value) {
			addCriterion("videoType =", value, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeNotEqualTo(String value) {
			addCriterion("videoType <>", value, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeGreaterThan(String value) {
			addCriterion("videoType >", value, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeGreaterThanOrEqualTo(String value) {
			addCriterion("videoType >=", value, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeLessThan(String value) {
			addCriterion("videoType <", value, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeLessThanOrEqualTo(String value) {
			addCriterion("videoType <=", value, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeLike(String value) {
			addCriterion("videoType like", value, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeNotLike(String value) {
			addCriterion("videoType not like", value, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeIn(List<String> values) {
			addCriterion("videoType in", values, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeNotIn(List<String> values) {
			addCriterion("videoType not in", values, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeBetween(String value1, String value2) {
			addCriterion("videoType between", value1, value2, "videotype");
			return (Criteria) this;
		}

		public Criteria andVideotypeNotBetween(String value1, String value2) {
			addCriterion("videoType not between", value1, value2, "videotype");
			return (Criteria) this;
		}

		public Criteria andTagsIsNull() {
			addCriterion("Tags is null");
			return (Criteria) this;
		}

		public Criteria andTagsIsNotNull() {
			addCriterion("Tags is not null");
			return (Criteria) this;
		}

		public Criteria andTagsEqualTo(String value) {
			addCriterion("Tags =", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotEqualTo(String value) {
			addCriterion("Tags <>", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsGreaterThan(String value) {
			addCriterion("Tags >", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsGreaterThanOrEqualTo(String value) {
			addCriterion("Tags >=", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsLessThan(String value) {
			addCriterion("Tags <", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsLessThanOrEqualTo(String value) {
			addCriterion("Tags <=", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsLike(String value) {
			addCriterion("Tags like", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotLike(String value) {
			addCriterion("Tags not like", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsIn(List<String> values) {
			addCriterion("Tags in", values, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotIn(List<String> values) {
			addCriterion("Tags not in", values, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsBetween(String value1, String value2) {
			addCriterion("Tags between", value1, value2, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotBetween(String value1, String value2) {
			addCriterion("Tags not between", value1, value2, "tags");
			return (Criteria) this;
		}

		public Criteria andAreaIsNull() {
			addCriterion("area is null");
			return (Criteria) this;
		}

		public Criteria andAreaIsNotNull() {
			addCriterion("area is not null");
			return (Criteria) this;
		}

		public Criteria andAreaEqualTo(String value) {
			addCriterion("area =", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotEqualTo(String value) {
			addCriterion("area <>", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaGreaterThan(String value) {
			addCriterion("area >", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaGreaterThanOrEqualTo(String value) {
			addCriterion("area >=", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLessThan(String value) {
			addCriterion("area <", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLessThanOrEqualTo(String value) {
			addCriterion("area <=", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLike(String value) {
			addCriterion("area like", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotLike(String value) {
			addCriterion("area not like", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaIn(List<String> values) {
			addCriterion("area in", values, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotIn(List<String> values) {
			addCriterion("area not in", values, "area");
			return (Criteria) this;
		}

		public Criteria andAreaBetween(String value1, String value2) {
			addCriterion("area between", value1, value2, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotBetween(String value1, String value2) {
			addCriterion("area not between", value1, value2, "area");
			return (Criteria) this;
		}

		public Criteria andActorsIsNull() {
			addCriterion("Actors is null");
			return (Criteria) this;
		}

		public Criteria andActorsIsNotNull() {
			addCriterion("Actors is not null");
			return (Criteria) this;
		}

		public Criteria andActorsEqualTo(String value) {
			addCriterion("Actors =", value, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsNotEqualTo(String value) {
			addCriterion("Actors <>", value, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsGreaterThan(String value) {
			addCriterion("Actors >", value, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsGreaterThanOrEqualTo(String value) {
			addCriterion("Actors >=", value, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsLessThan(String value) {
			addCriterion("Actors <", value, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsLessThanOrEqualTo(String value) {
			addCriterion("Actors <=", value, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsLike(String value) {
			addCriterion("Actors like", value, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsNotLike(String value) {
			addCriterion("Actors not like", value, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsIn(List<String> values) {
			addCriterion("Actors in", values, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsNotIn(List<String> values) {
			addCriterion("Actors not in", values, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsBetween(String value1, String value2) {
			addCriterion("Actors between", value1, value2, "actors");
			return (Criteria) this;
		}

		public Criteria andActorsNotBetween(String value1, String value2) {
			addCriterion("Actors not between", value1, value2, "actors");
			return (Criteria) this;
		}

		public Criteria andDirectorIsNull() {
			addCriterion("Director is null");
			return (Criteria) this;
		}

		public Criteria andDirectorIsNotNull() {
			addCriterion("Director is not null");
			return (Criteria) this;
		}

		public Criteria andDirectorEqualTo(String value) {
			addCriterion("Director =", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotEqualTo(String value) {
			addCriterion("Director <>", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorGreaterThan(String value) {
			addCriterion("Director >", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorGreaterThanOrEqualTo(String value) {
			addCriterion("Director >=", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorLessThan(String value) {
			addCriterion("Director <", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorLessThanOrEqualTo(String value) {
			addCriterion("Director <=", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorLike(String value) {
			addCriterion("Director like", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotLike(String value) {
			addCriterion("Director not like", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorIn(List<String> values) {
			addCriterion("Director in", values, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotIn(List<String> values) {
			addCriterion("Director not in", values, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorBetween(String value1, String value2) {
			addCriterion("Director between", value1, value2, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotBetween(String value1, String value2) {
			addCriterion("Director not between", value1, value2, "director");
			return (Criteria) this;
		}

		public Criteria andExtfield2IsNull() {
			addCriterion("EXTFIELD2 is null");
			return (Criteria) this;
		}

		public Criteria andExtfield2IsNotNull() {
			addCriterion("EXTFIELD2 is not null");
			return (Criteria) this;
		}

		public Criteria andExtfield2EqualTo(String value) {
			addCriterion("EXTFIELD2 =", value, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2NotEqualTo(String value) {
			addCriterion("EXTFIELD2 <>", value, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2GreaterThan(String value) {
			addCriterion("EXTFIELD2 >", value, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2GreaterThanOrEqualTo(String value) {
			addCriterion("EXTFIELD2 >=", value, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2LessThan(String value) {
			addCriterion("EXTFIELD2 <", value, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2LessThanOrEqualTo(String value) {
			addCriterion("EXTFIELD2 <=", value, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2Like(String value) {
			addCriterion("EXTFIELD2 like", value, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2NotLike(String value) {
			addCriterion("EXTFIELD2 not like", value, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2In(List<String> values) {
			addCriterion("EXTFIELD2 in", values, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2NotIn(List<String> values) {
			addCriterion("EXTFIELD2 not in", values, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2Between(String value1, String value2) {
			addCriterion("EXTFIELD2 between", value1, value2, "extfield2");
			return (Criteria) this;
		}

		public Criteria andExtfield2NotBetween(String value1, String value2) {
			addCriterion("EXTFIELD2 not between", value1, value2, "extfield2");
			return (Criteria) this;
		}

		public Criteria andContenttypeIsNull() {
			addCriterion("CONTENTTYPE is null");
			return (Criteria) this;
		}

		public Criteria andContenttypeIsNotNull() {
			addCriterion("CONTENTTYPE is not null");
			return (Criteria) this;
		}

		public Criteria andContenttypeEqualTo(String value) {
			addCriterion("CONTENTTYPE =", value, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeNotEqualTo(String value) {
			addCriterion("CONTENTTYPE <>", value, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeGreaterThan(String value) {
			addCriterion("CONTENTTYPE >", value, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeGreaterThanOrEqualTo(String value) {
			addCriterion("CONTENTTYPE >=", value, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeLessThan(String value) {
			addCriterion("CONTENTTYPE <", value, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeLessThanOrEqualTo(String value) {
			addCriterion("CONTENTTYPE <=", value, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeLike(String value) {
			addCriterion("CONTENTTYPE like", value, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeNotLike(String value) {
			addCriterion("CONTENTTYPE not like", value, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeIn(List<String> values) {
			addCriterion("CONTENTTYPE in", values, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeNotIn(List<String> values) {
			addCriterion("CONTENTTYPE not in", values, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeBetween(String value1, String value2) {
			addCriterion("CONTENTTYPE between", value1, value2, "contenttype");
			return (Criteria) this;
		}

		public Criteria andContenttypeNotBetween(String value1, String value2) {
			addCriterion("CONTENTTYPE not between", value1, value2,
					"contenttype");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("CREATEDATE is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("CREATEDATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("CREATEDATE =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("CREATEDATE <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("CREATEDATE >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATEDATE >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("CREATEDATE <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("CREATEDATE <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterion("CREATEDATE in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterion("CREATEDATE not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("CREATEDATE between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("CREATEDATE not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreateuseridIsNull() {
			addCriterion("CREATEUSERID is null");
			return (Criteria) this;
		}

		public Criteria andCreateuseridIsNotNull() {
			addCriterion("CREATEUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andCreateuseridEqualTo(Integer value) {
			addCriterion("CREATEUSERID =", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridNotEqualTo(Integer value) {
			addCriterion("CREATEUSERID <>", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridGreaterThan(Integer value) {
			addCriterion("CREATEUSERID >", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("CREATEUSERID >=", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridLessThan(Integer value) {
			addCriterion("CREATEUSERID <", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridLessThanOrEqualTo(Integer value) {
			addCriterion("CREATEUSERID <=", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridIn(List<Integer> values) {
			addCriterion("CREATEUSERID in", values, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridNotIn(List<Integer> values) {
			addCriterion("CREATEUSERID not in", values, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridBetween(Integer value1, Integer value2) {
			addCriterion("CREATEUSERID between", value1, value2, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridNotBetween(Integer value1, Integer value2) {
			addCriterion("CREATEUSERID not between", value1, value2,
					"createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateusernameIsNull() {
			addCriterion("CREATEUSERNAME is null");
			return (Criteria) this;
		}

		public Criteria andCreateusernameIsNotNull() {
			addCriterion("CREATEUSERNAME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateusernameEqualTo(String value) {
			addCriterion("CREATEUSERNAME =", value, "createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameNotEqualTo(String value) {
			addCriterion("CREATEUSERNAME <>", value, "createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameGreaterThan(String value) {
			addCriterion("CREATEUSERNAME >", value, "createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameGreaterThanOrEqualTo(String value) {
			addCriterion("CREATEUSERNAME >=", value, "createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameLessThan(String value) {
			addCriterion("CREATEUSERNAME <", value, "createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameLessThanOrEqualTo(String value) {
			addCriterion("CREATEUSERNAME <=", value, "createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameLike(String value) {
			addCriterion("CREATEUSERNAME like", value, "createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameNotLike(String value) {
			addCriterion("CREATEUSERNAME not like", value, "createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameIn(List<String> values) {
			addCriterion("CREATEUSERNAME in", values, "createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameNotIn(List<String> values) {
			addCriterion("CREATEUSERNAME not in", values, "createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameBetween(String value1, String value2) {
			addCriterion("CREATEUSERNAME between", value1, value2,
					"createusername");
			return (Criteria) this;
		}

		public Criteria andCreateusernameNotBetween(String value1, String value2) {
			addCriterion("CREATEUSERNAME not between", value1, value2,
					"createusername");
			return (Criteria) this;
		}

		public Criteria andDeleteflagIsNull() {
			addCriterion("DELETEFLAG is null");
			return (Criteria) this;
		}

		public Criteria andDeleteflagIsNotNull() {
			addCriterion("DELETEFLAG is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteflagEqualTo(Integer value) {
			addCriterion("DELETEFLAG =", value, "deleteflag");
			return (Criteria) this;
		}

		public Criteria andDeleteflagNotEqualTo(Integer value) {
			addCriterion("DELETEFLAG <>", value, "deleteflag");
			return (Criteria) this;
		}

		public Criteria andDeleteflagGreaterThan(Integer value) {
			addCriterion("DELETEFLAG >", value, "deleteflag");
			return (Criteria) this;
		}

		public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
			addCriterion("DELETEFLAG >=", value, "deleteflag");
			return (Criteria) this;
		}

		public Criteria andDeleteflagLessThan(Integer value) {
			addCriterion("DELETEFLAG <", value, "deleteflag");
			return (Criteria) this;
		}

		public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
			addCriterion("DELETEFLAG <=", value, "deleteflag");
			return (Criteria) this;
		}

		public Criteria andDeleteflagIn(List<Integer> values) {
			addCriterion("DELETEFLAG in", values, "deleteflag");
			return (Criteria) this;
		}

		public Criteria andDeleteflagNotIn(List<Integer> values) {
			addCriterion("DELETEFLAG not in", values, "deleteflag");
			return (Criteria) this;
		}

		public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
			addCriterion("DELETEFLAG between", value1, value2, "deleteflag");
			return (Criteria) this;
		}

		public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
			addCriterion("DELETEFLAG not between", value1, value2, "deleteflag");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("DESCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("DESCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("DESCRIPTION =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("DESCRIPTION <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("DESCRIPTION >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("DESCRIPTION <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("DESCRIPTION like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("DESCRIPTION not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("DESCRIPTION in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("DESCRIPTION not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("DESCRIPTION between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("DESCRIPTION not between", value1, value2,
					"description");
			return (Criteria) this;
		}

		public Criteria andDurationIsNull() {
			addCriterion("DURATION is null");
			return (Criteria) this;
		}

		public Criteria andDurationIsNotNull() {
			addCriterion("DURATION is not null");
			return (Criteria) this;
		}

		public Criteria andDurationEqualTo(Long value) {
			addCriterion("DURATION =", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotEqualTo(Long value) {
			addCriterion("DURATION <>", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationGreaterThan(Long value) {
			addCriterion("DURATION >", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationGreaterThanOrEqualTo(Long value) {
			addCriterion("DURATION >=", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLessThan(Long value) {
			addCriterion("DURATION <", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLessThanOrEqualTo(Long value) {
			addCriterion("DURATION <=", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationIn(List<Long> values) {
			addCriterion("DURATION in", values, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotIn(List<Long> values) {
			addCriterion("DURATION not in", values, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationBetween(Long value1, Long value2) {
			addCriterion("DURATION between", value1, value2, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotBetween(Long value1, Long value2) {
			addCriterion("DURATION not between", value1, value2, "duration");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateIsNull() {
			addCriterion("LASTMODIFIEDDATE is null");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateIsNotNull() {
			addCriterion("LASTMODIFIEDDATE is not null");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateEqualTo(Date value) {
			addCriterion("LASTMODIFIEDDATE =", value, "lastmodifieddate");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateNotEqualTo(Date value) {
			addCriterion("LASTMODIFIEDDATE <>", value, "lastmodifieddate");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateGreaterThan(Date value) {
			addCriterion("LASTMODIFIEDDATE >", value, "lastmodifieddate");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateGreaterThanOrEqualTo(Date value) {
			addCriterion("LASTMODIFIEDDATE >=", value, "lastmodifieddate");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateLessThan(Date value) {
			addCriterion("LASTMODIFIEDDATE <", value, "lastmodifieddate");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateLessThanOrEqualTo(Date value) {
			addCriterion("LASTMODIFIEDDATE <=", value, "lastmodifieddate");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateIn(List<Date> values) {
			addCriterion("LASTMODIFIEDDATE in", values, "lastmodifieddate");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateNotIn(List<Date> values) {
			addCriterion("LASTMODIFIEDDATE not in", values, "lastmodifieddate");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateBetween(Date value1, Date value2) {
			addCriterion("LASTMODIFIEDDATE between", value1, value2,
					"lastmodifieddate");
			return (Criteria) this;
		}

		public Criteria andLastmodifieddateNotBetween(Date value1, Date value2) {
			addCriterion("LASTMODIFIEDDATE not between", value1, value2,
					"lastmodifieddate");
			return (Criteria) this;
		}

		public Criteria andPublishdateIsNull() {
			addCriterion("PUBLISHDATE is null");
			return (Criteria) this;
		}

		public Criteria andPublishdateIsNotNull() {
			addCriterion("PUBLISHDATE is not null");
			return (Criteria) this;
		}

		public Criteria andPublishdateEqualTo(Date value) {
			addCriterion("PUBLISHDATE =", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateNotEqualTo(Date value) {
			addCriterion("PUBLISHDATE <>", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateGreaterThan(Date value) {
			addCriterion("PUBLISHDATE >", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateGreaterThanOrEqualTo(Date value) {
			addCriterion("PUBLISHDATE >=", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateLessThan(Date value) {
			addCriterion("PUBLISHDATE <", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateLessThanOrEqualTo(Date value) {
			addCriterion("PUBLISHDATE <=", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateIn(List<Date> values) {
			addCriterion("PUBLISHDATE in", values, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateNotIn(List<Date> values) {
			addCriterion("PUBLISHDATE not in", values, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateBetween(Date value1, Date value2) {
			addCriterion("PUBLISHDATE between", value1, value2, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateNotBetween(Date value1, Date value2) {
			addCriterion("PUBLISHDATE not between", value1, value2,
					"publishdate");
			return (Criteria) this;
		}

		public Criteria andTitleimageIsNull() {
			addCriterion("TITLEIMAGE is null");
			return (Criteria) this;
		}

		public Criteria andTitleimageIsNotNull() {
			addCriterion("TITLEIMAGE is not null");
			return (Criteria) this;
		}

		public Criteria andTitleimageEqualTo(String value) {
			addCriterion("TITLEIMAGE =", value, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageNotEqualTo(String value) {
			addCriterion("TITLEIMAGE <>", value, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageGreaterThan(String value) {
			addCriterion("TITLEIMAGE >", value, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageGreaterThanOrEqualTo(String value) {
			addCriterion("TITLEIMAGE >=", value, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageLessThan(String value) {
			addCriterion("TITLEIMAGE <", value, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageLessThanOrEqualTo(String value) {
			addCriterion("TITLEIMAGE <=", value, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageLike(String value) {
			addCriterion("TITLEIMAGE like", value, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageNotLike(String value) {
			addCriterion("TITLEIMAGE not like", value, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageIn(List<String> values) {
			addCriterion("TITLEIMAGE in", values, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageNotIn(List<String> values) {
			addCriterion("TITLEIMAGE not in", values, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageBetween(String value1, String value2) {
			addCriterion("TITLEIMAGE between", value1, value2, "titleimage");
			return (Criteria) this;
		}

		public Criteria andTitleimageNotBetween(String value1, String value2) {
			addCriterion("TITLEIMAGE not between", value1, value2, "titleimage");
			return (Criteria) this;
		}

		public Criteria andWeightIsNull() {
			addCriterion("WEIGHT is null");
			return (Criteria) this;
		}

		public Criteria andWeightIsNotNull() {
			addCriterion("WEIGHT is not null");
			return (Criteria) this;
		}

		public Criteria andWeightEqualTo(Integer value) {
			addCriterion("WEIGHT =", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotEqualTo(Integer value) {
			addCriterion("WEIGHT <>", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThan(Integer value) {
			addCriterion("WEIGHT >", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("WEIGHT >=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThan(Integer value) {
			addCriterion("WEIGHT <", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThanOrEqualTo(Integer value) {
			addCriterion("WEIGHT <=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightIn(List<Integer> values) {
			addCriterion("WEIGHT in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotIn(List<Integer> values) {
			addCriterion("WEIGHT not in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightBetween(Integer value1, Integer value2) {
			addCriterion("WEIGHT between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotBetween(Integer value1, Integer value2) {
			addCriterion("WEIGHT not between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andImgbigIsNull() {
			addCriterion("IMGBIG is null");
			return (Criteria) this;
		}

		public Criteria andImgbigIsNotNull() {
			addCriterion("IMGBIG is not null");
			return (Criteria) this;
		}

		public Criteria andImgbigEqualTo(String value) {
			addCriterion("IMGBIG =", value, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigNotEqualTo(String value) {
			addCriterion("IMGBIG <>", value, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigGreaterThan(String value) {
			addCriterion("IMGBIG >", value, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigGreaterThanOrEqualTo(String value) {
			addCriterion("IMGBIG >=", value, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigLessThan(String value) {
			addCriterion("IMGBIG <", value, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigLessThanOrEqualTo(String value) {
			addCriterion("IMGBIG <=", value, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigLike(String value) {
			addCriterion("IMGBIG like", value, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigNotLike(String value) {
			addCriterion("IMGBIG not like", value, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigIn(List<String> values) {
			addCriterion("IMGBIG in", values, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigNotIn(List<String> values) {
			addCriterion("IMGBIG not in", values, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigBetween(String value1, String value2) {
			addCriterion("IMGBIG between", value1, value2, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgbigNotBetween(String value1, String value2) {
			addCriterion("IMGBIG not between", value1, value2, "imgbig");
			return (Criteria) this;
		}

		public Criteria andImgsmallIsNull() {
			addCriterion("IMGSMALL is null");
			return (Criteria) this;
		}

		public Criteria andImgsmallIsNotNull() {
			addCriterion("IMGSMALL is not null");
			return (Criteria) this;
		}

		public Criteria andImgsmallEqualTo(String value) {
			addCriterion("IMGSMALL =", value, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallNotEqualTo(String value) {
			addCriterion("IMGSMALL <>", value, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallGreaterThan(String value) {
			addCriterion("IMGSMALL >", value, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallGreaterThanOrEqualTo(String value) {
			addCriterion("IMGSMALL >=", value, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallLessThan(String value) {
			addCriterion("IMGSMALL <", value, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallLessThanOrEqualTo(String value) {
			addCriterion("IMGSMALL <=", value, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallLike(String value) {
			addCriterion("IMGSMALL like", value, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallNotLike(String value) {
			addCriterion("IMGSMALL not like", value, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallIn(List<String> values) {
			addCriterion("IMGSMALL in", values, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallNotIn(List<String> values) {
			addCriterion("IMGSMALL not in", values, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallBetween(String value1, String value2) {
			addCriterion("IMGSMALL between", value1, value2, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgsmallNotBetween(String value1, String value2) {
			addCriterion("IMGSMALL not between", value1, value2, "imgsmall");
			return (Criteria) this;
		}

		public Criteria andImgother1IsNull() {
			addCriterion("IMGOTHER1 is null");
			return (Criteria) this;
		}

		public Criteria andImgother1IsNotNull() {
			addCriterion("IMGOTHER1 is not null");
			return (Criteria) this;
		}

		public Criteria andImgother1EqualTo(String value) {
			addCriterion("IMGOTHER1 =", value, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1NotEqualTo(String value) {
			addCriterion("IMGOTHER1 <>", value, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1GreaterThan(String value) {
			addCriterion("IMGOTHER1 >", value, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1GreaterThanOrEqualTo(String value) {
			addCriterion("IMGOTHER1 >=", value, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1LessThan(String value) {
			addCriterion("IMGOTHER1 <", value, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1LessThanOrEqualTo(String value) {
			addCriterion("IMGOTHER1 <=", value, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1Like(String value) {
			addCriterion("IMGOTHER1 like", value, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1NotLike(String value) {
			addCriterion("IMGOTHER1 not like", value, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1In(List<String> values) {
			addCriterion("IMGOTHER1 in", values, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1NotIn(List<String> values) {
			addCriterion("IMGOTHER1 not in", values, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1Between(String value1, String value2) {
			addCriterion("IMGOTHER1 between", value1, value2, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother1NotBetween(String value1, String value2) {
			addCriterion("IMGOTHER1 not between", value1, value2, "imgother1");
			return (Criteria) this;
		}

		public Criteria andImgother2IsNull() {
			addCriterion("IMGOTHER2 is null");
			return (Criteria) this;
		}

		public Criteria andImgother2IsNotNull() {
			addCriterion("IMGOTHER2 is not null");
			return (Criteria) this;
		}

		public Criteria andImgother2EqualTo(String value) {
			addCriterion("IMGOTHER2 =", value, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2NotEqualTo(String value) {
			addCriterion("IMGOTHER2 <>", value, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2GreaterThan(String value) {
			addCriterion("IMGOTHER2 >", value, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2GreaterThanOrEqualTo(String value) {
			addCriterion("IMGOTHER2 >=", value, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2LessThan(String value) {
			addCriterion("IMGOTHER2 <", value, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2LessThanOrEqualTo(String value) {
			addCriterion("IMGOTHER2 <=", value, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2Like(String value) {
			addCriterion("IMGOTHER2 like", value, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2NotLike(String value) {
			addCriterion("IMGOTHER2 not like", value, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2In(List<String> values) {
			addCriterion("IMGOTHER2 in", values, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2NotIn(List<String> values) {
			addCriterion("IMGOTHER2 not in", values, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2Between(String value1, String value2) {
			addCriterion("IMGOTHER2 between", value1, value2, "imgother2");
			return (Criteria) this;
		}

		public Criteria andImgother2NotBetween(String value1, String value2) {
			addCriterion("IMGOTHER2 not between", value1, value2, "imgother2");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlIsNull() {
			addCriterion("VIDEOFLASHLURL is null");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlIsNotNull() {
			addCriterion("VIDEOFLASHLURL is not null");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlEqualTo(String value) {
			addCriterion("VIDEOFLASHLURL =", value, "videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlNotEqualTo(String value) {
			addCriterion("VIDEOFLASHLURL <>", value, "videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlGreaterThan(String value) {
			addCriterion("VIDEOFLASHLURL >", value, "videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlGreaterThanOrEqualTo(String value) {
			addCriterion("VIDEOFLASHLURL >=", value, "videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlLessThan(String value) {
			addCriterion("VIDEOFLASHLURL <", value, "videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlLessThanOrEqualTo(String value) {
			addCriterion("VIDEOFLASHLURL <=", value, "videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlLike(String value) {
			addCriterion("VIDEOFLASHLURL like", value, "videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlNotLike(String value) {
			addCriterion("VIDEOFLASHLURL not like", value, "videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlIn(List<String> values) {
			addCriterion("VIDEOFLASHLURL in", values, "videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlNotIn(List<String> values) {
			addCriterion("VIDEOFLASHLURL not in", values, "videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlBetween(String value1, String value2) {
			addCriterion("VIDEOFLASHLURL between", value1, value2,
					"videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashlurlNotBetween(String value1, String value2) {
			addCriterion("VIDEOFLASHLURL not between", value1, value2,
					"videoflashlurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlIsNull() {
			addCriterion("VIDEOFLASHURL is null");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlIsNotNull() {
			addCriterion("VIDEOFLASHURL is not null");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlEqualTo(String value) {
			addCriterion("VIDEOFLASHURL =", value, "videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlNotEqualTo(String value) {
			addCriterion("VIDEOFLASHURL <>", value, "videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlGreaterThan(String value) {
			addCriterion("VIDEOFLASHURL >", value, "videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlGreaterThanOrEqualTo(String value) {
			addCriterion("VIDEOFLASHURL >=", value, "videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlLessThan(String value) {
			addCriterion("VIDEOFLASHURL <", value, "videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlLessThanOrEqualTo(String value) {
			addCriterion("VIDEOFLASHURL <=", value, "videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlLike(String value) {
			addCriterion("VIDEOFLASHURL like", value, "videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlNotLike(String value) {
			addCriterion("VIDEOFLASHURL not like", value, "videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlIn(List<String> values) {
			addCriterion("VIDEOFLASHURL in", values, "videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlNotIn(List<String> values) {
			addCriterion("VIDEOFLASHURL not in", values, "videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlBetween(String value1, String value2) {
			addCriterion("VIDEOFLASHURL between", value1, value2,
					"videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashurlNotBetween(String value1, String value2) {
			addCriterion("VIDEOFLASHURL not between", value1, value2,
					"videoflashurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlIsNull() {
			addCriterion("VIDEOFLASHHURL is null");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlIsNotNull() {
			addCriterion("VIDEOFLASHHURL is not null");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlEqualTo(String value) {
			addCriterion("VIDEOFLASHHURL =", value, "videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlNotEqualTo(String value) {
			addCriterion("VIDEOFLASHHURL <>", value, "videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlGreaterThan(String value) {
			addCriterion("VIDEOFLASHHURL >", value, "videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlGreaterThanOrEqualTo(String value) {
			addCriterion("VIDEOFLASHHURL >=", value, "videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlLessThan(String value) {
			addCriterion("VIDEOFLASHHURL <", value, "videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlLessThanOrEqualTo(String value) {
			addCriterion("VIDEOFLASHHURL <=", value, "videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlLike(String value) {
			addCriterion("VIDEOFLASHHURL like", value, "videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlNotLike(String value) {
			addCriterion("VIDEOFLASHHURL not like", value, "videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlIn(List<String> values) {
			addCriterion("VIDEOFLASHHURL in", values, "videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlNotIn(List<String> values) {
			addCriterion("VIDEOFLASHHURL not in", values, "videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlBetween(String value1, String value2) {
			addCriterion("VIDEOFLASHHURL between", value1, value2,
					"videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashhurlNotBetween(String value1, String value2) {
			addCriterion("VIDEOFLASHHURL not between", value1, value2,
					"videoflashhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlIsNull() {
			addCriterion("VIDEOFLASHUHURL is null");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlIsNotNull() {
			addCriterion("VIDEOFLASHUHURL is not null");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlEqualTo(String value) {
			addCriterion("VIDEOFLASHUHURL =", value, "videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlNotEqualTo(String value) {
			addCriterion("VIDEOFLASHUHURL <>", value, "videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlGreaterThan(String value) {
			addCriterion("VIDEOFLASHUHURL >", value, "videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlGreaterThanOrEqualTo(String value) {
			addCriterion("VIDEOFLASHUHURL >=", value, "videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlLessThan(String value) {
			addCriterion("VIDEOFLASHUHURL <", value, "videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlLessThanOrEqualTo(String value) {
			addCriterion("VIDEOFLASHUHURL <=", value, "videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlLike(String value) {
			addCriterion("VIDEOFLASHUHURL like", value, "videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlNotLike(String value) {
			addCriterion("VIDEOFLASHUHURL not like", value, "videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlIn(List<String> values) {
			addCriterion("VIDEOFLASHUHURL in", values, "videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlNotIn(List<String> values) {
			addCriterion("VIDEOFLASHUHURL not in", values, "videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlBetween(String value1, String value2) {
			addCriterion("VIDEOFLASHUHURL between", value1, value2,
					"videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideoflashuhurlNotBetween(String value1,
				String value2) {
			addCriterion("VIDEOFLASHUHURL not between", value1, value2,
					"videoflashuhurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlIsNull() {
			addCriterion("VIDEOLURL is null");
			return (Criteria) this;
		}

		public Criteria andVideolurlIsNotNull() {
			addCriterion("VIDEOLURL is not null");
			return (Criteria) this;
		}

		public Criteria andVideolurlEqualTo(String value) {
			addCriterion("VIDEOLURL =", value, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlNotEqualTo(String value) {
			addCriterion("VIDEOLURL <>", value, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlGreaterThan(String value) {
			addCriterion("VIDEOLURL >", value, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlGreaterThanOrEqualTo(String value) {
			addCriterion("VIDEOLURL >=", value, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlLessThan(String value) {
			addCriterion("VIDEOLURL <", value, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlLessThanOrEqualTo(String value) {
			addCriterion("VIDEOLURL <=", value, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlLike(String value) {
			addCriterion("VIDEOLURL like", value, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlNotLike(String value) {
			addCriterion("VIDEOLURL not like", value, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlIn(List<String> values) {
			addCriterion("VIDEOLURL in", values, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlNotIn(List<String> values) {
			addCriterion("VIDEOLURL not in", values, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlBetween(String value1, String value2) {
			addCriterion("VIDEOLURL between", value1, value2, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideolurlNotBetween(String value1, String value2) {
			addCriterion("VIDEOLURL not between", value1, value2, "videolurl");
			return (Criteria) this;
		}

		public Criteria andVideourlIsNull() {
			addCriterion("VIDEOURL is null");
			return (Criteria) this;
		}

		public Criteria andVideourlIsNotNull() {
			addCriterion("VIDEOURL is not null");
			return (Criteria) this;
		}

		public Criteria andVideourlEqualTo(String value) {
			addCriterion("VIDEOURL =", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlNotEqualTo(String value) {
			addCriterion("VIDEOURL <>", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlGreaterThan(String value) {
			addCriterion("VIDEOURL >", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlGreaterThanOrEqualTo(String value) {
			addCriterion("VIDEOURL >=", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlLessThan(String value) {
			addCriterion("VIDEOURL <", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlLessThanOrEqualTo(String value) {
			addCriterion("VIDEOURL <=", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlLike(String value) {
			addCriterion("VIDEOURL like", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlNotLike(String value) {
			addCriterion("VIDEOURL not like", value, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlIn(List<String> values) {
			addCriterion("VIDEOURL in", values, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlNotIn(List<String> values) {
			addCriterion("VIDEOURL not in", values, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlBetween(String value1, String value2) {
			addCriterion("VIDEOURL between", value1, value2, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideourlNotBetween(String value1, String value2) {
			addCriterion("VIDEOURL not between", value1, value2, "videourl");
			return (Criteria) this;
		}

		public Criteria andVideohurlIsNull() {
			addCriterion("VideoHUrl is null");
			return (Criteria) this;
		}

		public Criteria andVideohurlIsNotNull() {
			addCriterion("VideoHUrl is not null");
			return (Criteria) this;
		}

		public Criteria andVideohurlEqualTo(String value) {
			addCriterion("VideoHUrl =", value, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlNotEqualTo(String value) {
			addCriterion("VideoHUrl <>", value, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlGreaterThan(String value) {
			addCriterion("VideoHUrl >", value, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlGreaterThanOrEqualTo(String value) {
			addCriterion("VideoHUrl >=", value, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlLessThan(String value) {
			addCriterion("VideoHUrl <", value, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlLessThanOrEqualTo(String value) {
			addCriterion("VideoHUrl <=", value, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlLike(String value) {
			addCriterion("VideoHUrl like", value, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlNotLike(String value) {
			addCriterion("VideoHUrl not like", value, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlIn(List<String> values) {
			addCriterion("VideoHUrl in", values, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlNotIn(List<String> values) {
			addCriterion("VideoHUrl not in", values, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlBetween(String value1, String value2) {
			addCriterion("VideoHUrl between", value1, value2, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideohurlNotBetween(String value1, String value2) {
			addCriterion("VideoHUrl not between", value1, value2, "videohurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlIsNull() {
			addCriterion("VideoUHUrl is null");
			return (Criteria) this;
		}

		public Criteria andVideouhurlIsNotNull() {
			addCriterion("VideoUHUrl is not null");
			return (Criteria) this;
		}

		public Criteria andVideouhurlEqualTo(String value) {
			addCriterion("VideoUHUrl =", value, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlNotEqualTo(String value) {
			addCriterion("VideoUHUrl <>", value, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlGreaterThan(String value) {
			addCriterion("VideoUHUrl >", value, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlGreaterThanOrEqualTo(String value) {
			addCriterion("VideoUHUrl >=", value, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlLessThan(String value) {
			addCriterion("VideoUHUrl <", value, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlLessThanOrEqualTo(String value) {
			addCriterion("VideoUHUrl <=", value, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlLike(String value) {
			addCriterion("VideoUHUrl like", value, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlNotLike(String value) {
			addCriterion("VideoUHUrl not like", value, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlIn(List<String> values) {
			addCriterion("VideoUHUrl in", values, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlNotIn(List<String> values) {
			addCriterion("VideoUHUrl not in", values, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlBetween(String value1, String value2) {
			addCriterion("VideoUHUrl between", value1, value2, "videouhurl");
			return (Criteria) this;
		}

		public Criteria andVideouhurlNotBetween(String value1, String value2) {
			addCriterion("VideoUHUrl not between", value1, value2, "videouhurl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_contentmain
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	protected Page page;  

    public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_contentmain
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}