package com.cnLive.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class mediaAssetExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table media_asset
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table media_asset
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table media_asset
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public mediaAssetExample() {
		oredCriteria = new ArrayList<Criteria>();
		page = new Page();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table media_asset
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andMediaTypeIsNull() {
			addCriterion("media_type is null");
			return (Criteria) this;
		}

		public Criteria andMediaTypeIsNotNull() {
			addCriterion("media_type is not null");
			return (Criteria) this;
		}

		public Criteria andMediaTypeEqualTo(Integer value) {
			addCriterion("media_type =", value, "mediaType");
			return (Criteria) this;
		}

		public Criteria andMediaTypeNotEqualTo(Integer value) {
			addCriterion("media_type <>", value, "mediaType");
			return (Criteria) this;
		}

		public Criteria andMediaTypeGreaterThan(Integer value) {
			addCriterion("media_type >", value, "mediaType");
			return (Criteria) this;
		}

		public Criteria andMediaTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("media_type >=", value, "mediaType");
			return (Criteria) this;
		}

		public Criteria andMediaTypeLessThan(Integer value) {
			addCriterion("media_type <", value, "mediaType");
			return (Criteria) this;
		}

		public Criteria andMediaTypeLessThanOrEqualTo(Integer value) {
			addCriterion("media_type <=", value, "mediaType");
			return (Criteria) this;
		}

		public Criteria andMediaTypeIn(List<Integer> values) {
			addCriterion("media_type in", values, "mediaType");
			return (Criteria) this;
		}

		public Criteria andMediaTypeNotIn(List<Integer> values) {
			addCriterion("media_type not in", values, "mediaType");
			return (Criteria) this;
		}

		public Criteria andMediaTypeBetween(Integer value1, Integer value2) {
			addCriterion("media_type between", value1, value2, "mediaType");
			return (Criteria) this;
		}

		public Criteria andMediaTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("media_type not between", value1, value2, "mediaType");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedIsNull() {
			addCriterion("media_id_related is null");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedIsNotNull() {
			addCriterion("media_id_related is not null");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedEqualTo(String value) {
			addCriterion("media_id_related =", value, "mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedNotEqualTo(String value) {
			addCriterion("media_id_related <>", value, "mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedGreaterThan(String value) {
			addCriterion("media_id_related >", value, "mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedGreaterThanOrEqualTo(String value) {
			addCriterion("media_id_related >=", value, "mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedLessThan(String value) {
			addCriterion("media_id_related <", value, "mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedLessThanOrEqualTo(String value) {
			addCriterion("media_id_related <=", value, "mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedLike(String value) {
			addCriterion("media_id_related like", value, "mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedNotLike(String value) {
			addCriterion("media_id_related not like", value, "mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedIn(List<String> values) {
			addCriterion("media_id_related in", values, "mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedNotIn(List<String> values) {
			addCriterion("media_id_related not in", values, "mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedBetween(String value1, String value2) {
			addCriterion("media_id_related between", value1, value2,
					"mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaIdRelatedNotBetween(String value1, String value2) {
			addCriterion("media_id_related not between", value1, value2,
					"mediaIdRelated");
			return (Criteria) this;
		}

		public Criteria andMediaStatusIsNull() {
			addCriterion("media_status is null");
			return (Criteria) this;
		}

		public Criteria andMediaStatusIsNotNull() {
			addCriterion("media_status is not null");
			return (Criteria) this;
		}

		public Criteria andMediaStatusEqualTo(Integer value) {
			addCriterion("media_status =", value, "mediaStatus");
			return (Criteria) this;
		}

		public Criteria andMediaStatusNotEqualTo(Integer value) {
			addCriterion("media_status <>", value, "mediaStatus");
			return (Criteria) this;
		}

		public Criteria andMediaStatusGreaterThan(Integer value) {
			addCriterion("media_status >", value, "mediaStatus");
			return (Criteria) this;
		}

		public Criteria andMediaStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("media_status >=", value, "mediaStatus");
			return (Criteria) this;
		}

		public Criteria andMediaStatusLessThan(Integer value) {
			addCriterion("media_status <", value, "mediaStatus");
			return (Criteria) this;
		}

		public Criteria andMediaStatusLessThanOrEqualTo(Integer value) {
			addCriterion("media_status <=", value, "mediaStatus");
			return (Criteria) this;
		}

		public Criteria andMediaStatusIn(List<Integer> values) {
			addCriterion("media_status in", values, "mediaStatus");
			return (Criteria) this;
		}

		public Criteria andMediaStatusNotIn(List<Integer> values) {
			addCriterion("media_status not in", values, "mediaStatus");
			return (Criteria) this;
		}

		public Criteria andMediaStatusBetween(Integer value1, Integer value2) {
			addCriterion("media_status between", value1, value2, "mediaStatus");
			return (Criteria) this;
		}

		public Criteria andMediaStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("media_status not between", value1, value2,
					"mediaStatus");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andAliasIsNull() {
			addCriterion("alias is null");
			return (Criteria) this;
		}

		public Criteria andAliasIsNotNull() {
			addCriterion("alias is not null");
			return (Criteria) this;
		}

		public Criteria andAliasEqualTo(String value) {
			addCriterion("alias =", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotEqualTo(String value) {
			addCriterion("alias <>", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasGreaterThan(String value) {
			addCriterion("alias >", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasGreaterThanOrEqualTo(String value) {
			addCriterion("alias >=", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLessThan(String value) {
			addCriterion("alias <", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLessThanOrEqualTo(String value) {
			addCriterion("alias <=", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLike(String value) {
			addCriterion("alias like", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotLike(String value) {
			addCriterion("alias not like", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasIn(List<String> values) {
			addCriterion("alias in", values, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotIn(List<String> values) {
			addCriterion("alias not in", values, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasBetween(String value1, String value2) {
			addCriterion("alias between", value1, value2, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotBetween(String value1, String value2) {
			addCriterion("alias not between", value1, value2, "alias");
			return (Criteria) this;
		}

		public Criteria andEnglishNameIsNull() {
			addCriterion("english_name is null");
			return (Criteria) this;
		}

		public Criteria andEnglishNameIsNotNull() {
			addCriterion("english_name is not null");
			return (Criteria) this;
		}

		public Criteria andEnglishNameEqualTo(String value) {
			addCriterion("english_name =", value, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameNotEqualTo(String value) {
			addCriterion("english_name <>", value, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameGreaterThan(String value) {
			addCriterion("english_name >", value, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameGreaterThanOrEqualTo(String value) {
			addCriterion("english_name >=", value, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameLessThan(String value) {
			addCriterion("english_name <", value, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameLessThanOrEqualTo(String value) {
			addCriterion("english_name <=", value, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameLike(String value) {
			addCriterion("english_name like", value, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameNotLike(String value) {
			addCriterion("english_name not like", value, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameIn(List<String> values) {
			addCriterion("english_name in", values, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameNotIn(List<String> values) {
			addCriterion("english_name not in", values, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameBetween(String value1, String value2) {
			addCriterion("english_name between", value1, value2, "englishName");
			return (Criteria) this;
		}

		public Criteria andEnglishNameNotBetween(String value1, String value2) {
			addCriterion("english_name not between", value1, value2,
					"englishName");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andSubtitleIsNull() {
			addCriterion("subtitle is null");
			return (Criteria) this;
		}

		public Criteria andSubtitleIsNotNull() {
			addCriterion("subtitle is not null");
			return (Criteria) this;
		}

		public Criteria andSubtitleEqualTo(String value) {
			addCriterion("subtitle =", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleNotEqualTo(String value) {
			addCriterion("subtitle <>", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleGreaterThan(String value) {
			addCriterion("subtitle >", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleGreaterThanOrEqualTo(String value) {
			addCriterion("subtitle >=", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleLessThan(String value) {
			addCriterion("subtitle <", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleLessThanOrEqualTo(String value) {
			addCriterion("subtitle <=", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleLike(String value) {
			addCriterion("subtitle like", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleNotLike(String value) {
			addCriterion("subtitle not like", value, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleIn(List<String> values) {
			addCriterion("subtitle in", values, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleNotIn(List<String> values) {
			addCriterion("subtitle not in", values, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleBetween(String value1, String value2) {
			addCriterion("subtitle between", value1, value2, "subtitle");
			return (Criteria) this;
		}

		public Criteria andSubtitleNotBetween(String value1, String value2) {
			addCriterion("subtitle not between", value1, value2, "subtitle");
			return (Criteria) this;
		}

		public Criteria andBriefIsNull() {
			addCriterion("brief is null");
			return (Criteria) this;
		}

		public Criteria andBriefIsNotNull() {
			addCriterion("brief is not null");
			return (Criteria) this;
		}

		public Criteria andBriefEqualTo(String value) {
			addCriterion("brief =", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotEqualTo(String value) {
			addCriterion("brief <>", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefGreaterThan(String value) {
			addCriterion("brief >", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefGreaterThanOrEqualTo(String value) {
			addCriterion("brief >=", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefLessThan(String value) {
			addCriterion("brief <", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefLessThanOrEqualTo(String value) {
			addCriterion("brief <=", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefLike(String value) {
			addCriterion("brief like", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotLike(String value) {
			addCriterion("brief not like", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefIn(List<String> values) {
			addCriterion("brief in", values, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotIn(List<String> values) {
			addCriterion("brief not in", values, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefBetween(String value1, String value2) {
			addCriterion("brief between", value1, value2, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotBetween(String value1, String value2) {
			addCriterion("brief not between", value1, value2, "brief");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNull() {
			addCriterion("keyword is null");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNotNull() {
			addCriterion("keyword is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordEqualTo(String value) {
			addCriterion("keyword =", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotEqualTo(String value) {
			addCriterion("keyword <>", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThan(String value) {
			addCriterion("keyword >", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThanOrEqualTo(String value) {
			addCriterion("keyword >=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThan(String value) {
			addCriterion("keyword <", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThanOrEqualTo(String value) {
			addCriterion("keyword <=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLike(String value) {
			addCriterion("keyword like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotLike(String value) {
			addCriterion("keyword not like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordIn(List<String> values) {
			addCriterion("keyword in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotIn(List<String> values) {
			addCriterion("keyword not in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordBetween(String value1, String value2) {
			addCriterion("keyword between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotBetween(String value1, String value2) {
			addCriterion("keyword not between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andDirectorIsNull() {
			addCriterion("director is null");
			return (Criteria) this;
		}

		public Criteria andDirectorIsNotNull() {
			addCriterion("director is not null");
			return (Criteria) this;
		}

		public Criteria andDirectorEqualTo(String value) {
			addCriterion("director =", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotEqualTo(String value) {
			addCriterion("director <>", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorGreaterThan(String value) {
			addCriterion("director >", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorGreaterThanOrEqualTo(String value) {
			addCriterion("director >=", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorLessThan(String value) {
			addCriterion("director <", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorLessThanOrEqualTo(String value) {
			addCriterion("director <=", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorLike(String value) {
			addCriterion("director like", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotLike(String value) {
			addCriterion("director not like", value, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorIn(List<String> values) {
			addCriterion("director in", values, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotIn(List<String> values) {
			addCriterion("director not in", values, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorBetween(String value1, String value2) {
			addCriterion("director between", value1, value2, "director");
			return (Criteria) this;
		}

		public Criteria andDirectorNotBetween(String value1, String value2) {
			addCriterion("director not between", value1, value2, "director");
			return (Criteria) this;
		}

		public Criteria andActorIsNull() {
			addCriterion("actor is null");
			return (Criteria) this;
		}

		public Criteria andActorIsNotNull() {
			addCriterion("actor is not null");
			return (Criteria) this;
		}

		public Criteria andActorEqualTo(String value) {
			addCriterion("actor =", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorNotEqualTo(String value) {
			addCriterion("actor <>", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorGreaterThan(String value) {
			addCriterion("actor >", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorGreaterThanOrEqualTo(String value) {
			addCriterion("actor >=", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorLessThan(String value) {
			addCriterion("actor <", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorLessThanOrEqualTo(String value) {
			addCriterion("actor <=", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorLike(String value) {
			addCriterion("actor like", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorNotLike(String value) {
			addCriterion("actor not like", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorIn(List<String> values) {
			addCriterion("actor in", values, "actor");
			return (Criteria) this;
		}

		public Criteria andActorNotIn(List<String> values) {
			addCriterion("actor not in", values, "actor");
			return (Criteria) this;
		}

		public Criteria andActorBetween(String value1, String value2) {
			addCriterion("actor between", value1, value2, "actor");
			return (Criteria) this;
		}

		public Criteria andActorNotBetween(String value1, String value2) {
			addCriterion("actor not between", value1, value2, "actor");
			return (Criteria) this;
		}

		public Criteria andWriterIsNull() {
			addCriterion("writer is null");
			return (Criteria) this;
		}

		public Criteria andWriterIsNotNull() {
			addCriterion("writer is not null");
			return (Criteria) this;
		}

		public Criteria andWriterEqualTo(String value) {
			addCriterion("writer =", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterNotEqualTo(String value) {
			addCriterion("writer <>", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterGreaterThan(String value) {
			addCriterion("writer >", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterGreaterThanOrEqualTo(String value) {
			addCriterion("writer >=", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterLessThan(String value) {
			addCriterion("writer <", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterLessThanOrEqualTo(String value) {
			addCriterion("writer <=", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterLike(String value) {
			addCriterion("writer like", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterNotLike(String value) {
			addCriterion("writer not like", value, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterIn(List<String> values) {
			addCriterion("writer in", values, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterNotIn(List<String> values) {
			addCriterion("writer not in", values, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterBetween(String value1, String value2) {
			addCriterion("writer between", value1, value2, "writer");
			return (Criteria) this;
		}

		public Criteria andWriterNotBetween(String value1, String value2) {
			addCriterion("writer not between", value1, value2, "writer");
			return (Criteria) this;
		}

		public Criteria andProducerIsNull() {
			addCriterion("producer is null");
			return (Criteria) this;
		}

		public Criteria andProducerIsNotNull() {
			addCriterion("producer is not null");
			return (Criteria) this;
		}

		public Criteria andProducerEqualTo(String value) {
			addCriterion("producer =", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotEqualTo(String value) {
			addCriterion("producer <>", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerGreaterThan(String value) {
			addCriterion("producer >", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerGreaterThanOrEqualTo(String value) {
			addCriterion("producer >=", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerLessThan(String value) {
			addCriterion("producer <", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerLessThanOrEqualTo(String value) {
			addCriterion("producer <=", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerLike(String value) {
			addCriterion("producer like", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotLike(String value) {
			addCriterion("producer not like", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerIn(List<String> values) {
			addCriterion("producer in", values, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotIn(List<String> values) {
			addCriterion("producer not in", values, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerBetween(String value1, String value2) {
			addCriterion("producer between", value1, value2, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotBetween(String value1, String value2) {
			addCriterion("producer not between", value1, value2, "producer");
			return (Criteria) this;
		}

		public Criteria andShowyearIsNull() {
			addCriterion("showyear is null");
			return (Criteria) this;
		}

		public Criteria andShowyearIsNotNull() {
			addCriterion("showyear is not null");
			return (Criteria) this;
		}

		public Criteria andShowyearEqualTo(Integer value) {
			addCriterion("showyear =", value, "showyear");
			return (Criteria) this;
		}

		public Criteria andShowyearNotEqualTo(Integer value) {
			addCriterion("showyear <>", value, "showyear");
			return (Criteria) this;
		}

		public Criteria andShowyearGreaterThan(Integer value) {
			addCriterion("showyear >", value, "showyear");
			return (Criteria) this;
		}

		public Criteria andShowyearGreaterThanOrEqualTo(Integer value) {
			addCriterion("showyear >=", value, "showyear");
			return (Criteria) this;
		}

		public Criteria andShowyearLessThan(Integer value) {
			addCriterion("showyear <", value, "showyear");
			return (Criteria) this;
		}

		public Criteria andShowyearLessThanOrEqualTo(Integer value) {
			addCriterion("showyear <=", value, "showyear");
			return (Criteria) this;
		}

		public Criteria andShowyearIn(List<Integer> values) {
			addCriterion("showyear in", values, "showyear");
			return (Criteria) this;
		}

		public Criteria andShowyearNotIn(List<Integer> values) {
			addCriterion("showyear not in", values, "showyear");
			return (Criteria) this;
		}

		public Criteria andShowyearBetween(Integer value1, Integer value2) {
			addCriterion("showyear between", value1, value2, "showyear");
			return (Criteria) this;
		}

		public Criteria andShowyearNotBetween(Integer value1, Integer value2) {
			addCriterion("showyear not between", value1, value2, "showyear");
			return (Criteria) this;
		}

		public Criteria andShowtimeIsNull() {
			addCriterion("showtime is null");
			return (Criteria) this;
		}

		public Criteria andShowtimeIsNotNull() {
			addCriterion("showtime is not null");
			return (Criteria) this;
		}

		public Criteria andShowtimeEqualTo(Date value) {
			addCriterion("showtime =", value, "showtime");
			return (Criteria) this;
		}

		public Criteria andShowtimeNotEqualTo(Date value) {
			addCriterion("showtime <>", value, "showtime");
			return (Criteria) this;
		}

		public Criteria andShowtimeGreaterThan(Date value) {
			addCriterion("showtime >", value, "showtime");
			return (Criteria) this;
		}

		public Criteria andShowtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("showtime >=", value, "showtime");
			return (Criteria) this;
		}

		public Criteria andShowtimeLessThan(Date value) {
			addCriterion("showtime <", value, "showtime");
			return (Criteria) this;
		}

		public Criteria andShowtimeLessThanOrEqualTo(Date value) {
			addCriterion("showtime <=", value, "showtime");
			return (Criteria) this;
		}

		public Criteria andShowtimeIn(List<Date> values) {
			addCriterion("showtime in", values, "showtime");
			return (Criteria) this;
		}

		public Criteria andShowtimeNotIn(List<Date> values) {
			addCriterion("showtime not in", values, "showtime");
			return (Criteria) this;
		}

		public Criteria andShowtimeBetween(Date value1, Date value2) {
			addCriterion("showtime between", value1, value2, "showtime");
			return (Criteria) this;
		}

		public Criteria andShowtimeNotBetween(Date value1, Date value2) {
			addCriterion("showtime not between", value1, value2, "showtime");
			return (Criteria) this;
		}

		public Criteria andDurationIsNull() {
			addCriterion("duration is null");
			return (Criteria) this;
		}

		public Criteria andDurationIsNotNull() {
			addCriterion("duration is not null");
			return (Criteria) this;
		}

		public Criteria andDurationEqualTo(Integer value) {
			addCriterion("duration =", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotEqualTo(Integer value) {
			addCriterion("duration <>", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationGreaterThan(Integer value) {
			addCriterion("duration >", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
			addCriterion("duration >=", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLessThan(Integer value) {
			addCriterion("duration <", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLessThanOrEqualTo(Integer value) {
			addCriterion("duration <=", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationIn(List<Integer> values) {
			addCriterion("duration in", values, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotIn(List<Integer> values) {
			addCriterion("duration not in", values, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationBetween(Integer value1, Integer value2) {
			addCriterion("duration between", value1, value2, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotBetween(Integer value1, Integer value2) {
			addCriterion("duration not between", value1, value2, "duration");
			return (Criteria) this;
		}

		public Criteria andMovieAreaIsNull() {
			addCriterion("movie_area is null");
			return (Criteria) this;
		}

		public Criteria andMovieAreaIsNotNull() {
			addCriterion("movie_area is not null");
			return (Criteria) this;
		}

		public Criteria andMovieAreaEqualTo(String value) {
			addCriterion("movie_area =", value, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaNotEqualTo(String value) {
			addCriterion("movie_area <>", value, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaGreaterThan(String value) {
			addCriterion("movie_area >", value, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaGreaterThanOrEqualTo(String value) {
			addCriterion("movie_area >=", value, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaLessThan(String value) {
			addCriterion("movie_area <", value, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaLessThanOrEqualTo(String value) {
			addCriterion("movie_area <=", value, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaLike(String value) {
			addCriterion("movie_area like", value, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaNotLike(String value) {
			addCriterion("movie_area not like", value, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaIn(List<String> values) {
			addCriterion("movie_area in", values, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaNotIn(List<String> values) {
			addCriterion("movie_area not in", values, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaBetween(String value1, String value2) {
			addCriterion("movie_area between", value1, value2, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieAreaNotBetween(String value1, String value2) {
			addCriterion("movie_area not between", value1, value2, "movieArea");
			return (Criteria) this;
		}

		public Criteria andMovieTypeIsNull() {
			addCriterion("movie_type is null");
			return (Criteria) this;
		}

		public Criteria andMovieTypeIsNotNull() {
			addCriterion("movie_type is not null");
			return (Criteria) this;
		}

		public Criteria andMovieTypeEqualTo(String value) {
			addCriterion("movie_type =", value, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeNotEqualTo(String value) {
			addCriterion("movie_type <>", value, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeGreaterThan(String value) {
			addCriterion("movie_type >", value, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeGreaterThanOrEqualTo(String value) {
			addCriterion("movie_type >=", value, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeLessThan(String value) {
			addCriterion("movie_type <", value, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeLessThanOrEqualTo(String value) {
			addCriterion("movie_type <=", value, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeLike(String value) {
			addCriterion("movie_type like", value, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeNotLike(String value) {
			addCriterion("movie_type not like", value, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeIn(List<String> values) {
			addCriterion("movie_type in", values, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeNotIn(List<String> values) {
			addCriterion("movie_type not in", values, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeBetween(String value1, String value2) {
			addCriterion("movie_type between", value1, value2, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieTypeNotBetween(String value1, String value2) {
			addCriterion("movie_type not between", value1, value2, "movieType");
			return (Criteria) this;
		}

		public Criteria andMovieLevelIsNull() {
			addCriterion("movie_level is null");
			return (Criteria) this;
		}

		public Criteria andMovieLevelIsNotNull() {
			addCriterion("movie_level is not null");
			return (Criteria) this;
		}

		public Criteria andMovieLevelEqualTo(Integer value) {
			addCriterion("movie_level =", value, "movieLevel");
			return (Criteria) this;
		}

		public Criteria andMovieLevelNotEqualTo(Integer value) {
			addCriterion("movie_level <>", value, "movieLevel");
			return (Criteria) this;
		}

		public Criteria andMovieLevelGreaterThan(Integer value) {
			addCriterion("movie_level >", value, "movieLevel");
			return (Criteria) this;
		}

		public Criteria andMovieLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("movie_level >=", value, "movieLevel");
			return (Criteria) this;
		}

		public Criteria andMovieLevelLessThan(Integer value) {
			addCriterion("movie_level <", value, "movieLevel");
			return (Criteria) this;
		}

		public Criteria andMovieLevelLessThanOrEqualTo(Integer value) {
			addCriterion("movie_level <=", value, "movieLevel");
			return (Criteria) this;
		}

		public Criteria andMovieLevelIn(List<Integer> values) {
			addCriterion("movie_level in", values, "movieLevel");
			return (Criteria) this;
		}

		public Criteria andMovieLevelNotIn(List<Integer> values) {
			addCriterion("movie_level not in", values, "movieLevel");
			return (Criteria) this;
		}

		public Criteria andMovieLevelBetween(Integer value1, Integer value2) {
			addCriterion("movie_level between", value1, value2, "movieLevel");
			return (Criteria) this;
		}

		public Criteria andMovieLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("movie_level not between", value1, value2,
					"movieLevel");
			return (Criteria) this;
		}

		public Criteria andImageHBannerIsNull() {
			addCriterion("image_h_banner is null");
			return (Criteria) this;
		}

		public Criteria andImageHBannerIsNotNull() {
			addCriterion("image_h_banner is not null");
			return (Criteria) this;
		}

		public Criteria andImageHBannerEqualTo(String value) {
			addCriterion("image_h_banner =", value, "imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerNotEqualTo(String value) {
			addCriterion("image_h_banner <>", value, "imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerGreaterThan(String value) {
			addCriterion("image_h_banner >", value, "imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerGreaterThanOrEqualTo(String value) {
			addCriterion("image_h_banner >=", value, "imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerLessThan(String value) {
			addCriterion("image_h_banner <", value, "imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerLessThanOrEqualTo(String value) {
			addCriterion("image_h_banner <=", value, "imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerLike(String value) {
			addCriterion("image_h_banner like", value, "imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerNotLike(String value) {
			addCriterion("image_h_banner not like", value, "imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerIn(List<String> values) {
			addCriterion("image_h_banner in", values, "imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerNotIn(List<String> values) {
			addCriterion("image_h_banner not in", values, "imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerBetween(String value1, String value2) {
			addCriterion("image_h_banner between", value1, value2,
					"imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHBannerNotBetween(String value1, String value2) {
			addCriterion("image_h_banner not between", value1, value2,
					"imageHBanner");
			return (Criteria) this;
		}

		public Criteria andImageHSmallIsNull() {
			addCriterion("image_h_small is null");
			return (Criteria) this;
		}

		public Criteria andImageHSmallIsNotNull() {
			addCriterion("image_h_small is not null");
			return (Criteria) this;
		}

		public Criteria andImageHSmallEqualTo(String value) {
			addCriterion("image_h_small =", value, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallNotEqualTo(String value) {
			addCriterion("image_h_small <>", value, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallGreaterThan(String value) {
			addCriterion("image_h_small >", value, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallGreaterThanOrEqualTo(String value) {
			addCriterion("image_h_small >=", value, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallLessThan(String value) {
			addCriterion("image_h_small <", value, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallLessThanOrEqualTo(String value) {
			addCriterion("image_h_small <=", value, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallLike(String value) {
			addCriterion("image_h_small like", value, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallNotLike(String value) {
			addCriterion("image_h_small not like", value, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallIn(List<String> values) {
			addCriterion("image_h_small in", values, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallNotIn(List<String> values) {
			addCriterion("image_h_small not in", values, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallBetween(String value1, String value2) {
			addCriterion("image_h_small between", value1, value2, "imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageHSmallNotBetween(String value1, String value2) {
			addCriterion("image_h_small not between", value1, value2,
					"imageHSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallIsNull() {
			addCriterion("image_v_small is null");
			return (Criteria) this;
		}

		public Criteria andImageVSmallIsNotNull() {
			addCriterion("image_v_small is not null");
			return (Criteria) this;
		}

		public Criteria andImageVSmallEqualTo(String value) {
			addCriterion("image_v_small =", value, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallNotEqualTo(String value) {
			addCriterion("image_v_small <>", value, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallGreaterThan(String value) {
			addCriterion("image_v_small >", value, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallGreaterThanOrEqualTo(String value) {
			addCriterion("image_v_small >=", value, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallLessThan(String value) {
			addCriterion("image_v_small <", value, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallLessThanOrEqualTo(String value) {
			addCriterion("image_v_small <=", value, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallLike(String value) {
			addCriterion("image_v_small like", value, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallNotLike(String value) {
			addCriterion("image_v_small not like", value, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallIn(List<String> values) {
			addCriterion("image_v_small in", values, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallNotIn(List<String> values) {
			addCriterion("image_v_small not in", values, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallBetween(String value1, String value2) {
			addCriterion("image_v_small between", value1, value2, "imageVSmall");
			return (Criteria) this;
		}

		public Criteria andImageVSmallNotBetween(String value1, String value2) {
			addCriterion("image_v_small not between", value1, value2,
					"imageVSmall");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowIsNull() {
			addCriterion("video_play_url_low is null");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowIsNotNull() {
			addCriterion("video_play_url_low is not null");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowEqualTo(String value) {
			addCriterion("video_play_url_low =", value, "videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowNotEqualTo(String value) {
			addCriterion("video_play_url_low <>", value, "videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowGreaterThan(String value) {
			addCriterion("video_play_url_low >", value, "videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowGreaterThanOrEqualTo(String value) {
			addCriterion("video_play_url_low >=", value, "videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowLessThan(String value) {
			addCriterion("video_play_url_low <", value, "videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowLessThanOrEqualTo(String value) {
			addCriterion("video_play_url_low <=", value, "videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowLike(String value) {
			addCriterion("video_play_url_low like", value, "videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowNotLike(String value) {
			addCriterion("video_play_url_low not like", value,
					"videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowIn(List<String> values) {
			addCriterion("video_play_url_low in", values, "videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowNotIn(List<String> values) {
			addCriterion("video_play_url_low not in", values, "videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowBetween(String value1, String value2) {
			addCriterion("video_play_url_low between", value1, value2,
					"videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlLowNotBetween(String value1,
				String value2) {
			addCriterion("video_play_url_low not between", value1, value2,
					"videoPlayUrlLow");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdIsNull() {
			addCriterion("video_play_url_sd is null");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdIsNotNull() {
			addCriterion("video_play_url_sd is not null");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdEqualTo(String value) {
			addCriterion("video_play_url_sd =", value, "videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdNotEqualTo(String value) {
			addCriterion("video_play_url_sd <>", value, "videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdGreaterThan(String value) {
			addCriterion("video_play_url_sd >", value, "videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdGreaterThanOrEqualTo(String value) {
			addCriterion("video_play_url_sd >=", value, "videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdLessThan(String value) {
			addCriterion("video_play_url_sd <", value, "videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdLessThanOrEqualTo(String value) {
			addCriterion("video_play_url_sd <=", value, "videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdLike(String value) {
			addCriterion("video_play_url_sd like", value, "videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdNotLike(String value) {
			addCriterion("video_play_url_sd not like", value, "videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdIn(List<String> values) {
			addCriterion("video_play_url_sd in", values, "videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdNotIn(List<String> values) {
			addCriterion("video_play_url_sd not in", values, "videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdBetween(String value1, String value2) {
			addCriterion("video_play_url_sd between", value1, value2,
					"videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlSdNotBetween(String value1, String value2) {
			addCriterion("video_play_url_sd not between", value1, value2,
					"videoPlayUrlSd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdIsNull() {
			addCriterion("video_play_url_hd is null");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdIsNotNull() {
			addCriterion("video_play_url_hd is not null");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdEqualTo(String value) {
			addCriterion("video_play_url_hd =", value, "videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdNotEqualTo(String value) {
			addCriterion("video_play_url_hd <>", value, "videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdGreaterThan(String value) {
			addCriterion("video_play_url_hd >", value, "videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdGreaterThanOrEqualTo(String value) {
			addCriterion("video_play_url_hd >=", value, "videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdLessThan(String value) {
			addCriterion("video_play_url_hd <", value, "videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdLessThanOrEqualTo(String value) {
			addCriterion("video_play_url_hd <=", value, "videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdLike(String value) {
			addCriterion("video_play_url_hd like", value, "videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdNotLike(String value) {
			addCriterion("video_play_url_hd not like", value, "videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdIn(List<String> values) {
			addCriterion("video_play_url_hd in", values, "videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdNotIn(List<String> values) {
			addCriterion("video_play_url_hd not in", values, "videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdBetween(String value1, String value2) {
			addCriterion("video_play_url_hd between", value1, value2,
					"videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlHdNotBetween(String value1, String value2) {
			addCriterion("video_play_url_hd not between", value1, value2,
					"videoPlayUrlHd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdIsNull() {
			addCriterion("video_play_url_uhd is null");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdIsNotNull() {
			addCriterion("video_play_url_uhd is not null");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdEqualTo(String value) {
			addCriterion("video_play_url_uhd =", value, "videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdNotEqualTo(String value) {
			addCriterion("video_play_url_uhd <>", value, "videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdGreaterThan(String value) {
			addCriterion("video_play_url_uhd >", value, "videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdGreaterThanOrEqualTo(String value) {
			addCriterion("video_play_url_uhd >=", value, "videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdLessThan(String value) {
			addCriterion("video_play_url_uhd <", value, "videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdLessThanOrEqualTo(String value) {
			addCriterion("video_play_url_uhd <=", value, "videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdLike(String value) {
			addCriterion("video_play_url_uhd like", value, "videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdNotLike(String value) {
			addCriterion("video_play_url_uhd not like", value,
					"videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdIn(List<String> values) {
			addCriterion("video_play_url_uhd in", values, "videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdNotIn(List<String> values) {
			addCriterion("video_play_url_uhd not in", values, "videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdBetween(String value1, String value2) {
			addCriterion("video_play_url_uhd between", value1, value2,
					"videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andVideoPlayUrlUhdNotBetween(String value1,
				String value2) {
			addCriterion("video_play_url_uhd not between", value1, value2,
					"videoPlayUrlUhd");
			return (Criteria) this;
		}

		public Criteria andCopyrightIsNull() {
			addCriterion("copyright is null");
			return (Criteria) this;
		}

		public Criteria andCopyrightIsNotNull() {
			addCriterion("copyright is not null");
			return (Criteria) this;
		}

		public Criteria andCopyrightEqualTo(Integer value) {
			addCriterion("copyright =", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightNotEqualTo(Integer value) {
			addCriterion("copyright <>", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightGreaterThan(Integer value) {
			addCriterion("copyright >", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightGreaterThanOrEqualTo(Integer value) {
			addCriterion("copyright >=", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightLessThan(Integer value) {
			addCriterion("copyright <", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightLessThanOrEqualTo(Integer value) {
			addCriterion("copyright <=", value, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightIn(List<Integer> values) {
			addCriterion("copyright in", values, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightNotIn(List<Integer> values) {
			addCriterion("copyright not in", values, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightBetween(Integer value1, Integer value2) {
			addCriterion("copyright between", value1, value2, "copyright");
			return (Criteria) this;
		}

		public Criteria andCopyrightNotBetween(Integer value1, Integer value2) {
			addCriterion("copyright not between", value1, value2, "copyright");
			return (Criteria) this;
		}

		public Criteria andProgramSourceIsNull() {
			addCriterion("program_source is null");
			return (Criteria) this;
		}

		public Criteria andProgramSourceIsNotNull() {
			addCriterion("program_source is not null");
			return (Criteria) this;
		}

		public Criteria andProgramSourceEqualTo(String value) {
			addCriterion("program_source =", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceNotEqualTo(String value) {
			addCriterion("program_source <>", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceGreaterThan(String value) {
			addCriterion("program_source >", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceGreaterThanOrEqualTo(String value) {
			addCriterion("program_source >=", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceLessThan(String value) {
			addCriterion("program_source <", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceLessThanOrEqualTo(String value) {
			addCriterion("program_source <=", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceLike(String value) {
			addCriterion("program_source like", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceNotLike(String value) {
			addCriterion("program_source not like", value, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceIn(List<String> values) {
			addCriterion("program_source in", values, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceNotIn(List<String> values) {
			addCriterion("program_source not in", values, "programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceBetween(String value1, String value2) {
			addCriterion("program_source between", value1, value2,
					"programSource");
			return (Criteria) this;
		}

		public Criteria andProgramSourceNotBetween(String value1, String value2) {
			addCriterion("program_source not between", value1, value2,
					"programSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceIsNull() {
			addCriterion("copyright_source is null");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceIsNotNull() {
			addCriterion("copyright_source is not null");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceEqualTo(String value) {
			addCriterion("copyright_source =", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceNotEqualTo(String value) {
			addCriterion("copyright_source <>", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceGreaterThan(String value) {
			addCriterion("copyright_source >", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceGreaterThanOrEqualTo(String value) {
			addCriterion("copyright_source >=", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceLessThan(String value) {
			addCriterion("copyright_source <", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceLessThanOrEqualTo(String value) {
			addCriterion("copyright_source <=", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceLike(String value) {
			addCriterion("copyright_source like", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceNotLike(String value) {
			addCriterion("copyright_source not like", value, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceIn(List<String> values) {
			addCriterion("copyright_source in", values, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceNotIn(List<String> values) {
			addCriterion("copyright_source not in", values, "copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceBetween(String value1, String value2) {
			addCriterion("copyright_source between", value1, value2,
					"copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightSourceNotBetween(String value1,
				String value2) {
			addCriterion("copyright_source not between", value1, value2,
					"copyrightSource");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateIsNull() {
			addCriterion("copyright_begindate is null");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateIsNotNull() {
			addCriterion("copyright_begindate is not null");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateEqualTo(Date value) {
			addCriterion("copyright_begindate =", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateNotEqualTo(Date value) {
			addCriterion("copyright_begindate <>", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateGreaterThan(Date value) {
			addCriterion("copyright_begindate >", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateGreaterThanOrEqualTo(Date value) {
			addCriterion("copyright_begindate >=", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateLessThan(Date value) {
			addCriterion("copyright_begindate <", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateLessThanOrEqualTo(Date value) {
			addCriterion("copyright_begindate <=", value, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateIn(List<Date> values) {
			addCriterion("copyright_begindate in", values, "copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateNotIn(List<Date> values) {
			addCriterion("copyright_begindate not in", values,
					"copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateBetween(Date value1, Date value2) {
			addCriterion("copyright_begindate between", value1, value2,
					"copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightBegindateNotBetween(Date value1, Date value2) {
			addCriterion("copyright_begindate not between", value1, value2,
					"copyrightBegindate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateIsNull() {
			addCriterion("copyright_enddate is null");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateIsNotNull() {
			addCriterion("copyright_enddate is not null");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateEqualTo(Date value) {
			addCriterion("copyright_enddate =", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateNotEqualTo(Date value) {
			addCriterion("copyright_enddate <>", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateGreaterThan(Date value) {
			addCriterion("copyright_enddate >", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateGreaterThanOrEqualTo(Date value) {
			addCriterion("copyright_enddate >=", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateLessThan(Date value) {
			addCriterion("copyright_enddate <", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateLessThanOrEqualTo(Date value) {
			addCriterion("copyright_enddate <=", value, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateIn(List<Date> values) {
			addCriterion("copyright_enddate in", values, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateNotIn(List<Date> values) {
			addCriterion("copyright_enddate not in", values, "copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateBetween(Date value1, Date value2) {
			addCriterion("copyright_enddate between", value1, value2,
					"copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andCopyrightEnddateNotBetween(Date value1, Date value2) {
			addCriterion("copyright_enddate not between", value1, value2,
					"copyrightEnddate");
			return (Criteria) this;
		}

		public Criteria andChargeIsNull() {
			addCriterion("charge is null");
			return (Criteria) this;
		}

		public Criteria andChargeIsNotNull() {
			addCriterion("charge is not null");
			return (Criteria) this;
		}

		public Criteria andChargeEqualTo(Integer value) {
			addCriterion("charge =", value, "charge");
			return (Criteria) this;
		}

		public Criteria andChargeNotEqualTo(Integer value) {
			addCriterion("charge <>", value, "charge");
			return (Criteria) this;
		}

		public Criteria andChargeGreaterThan(Integer value) {
			addCriterion("charge >", value, "charge");
			return (Criteria) this;
		}

		public Criteria andChargeGreaterThanOrEqualTo(Integer value) {
			addCriterion("charge >=", value, "charge");
			return (Criteria) this;
		}

		public Criteria andChargeLessThan(Integer value) {
			addCriterion("charge <", value, "charge");
			return (Criteria) this;
		}

		public Criteria andChargeLessThanOrEqualTo(Integer value) {
			addCriterion("charge <=", value, "charge");
			return (Criteria) this;
		}

		public Criteria andChargeIn(List<Integer> values) {
			addCriterion("charge in", values, "charge");
			return (Criteria) this;
		}

		public Criteria andChargeNotIn(List<Integer> values) {
			addCriterion("charge not in", values, "charge");
			return (Criteria) this;
		}

		public Criteria andChargeBetween(Integer value1, Integer value2) {
			addCriterion("charge between", value1, value2, "charge");
			return (Criteria) this;
		}

		public Criteria andChargeNotBetween(Integer value1, Integer value2) {
			addCriterion("charge not between", value1, value2, "charge");
			return (Criteria) this;
		}

		public Criteria andWeightIsNull() {
			addCriterion("weight is null");
			return (Criteria) this;
		}

		public Criteria andWeightIsNotNull() {
			addCriterion("weight is not null");
			return (Criteria) this;
		}

		public Criteria andWeightEqualTo(Integer value) {
			addCriterion("weight =", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotEqualTo(Integer value) {
			addCriterion("weight <>", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThan(Integer value) {
			addCriterion("weight >", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("weight >=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThan(Integer value) {
			addCriterion("weight <", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThanOrEqualTo(Integer value) {
			addCriterion("weight <=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightIn(List<Integer> values) {
			addCriterion("weight in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotIn(List<Integer> values) {
			addCriterion("weight not in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightBetween(Integer value1, Integer value2) {
			addCriterion("weight between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotBetween(Integer value1, Integer value2) {
			addCriterion("weight not between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("creator is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("creator is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorEqualTo(String value) {
			addCriterion("creator =", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotEqualTo(String value) {
			addCriterion("creator <>", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThan(String value) {
			addCriterion("creator >", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(String value) {
			addCriterion("creator >=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThan(String value) {
			addCriterion("creator <", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThanOrEqualTo(String value) {
			addCriterion("creator <=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLike(String value) {
			addCriterion("creator like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotLike(String value) {
			addCriterion("creator not like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorIn(List<String> values) {
			addCriterion("creator in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotIn(List<String> values) {
			addCriterion("creator not in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorBetween(String value1, String value2) {
			addCriterion("creator between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotBetween(String value1, String value2) {
			addCriterion("creator not between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andAuditorIsNull() {
			addCriterion("auditor is null");
			return (Criteria) this;
		}

		public Criteria andAuditorIsNotNull() {
			addCriterion("auditor is not null");
			return (Criteria) this;
		}

		public Criteria andAuditorEqualTo(String value) {
			addCriterion("auditor =", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotEqualTo(String value) {
			addCriterion("auditor <>", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorGreaterThan(String value) {
			addCriterion("auditor >", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorGreaterThanOrEqualTo(String value) {
			addCriterion("auditor >=", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorLessThan(String value) {
			addCriterion("auditor <", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorLessThanOrEqualTo(String value) {
			addCriterion("auditor <=", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorLike(String value) {
			addCriterion("auditor like", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotLike(String value) {
			addCriterion("auditor not like", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorIn(List<String> values) {
			addCriterion("auditor in", values, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotIn(List<String> values) {
			addCriterion("auditor not in", values, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorBetween(String value1, String value2) {
			addCriterion("auditor between", value1, value2, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotBetween(String value1, String value2) {
			addCriterion("auditor not between", value1, value2, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditTimeIsNull() {
			addCriterion("audit_time is null");
			return (Criteria) this;
		}

		public Criteria andAuditTimeIsNotNull() {
			addCriterion("audit_time is not null");
			return (Criteria) this;
		}

		public Criteria andAuditTimeEqualTo(Date value) {
			addCriterion("audit_time =", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeNotEqualTo(Date value) {
			addCriterion("audit_time <>", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeGreaterThan(Date value) {
			addCriterion("audit_time >", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("audit_time >=", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeLessThan(Date value) {
			addCriterion("audit_time <", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
			addCriterion("audit_time <=", value, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeIn(List<Date> values) {
			addCriterion("audit_time in", values, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeNotIn(List<Date> values) {
			addCriterion("audit_time not in", values, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeBetween(Date value1, Date value2) {
			addCriterion("audit_time between", value1, value2, "auditTime");
			return (Criteria) this;
		}

		public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
			addCriterion("audit_time not between", value1, value2, "auditTime");
			return (Criteria) this;
		}

		public Criteria andMiguContentidIsNull() {
			addCriterion("migu_contentid is null");
			return (Criteria) this;
		}

		public Criteria andMiguContentidIsNotNull() {
			addCriterion("migu_contentid is not null");
			return (Criteria) this;
		}

		public Criteria andMiguContentidEqualTo(String value) {
			addCriterion("migu_contentid =", value, "miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidNotEqualTo(String value) {
			addCriterion("migu_contentid <>", value, "miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidGreaterThan(String value) {
			addCriterion("migu_contentid >", value, "miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidGreaterThanOrEqualTo(String value) {
			addCriterion("migu_contentid >=", value, "miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidLessThan(String value) {
			addCriterion("migu_contentid <", value, "miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidLessThanOrEqualTo(String value) {
			addCriterion("migu_contentid <=", value, "miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidLike(String value) {
			addCriterion("migu_contentid like", value, "miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidNotLike(String value) {
			addCriterion("migu_contentid not like", value, "miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidIn(List<String> values) {
			addCriterion("migu_contentid in", values, "miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidNotIn(List<String> values) {
			addCriterion("migu_contentid not in", values, "miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidBetween(String value1, String value2) {
			addCriterion("migu_contentid between", value1, value2,
					"miguContentid");
			return (Criteria) this;
		}

		public Criteria andMiguContentidNotBetween(String value1, String value2) {
			addCriterion("migu_contentid not between", value1, value2,
					"miguContentid");
			return (Criteria) this;
		}

		public Criteria andMaincategoryIsNull() {
			addCriterion("MAINCATEGORY is null");
			return (Criteria) this;
		}

		public Criteria andMaincategoryIsNotNull() {
			addCriterion("MAINCATEGORY is not null");
			return (Criteria) this;
		}

		public Criteria andMaincategoryEqualTo(String value) {
			addCriterion("MAINCATEGORY =", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryNotEqualTo(String value) {
			addCriterion("MAINCATEGORY <>", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryGreaterThan(String value) {
			addCriterion("MAINCATEGORY >", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryGreaterThanOrEqualTo(String value) {
			addCriterion("MAINCATEGORY >=", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryLessThan(String value) {
			addCriterion("MAINCATEGORY <", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryLessThanOrEqualTo(String value) {
			addCriterion("MAINCATEGORY <=", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryLike(String value) {
			addCriterion("MAINCATEGORY like", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryNotLike(String value) {
			addCriterion("MAINCATEGORY not like", value, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryIn(List<String> values) {
			addCriterion("MAINCATEGORY in", values, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryNotIn(List<String> values) {
			addCriterion("MAINCATEGORY not in", values, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryBetween(String value1, String value2) {
			addCriterion("MAINCATEGORY between", value1, value2, "maincategory");
			return (Criteria) this;
		}

		public Criteria andMaincategoryNotBetween(String value1, String value2) {
			addCriterion("MAINCATEGORY not between", value1, value2,
					"maincategory");
			return (Criteria) this;
		}

		public Criteria andCategorysIsNull() {
			addCriterion("categorys is null");
			return (Criteria) this;
		}

		public Criteria andCategorysIsNotNull() {
			addCriterion("categorys is not null");
			return (Criteria) this;
		}

		public Criteria andCategorysEqualTo(String value) {
			addCriterion("categorys =", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysNotEqualTo(String value) {
			addCriterion("categorys <>", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysGreaterThan(String value) {
			addCriterion("categorys >", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysGreaterThanOrEqualTo(String value) {
			addCriterion("categorys >=", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysLessThan(String value) {
			addCriterion("categorys <", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysLessThanOrEqualTo(String value) {
			addCriterion("categorys <=", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysLike(String value) {
			addCriterion("categorys like", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysNotLike(String value) {
			addCriterion("categorys not like", value, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysIn(List<String> values) {
			addCriterion("categorys in", values, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysNotIn(List<String> values) {
			addCriterion("categorys not in", values, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysBetween(String value1, String value2) {
			addCriterion("categorys between", value1, value2, "categorys");
			return (Criteria) this;
		}

		public Criteria andCategorysNotBetween(String value1, String value2) {
			addCriterion("categorys not between", value1, value2, "categorys");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table media_asset
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	protected Page page;
	public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table media_asset
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}