package com.cnLive.pojo;

import java.util.Date;

public class mediaAsset {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.media_type
	 * @mbggenerated
	 */
	private Integer mediaType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.media_id_related
	 * @mbggenerated
	 */
	private String mediaIdRelated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.media_status
	 * @mbggenerated
	 */
	private Integer mediaStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.alias
	 * @mbggenerated
	 */
	private String alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.english_name
	 * @mbggenerated
	 */
	private String englishName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.title
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.subtitle
	 * @mbggenerated
	 */
	private String subtitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.brief
	 * @mbggenerated
	 */
	private String brief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.keyword
	 * @mbggenerated
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.director
	 * @mbggenerated
	 */
	private String director;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.actor
	 * @mbggenerated
	 */
	private String actor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.writer
	 * @mbggenerated
	 */
	private String writer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.producer
	 * @mbggenerated
	 */
	private String producer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.showyear
	 * @mbggenerated
	 */
	private Integer showyear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.showtime
	 * @mbggenerated
	 */
	private Date showtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.duration
	 * @mbggenerated
	 */
	private Integer duration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.movie_area
	 * @mbggenerated
	 */
	private String movieArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.movie_type
	 * @mbggenerated
	 */
	private String movieType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.movie_level
	 * @mbggenerated
	 */
	private Integer movieLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.image_h_banner
	 * @mbggenerated
	 */
	private String imageHBanner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.image_h_small
	 * @mbggenerated
	 */
	private String imageHSmall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.image_v_small
	 * @mbggenerated
	 */
	private String imageVSmall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.video_play_url_low
	 * @mbggenerated
	 */
	private String videoPlayUrlLow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.video_play_url_sd
	 * @mbggenerated
	 */
	private String videoPlayUrlSd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.video_play_url_hd
	 * @mbggenerated
	 */
	private String videoPlayUrlHd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.video_play_url_uhd
	 * @mbggenerated
	 */
	private String videoPlayUrlUhd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.copyright
	 * @mbggenerated
	 */
	private Integer copyright;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.program_source
	 * @mbggenerated
	 */
	private String programSource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.copyright_source
	 * @mbggenerated
	 */
	private String copyrightSource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.copyright_begindate
	 * @mbggenerated
	 */
	private Date copyrightBegindate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.copyright_enddate
	 * @mbggenerated
	 */
	private Date copyrightEnddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.charge
	 * @mbggenerated
	 */
	private Integer charge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.weight
	 * @mbggenerated
	 */
	private Integer weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.creator
	 * @mbggenerated
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.auditor
	 * @mbggenerated
	 */
	private String auditor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.audit_time
	 * @mbggenerated
	 */
	private Date auditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.migu_contentid
	 * @mbggenerated
	 */
	private String miguContentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.MAINCATEGORY
	 * @mbggenerated
	 */
	private String maincategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media_asset.categorys
	 * @mbggenerated
	 */
	private String categorys;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.id
	 * @return  the value of media_asset.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.id
	 * @param id  the value for media_asset.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.media_type
	 * @return  the value of media_asset.media_type
	 * @mbggenerated
	 */
	public Integer getMediaType() {
		return mediaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.media_type
	 * @param mediaType  the value for media_asset.media_type
	 * @mbggenerated
	 */
	public void setMediaType(Integer mediaType) {
		this.mediaType = mediaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.media_id_related
	 * @return  the value of media_asset.media_id_related
	 * @mbggenerated
	 */
	public String getMediaIdRelated() {
		return mediaIdRelated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.media_id_related
	 * @param mediaIdRelated  the value for media_asset.media_id_related
	 * @mbggenerated
	 */
	public void setMediaIdRelated(String mediaIdRelated) {
		this.mediaIdRelated = mediaIdRelated == null ? null : mediaIdRelated
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.media_status
	 * @return  the value of media_asset.media_status
	 * @mbggenerated
	 */
	public Integer getMediaStatus() {
		return mediaStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.media_status
	 * @param mediaStatus  the value for media_asset.media_status
	 * @mbggenerated
	 */
	public void setMediaStatus(Integer mediaStatus) {
		this.mediaStatus = mediaStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.name
	 * @return  the value of media_asset.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.name
	 * @param name  the value for media_asset.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.alias
	 * @return  the value of media_asset.alias
	 * @mbggenerated
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.alias
	 * @param alias  the value for media_asset.alias
	 * @mbggenerated
	 */
	public void setAlias(String alias) {
		this.alias = alias == null ? null : alias.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.english_name
	 * @return  the value of media_asset.english_name
	 * @mbggenerated
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.english_name
	 * @param englishName  the value for media_asset.english_name
	 * @mbggenerated
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName == null ? null : englishName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.title
	 * @return  the value of media_asset.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.title
	 * @param title  the value for media_asset.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.subtitle
	 * @return  the value of media_asset.subtitle
	 * @mbggenerated
	 */
	public String getSubtitle() {
		return subtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.subtitle
	 * @param subtitle  the value for media_asset.subtitle
	 * @mbggenerated
	 */
	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle == null ? null : subtitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.brief
	 * @return  the value of media_asset.brief
	 * @mbggenerated
	 */
	public String getBrief() {
		return brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.brief
	 * @param brief  the value for media_asset.brief
	 * @mbggenerated
	 */
	public void setBrief(String brief) {
		this.brief = brief == null ? null : brief.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.keyword
	 * @return  the value of media_asset.keyword
	 * @mbggenerated
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.keyword
	 * @param keyword  the value for media_asset.keyword
	 * @mbggenerated
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword == null ? null : keyword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.director
	 * @return  the value of media_asset.director
	 * @mbggenerated
	 */
	public String getDirector() {
		return director;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.director
	 * @param director  the value for media_asset.director
	 * @mbggenerated
	 */
	public void setDirector(String director) {
		this.director = director == null ? null : director.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.actor
	 * @return  the value of media_asset.actor
	 * @mbggenerated
	 */
	public String getActor() {
		return actor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.actor
	 * @param actor  the value for media_asset.actor
	 * @mbggenerated
	 */
	public void setActor(String actor) {
		this.actor = actor == null ? null : actor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.writer
	 * @return  the value of media_asset.writer
	 * @mbggenerated
	 */
	public String getWriter() {
		return writer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.writer
	 * @param writer  the value for media_asset.writer
	 * @mbggenerated
	 */
	public void setWriter(String writer) {
		this.writer = writer == null ? null : writer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.producer
	 * @return  the value of media_asset.producer
	 * @mbggenerated
	 */
	public String getProducer() {
		return producer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.producer
	 * @param producer  the value for media_asset.producer
	 * @mbggenerated
	 */
	public void setProducer(String producer) {
		this.producer = producer == null ? null : producer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.showyear
	 * @return  the value of media_asset.showyear
	 * @mbggenerated
	 */
	public Integer getShowyear() {
		return showyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.showyear
	 * @param showyear  the value for media_asset.showyear
	 * @mbggenerated
	 */
	public void setShowyear(Integer showyear) {
		this.showyear = showyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.showtime
	 * @return  the value of media_asset.showtime
	 * @mbggenerated
	 */
	public Date getShowtime() {
		return showtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.showtime
	 * @param showtime  the value for media_asset.showtime
	 * @mbggenerated
	 */
	public void setShowtime(Date showtime) {
		this.showtime = showtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.duration
	 * @return  the value of media_asset.duration
	 * @mbggenerated
	 */
	public Integer getDuration() {
		return duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.duration
	 * @param duration  the value for media_asset.duration
	 * @mbggenerated
	 */
	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.movie_area
	 * @return  the value of media_asset.movie_area
	 * @mbggenerated
	 */
	public String getMovieArea() {
		return movieArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.movie_area
	 * @param movieArea  the value for media_asset.movie_area
	 * @mbggenerated
	 */
	public void setMovieArea(String movieArea) {
		this.movieArea = movieArea == null ? null : movieArea.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.movie_type
	 * @return  the value of media_asset.movie_type
	 * @mbggenerated
	 */
	public String getMovieType() {
		return movieType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.movie_type
	 * @param movieType  the value for media_asset.movie_type
	 * @mbggenerated
	 */
	public void setMovieType(String movieType) {
		this.movieType = movieType == null ? null : movieType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.movie_level
	 * @return  the value of media_asset.movie_level
	 * @mbggenerated
	 */
	public Integer getMovieLevel() {
		return movieLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.movie_level
	 * @param movieLevel  the value for media_asset.movie_level
	 * @mbggenerated
	 */
	public void setMovieLevel(Integer movieLevel) {
		this.movieLevel = movieLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.image_h_banner
	 * @return  the value of media_asset.image_h_banner
	 * @mbggenerated
	 */
	public String getImageHBanner() {
		return imageHBanner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.image_h_banner
	 * @param imageHBanner  the value for media_asset.image_h_banner
	 * @mbggenerated
	 */
	public void setImageHBanner(String imageHBanner) {
		this.imageHBanner = imageHBanner == null ? null : imageHBanner.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.image_h_small
	 * @return  the value of media_asset.image_h_small
	 * @mbggenerated
	 */
	public String getImageHSmall() {
		return imageHSmall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.image_h_small
	 * @param imageHSmall  the value for media_asset.image_h_small
	 * @mbggenerated
	 */
	public void setImageHSmall(String imageHSmall) {
		this.imageHSmall = imageHSmall == null ? null : imageHSmall.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.image_v_small
	 * @return  the value of media_asset.image_v_small
	 * @mbggenerated
	 */
	public String getImageVSmall() {
		return imageVSmall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.image_v_small
	 * @param imageVSmall  the value for media_asset.image_v_small
	 * @mbggenerated
	 */
	public void setImageVSmall(String imageVSmall) {
		this.imageVSmall = imageVSmall == null ? null : imageVSmall.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.video_play_url_low
	 * @return  the value of media_asset.video_play_url_low
	 * @mbggenerated
	 */
	public String getVideoPlayUrlLow() {
		return videoPlayUrlLow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.video_play_url_low
	 * @param videoPlayUrlLow  the value for media_asset.video_play_url_low
	 * @mbggenerated
	 */
	public void setVideoPlayUrlLow(String videoPlayUrlLow) {
		this.videoPlayUrlLow = videoPlayUrlLow == null ? null : videoPlayUrlLow
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.video_play_url_sd
	 * @return  the value of media_asset.video_play_url_sd
	 * @mbggenerated
	 */
	public String getVideoPlayUrlSd() {
		return videoPlayUrlSd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.video_play_url_sd
	 * @param videoPlayUrlSd  the value for media_asset.video_play_url_sd
	 * @mbggenerated
	 */
	public void setVideoPlayUrlSd(String videoPlayUrlSd) {
		this.videoPlayUrlSd = videoPlayUrlSd == null ? null : videoPlayUrlSd
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.video_play_url_hd
	 * @return  the value of media_asset.video_play_url_hd
	 * @mbggenerated
	 */
	public String getVideoPlayUrlHd() {
		return videoPlayUrlHd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.video_play_url_hd
	 * @param videoPlayUrlHd  the value for media_asset.video_play_url_hd
	 * @mbggenerated
	 */
	public void setVideoPlayUrlHd(String videoPlayUrlHd) {
		this.videoPlayUrlHd = videoPlayUrlHd == null ? null : videoPlayUrlHd
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.video_play_url_uhd
	 * @return  the value of media_asset.video_play_url_uhd
	 * @mbggenerated
	 */
	public String getVideoPlayUrlUhd() {
		return videoPlayUrlUhd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.video_play_url_uhd
	 * @param videoPlayUrlUhd  the value for media_asset.video_play_url_uhd
	 * @mbggenerated
	 */
	public void setVideoPlayUrlUhd(String videoPlayUrlUhd) {
		this.videoPlayUrlUhd = videoPlayUrlUhd == null ? null : videoPlayUrlUhd
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.copyright
	 * @return  the value of media_asset.copyright
	 * @mbggenerated
	 */
	public Integer getCopyright() {
		return copyright;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.copyright
	 * @param copyright  the value for media_asset.copyright
	 * @mbggenerated
	 */
	public void setCopyright(Integer copyright) {
		this.copyright = copyright;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.program_source
	 * @return  the value of media_asset.program_source
	 * @mbggenerated
	 */
	public String getProgramSource() {
		return programSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.program_source
	 * @param programSource  the value for media_asset.program_source
	 * @mbggenerated
	 */
	public void setProgramSource(String programSource) {
		this.programSource = programSource == null ? null : programSource
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.copyright_source
	 * @return  the value of media_asset.copyright_source
	 * @mbggenerated
	 */
	public String getCopyrightSource() {
		return copyrightSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.copyright_source
	 * @param copyrightSource  the value for media_asset.copyright_source
	 * @mbggenerated
	 */
	public void setCopyrightSource(String copyrightSource) {
		this.copyrightSource = copyrightSource == null ? null : copyrightSource
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.copyright_begindate
	 * @return  the value of media_asset.copyright_begindate
	 * @mbggenerated
	 */
	public Date getCopyrightBegindate() {
		return copyrightBegindate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.copyright_begindate
	 * @param copyrightBegindate  the value for media_asset.copyright_begindate
	 * @mbggenerated
	 */
	public void setCopyrightBegindate(Date copyrightBegindate) {
		this.copyrightBegindate = copyrightBegindate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.copyright_enddate
	 * @return  the value of media_asset.copyright_enddate
	 * @mbggenerated
	 */
	public Date getCopyrightEnddate() {
		return copyrightEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.copyright_enddate
	 * @param copyrightEnddate  the value for media_asset.copyright_enddate
	 * @mbggenerated
	 */
	public void setCopyrightEnddate(Date copyrightEnddate) {
		this.copyrightEnddate = copyrightEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.charge
	 * @return  the value of media_asset.charge
	 * @mbggenerated
	 */
	public Integer getCharge() {
		return charge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.charge
	 * @param charge  the value for media_asset.charge
	 * @mbggenerated
	 */
	public void setCharge(Integer charge) {
		this.charge = charge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.weight
	 * @return  the value of media_asset.weight
	 * @mbggenerated
	 */
	public Integer getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.weight
	 * @param weight  the value for media_asset.weight
	 * @mbggenerated
	 */
	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.creator
	 * @return  the value of media_asset.creator
	 * @mbggenerated
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.creator
	 * @param creator  the value for media_asset.creator
	 * @mbggenerated
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.create_time
	 * @return  the value of media_asset.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.create_time
	 * @param createTime  the value for media_asset.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.auditor
	 * @return  the value of media_asset.auditor
	 * @mbggenerated
	 */
	public String getAuditor() {
		return auditor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.auditor
	 * @param auditor  the value for media_asset.auditor
	 * @mbggenerated
	 */
	public void setAuditor(String auditor) {
		this.auditor = auditor == null ? null : auditor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.audit_time
	 * @return  the value of media_asset.audit_time
	 * @mbggenerated
	 */
	public Date getAuditTime() {
		return auditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.audit_time
	 * @param auditTime  the value for media_asset.audit_time
	 * @mbggenerated
	 */
	public void setAuditTime(Date auditTime) {
		this.auditTime = auditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.migu_contentid
	 * @return  the value of media_asset.migu_contentid
	 * @mbggenerated
	 */
	public String getMiguContentid() {
		return miguContentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.migu_contentid
	 * @param miguContentid  the value for media_asset.migu_contentid
	 * @mbggenerated
	 */
	public void setMiguContentid(String miguContentid) {
		this.miguContentid = miguContentid == null ? null : miguContentid
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.MAINCATEGORY
	 * @return  the value of media_asset.MAINCATEGORY
	 * @mbggenerated
	 */
	public String getMaincategory() {
		return maincategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.MAINCATEGORY
	 * @param maincategory  the value for media_asset.MAINCATEGORY
	 * @mbggenerated
	 */
	public void setMaincategory(String maincategory) {
		this.maincategory = maincategory == null ? null : maincategory.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media_asset.categorys
	 * @return  the value of media_asset.categorys
	 * @mbggenerated
	 */
	public String getCategorys() {
		return categorys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media_asset.categorys
	 * @param categorys  the value for media_asset.categorys
	 * @mbggenerated
	 */
	public void setCategorys(String categorys) {
		this.categorys = categorys == null ? null : categorys.trim();
	}
}